[SPARK-53054][CONNECT] Fix the connect.DataFrameReader default format behavior
### What changes were proposed in this pull request?
See title.

### Why are the changes needed?
Scala Spark Connect does not adhere to the [documented](https://spark.apache.org/docs/3.5.6/sql-data-sources-load-save-functions.html) behavior.

### Does this PR introduce _any_ user-facing change?
As documented in [Generic Load/Save Functions - Spark 3.5.6 Documentation](https://spark.apache.org/docs/3.5.6/sql-data-sources-load-save-functions.html), and similar to Spark Classic and the Python Spark Connect, Scala Spark Connect's `DataFrameReader` will now also default to the format set via the `spark.sql.sources.default` SQL configuration.

**Before**: `spark.read.load("..."`) throws

```
java.lang.IllegalArgumentException: The source format must be specified.
```
**Now**: `spark.read.load("...")` uses the format specified via `spark.sql.sources.default`

### How was this patch tested?
Test case added to ClientE2ETestSuite.

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #51761 from dillitz/fix-default-format-master.

Lead-authored-by: Robert Dillitz <r.dillitz@gmail.com>
Co-authored-by: Robert Dillitz <robert.dillitz@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>