[SPARK-51192][CONNECT] Expose `processWithoutResponseObserverForTesting` in `SparkConnectPlanner`
### What changes were proposed in this pull request?

Adds a new `processWithoutResponseObserverForTesting` private-package method scoped to `planner`. This method is called by `SparkConnectPlannerTestUtils#transform`.

### Why are the changes needed?

https://github.com/apache/spark/pull/47816 attempted to move `MockObserver` into source code to address compilation errors when open-source libraries attempt to test their command plugin extensions via the `SparkConnectPlannerUtils`.

However, this isn't enough as the error `java.lang.NoSuchMethodError: 'void org.apache.spark.sql.connect.planner.SparkConnectPlanner.process(org.apache.spark.connect.proto.Command, io.grpc.stub.StreamObserver` continues to be seen.

To address this shading issue, we move the creation of the `MockObserver` to the source code.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Existing tests

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #49921 from vicennial/SPARK-51192.

Authored-by: vicennial <venkata.gudesa@databricks.com>
Signed-off-by: Herman van Hovell <herman@databricks.com>