[SPARK-37231][SQL] Dynamic writes/reads of ANSI interval partitions
### What changes were proposed in this pull request?
In the PR, I propose to check that ANSI intervals can be written as partitions dynamically, and read back as intervals if the  schema is set correctly. The last one requires a fix in `PartitioningUtils. AnsiIntervalType` to handle ANSI interval types and cast partition value strings to desired interval types.

### Why are the changes needed?
1. To check that ANSI intervals can be saved as partitions values
2. To fix loading of ANSI intervals as partitions values. The example below demonstrates the issue:
```scala
scala> sql("SELECT INTERVAL '1' YEAR AS i, 0 as id").write.partitionBy("i").json("/Users/maximgekk/tmp/ansi_interval_json")

scala> spark.read.schema("i INTERVAL YEAR, id INT").json("/Users/maximgekk/tmp/ansi_interval_json")
java.lang.RuntimeException: Failed to cast value `INTERVAL %271%27 YEAR` to `YearMonthIntervalType(0,0)` for partition column `i`
  at org.apache.spark.sql.errors.QueryExecutionErrors$.failedToCastValueToDataTypeForPartitionColumnError(QueryExecutionErrors.scala:593)
  at org.apache.spark.sql.execution.datasources.PartitioningUtils$.$anonfun$parsePartitions$13(PartitioningUtils.scala:204)
```

### Does this PR introduce _any_ user-facing change?
No, this PR fixes the issues above. After the changes, the code works as expected:
```scala
scala> spark.read.schema("i INTERVAL YEAR, id INT").json("/Users/maximgekk/tmp/ansi_interval_json").show(false)
+---+-----------------+
|id |i                |
+---+-----------------+
|0  |INTERVAL '1' YEAR|
+---+-----------------+
```

### How was this patch tested?
By running new test:
```
$ build/sbt "test:testOnly *PartitionedWriteSuite"
```

Closes #34506 from MaxGekk/ansi-intervals-as-part-values.

Authored-by: Max Gekk <max.gekk@gmail.com>
Signed-off-by: Kousuke Saruta <sarutak@oss.nttdata.com>