[SPARK-54397][PYTHON] Make `UserDefinedType` hashable
### What changes were proposed in this pull request?
Fix the hashability of `UserDefinedType`

### Why are the changes needed?
UDT is not hashable, e.g.
```
In [11]: from pyspark.testing.objects import ExamplePointUDT

In [12]: e = ExamplePointUDT()

In [13]: {e: 0}
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[13], line 1
----> 1 {e: 0}

TypeError: unhashable type: 'ExamplePointUDT'

In [14]: from pyspark.ml.linalg import VectorUDT

In [15]: v = VectorUDT()

In [16]: {v: 1}
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[16], line 1
----> 1 {v: 1}

TypeError: unhashable type: 'VectorUDT'

```

see https://docs.python.org/3/reference/datamodel.html#object.__hash__

> If a class does not define an __eq__() method it should not define a __hash__() operation either; if it defines __eq__() but not __hash__(), its instances will not be usable as items in hashable collections.

> A class that overrides __eq__() and does not define __hash__() will have its __hash__() implicitly set to None. When the __hash__() method of a class is None, instances of the class will raise an appropriate TypeError when a program attempts to retrieve their hash value, and will also be correctly identified as unhashable when checking isinstance(obj, collections.abc.Hashable).

### Does this PR introduce _any_ user-facing change?
yes, `hash(udt)` will work after this fix

### How was this patch tested?
added tests

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #53113 from zhengruifeng/type_hashable.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>