[SPARK-8821] [EC2] Switched to binary mode
Otherwise the script will crash with

 - Downloading boto...
Traceback (most recent call last):
  File "ec2/spark_ec2.py", line 148, in <module>
    setup_external_libs(external_libs)
  File "ec2/spark_ec2.py", line 128, in setup_external_libs
    if hashlib.md5(tar.read()).hexdigest() != lib["md5"]:
  File "/usr/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

In case of an utf8 env setting.