[SPARK-39756][PS] Better error messages for missing pandas scalars
### What changes were proposed in this pull request?
pandas scalars are not reimplemented in pandas API on Spark intentionally, as part of the initial design principle.

Users can use pandas scalars in pandas API on Spark directly.

However, error messages are confusing when users mistakenly assume pandas scalars are reimplemented, for example, calling `ps.Timestamp` as below

```py
>>> ps.Series([ps.Timestamp(1994, 1, 31)])
Traceback (most recent call last):
...
AttributeError: module 'pyspark.pandas' has no attribute 'Timestamp'
```

Users may jump to the conclusion that a Series of timestamp data is not supported.

However, we do support that by using `pd.Timestamp` as below:

```py
>>> ps.Series([pd.Timestamp(1994, 1, 31)])
0   1994-01-31
dtype: datetime64[ns]
```

We should inform users to use pandas scalars instead.

In addition, `PandasNotImplementedError` should be raised rather than `AttributeError` for clarity.

### Why are the changes needed?
Better error messages should be clear and tell how to fix the errors.
That can enhance usability, debuggability, and furthermore, user adoption.

### Does this PR introduce _any_ user-facing change?
Yes. Error messages change. For example:

**Before**
```py
>>> ps.Series([ps.Timestamp(1994, 1, 31)])
Traceback (most recent call last):
...
AttributeError: module 'pyspark.pandas' has no attribute 'Timestamp'
```

**After**
```py
>>> ps.Series([ps.Timestamp(1994, 1, 31)])
Traceback (most recent call last):
...
pyspark.pandas.exceptions.PandasNotImplementedError: The scalar `ps.Timestamp` is not reimplemented in pyspark.pandas; use `pd.Timestamp`.
```
### How was this patch tested?
Unit tests.

Closes #37168 from xinrong-meng/ps_missing_scalar.

Authored-by: Xinrong Meng <xinrong.meng@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>