[SPARK-44876][PYTHON] Fix Arrow-optimized Python UDF on Spark Connect
### What changes were proposed in this pull request?

Fixes Arrow-optimized Python UDF on Spark Connect.

Also enables the missing test `pyspark.sql.tests.connect.test_parity_arrow_python_udf`.

### Why are the changes needed?

`pyspark.sql.tests.connect.test_parity_arrow_python_udf` is not listed in `dev/sparktestsupport/modules.py`, and it fails when running manually.

```
======================================================================
ERROR [0.072s]: test_register (pyspark.sql.tests.connect.test_parity_arrow_python_udf.ArrowPythonUDFParityTests)
----------------------------------------------------------------------
Traceback (most recent call last):
...
pyspark.errors.exceptions.base.PySparkRuntimeError: [SCHEMA_MISMATCH_FOR_PANDAS_UDF] Result vector from pandas_udf was not the required length: expected 1, got 38.
```

The failure had not been captured because the test is missing in the `module.py` file.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

Closes #42568 from ueshin/issues/SPARK-44876/test_parity_arrow_python_udf.

Authored-by: Takuya UESHIN <ueshin@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
(cherry picked from commit 75c0b8b61ca53c3763c8e43e83b93b34688ea246)
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>