[SPARK-38680][INFRA] Set upperbound for pandas-stubs in CI
### What changes were proposed in this pull request?

`pandas-stubs` released `1.2.0.54` but that seems like havng a breaking change:

e.g., ) https://github.com/apache/spark/runs/5729037000?check_suite_focus=true

```
starting mypy annotations test...
annotations failed mypy checks:
python/pyspark/pandas/ml.py:62: error: Incompatible types in assignment (expression has type "Index", variable has type "MultiIndex")  [assignment]
python/pyspark/pandas/frame.py:6133: error: unused "type: ignore" comment
python/pyspark/pandas/frame.py:6292: error: Incompatible types in assignment (expression has type "Index", variable has type "MultiIndex")  [assignment]
Found 3 errors in 2 files (checked 325 source files)
```

This PR proposes to pin pandas-stubs version for now to avoid breaking CI.

### Why are the changes needed?

To have the stable CI status.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

It should be tested in this CI.

Closes #35996 from HyukjinKwon/SPARK-38680.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
(cherry picked from commit 2d90659d09b153ebd4100db686d5c63e8dbe63db)
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>