[SPARK-48620][PYTHON] Fix internal raw data leak in `YearMonthIntervalType` and `CalendarIntervalType`
### What changes were proposed in this pull request?
Fix internal raw data leak in `YearMonthIntervalType/CalendarIntervalType`:

PySpark Classic: it fails collection of `YearMonthIntervalType/CalendarIntervalType`

### Why are the changes needed?
the raw data should not be leaked

### Does this PR introduce _any_ user-facing change?
**PySpark Classic** (before):
```
In [4]: spark.sql("SELECT INTERVAL '10-8' YEAR TO MONTH AS interval").first()[0]
Out[4]: 128

In [5]: spark.sql("SELECT make_interval(100, 11, 1, 1, 12, 30, 01.001001)").first()[0]
Out[5]: {'__class__': 'org.apache.spark.unsafe.types.CalendarInterval'}
```

**PySpark Classic** (after):
```
In [1]: spark.sql("SELECT INTERVAL '10-8' YEAR TO MONTH AS interval").first()
---------------------------------------------------------------------------
PySparkNotImplementedError                Traceback (most recent call last)
Cell In[1], line 1
----> 1 spark.sql("SELECT INTERVAL '10-8' YEAR TO MONTH AS interval").first()

...

PySparkNotImplementedError: [NOT_IMPLEMENTED] YearMonthIntervalType.fromInternal is not implemented.

In [2]: import os

In [3]: os.environ['PYSPARK_YM_INTERVAL_LEGACY'] = "1"

In [4]: spark.sql("SELECT INTERVAL '10-8' YEAR TO MONTH AS interval").first()
Out[4]: Row(interval=128)
```

### How was this patch tested?
Added test

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #46975 from zhengruifeng/fail_ym_interval_collect.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>