[SPARK-54517][PYTHON][TESTS][FOLLOWUP] Fix typehints using ellipsis
### What changes were proposed in this pull request?

This is a follow-up of #53223.

Fixes a typehint using ellipsis that are not available as type arguments in Python 3.10.

### Why are the changes needed?

#53223 caused a test failure in Python 3.10 tests:

```
  File "/__w/spark/spark/python/pyspark/testing/connectutils.py", line 312, in <module>
    ) -> Callable[[...], ...]:
         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pypy/pypy3.10/lib/pypy3.10/typing.py", line 1206, in __getitem__
    return self.__getitem_inner__(params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pypy/pypy3.10/lib/pypy3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pypy/pypy3.10/lib/pypy3.10/typing.py", line 1212, in __getitem_inner__
    result = _type_check(result, msg)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/pypy/pypy3.10/lib/pypy3.10/typing.py", line 176, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Callable[args, result]: result must be a type. Got Ellipsis.
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

The existing tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #53238 from ueshin/issues/SPARK-54517/typehints.

Authored-by: Takuya Ueshin <ueshin@databricks.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
(cherry picked from commit c11edf9e8d21417c4a44bcd1a35b1792f556af19)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>