[SPARK-51739][PYTHON] Validate Arrow schema from mapInArrow & mapInPandas & DataSource
### What changes were proposed in this pull request?

Check the actual Arrow batch schema against the declared schema in `MapInBatchEvaluator`, throwing error if they don't match.

Also fix Pandas to Arrow conversion in `ArrowStreamPandasUDFSerializer` to respect nullability of output schema fields.

### Why are the changes needed?

To improve error message and reject suspicious usage.

### Does this PR introduce _any_ user-facing change?

Yes.

#### Behaviour change

1. Some previously suspicious but accepted schema mismatches are now no longer valid.

    This includes:
    - extraneous fields (previously ignored)
    - wrong order of fields of the same type (previously accepted but in wrong order)
    - expected non-nullable field is actually nullable (previously ignored)

    Example:
    ```py
    from pyspark.sql.datasource import DataSource, DataSourceReader
    from pyspark.sql.pandas.types import to_arrow_schema
    import pyarrow as pa

    expected = StructType.fromDDL("a int, b int")
    actual = StructType.fromDDL("b int, a int")  # wrong order of fields

    class TestDataSource(DataSource):
        def schema(self):
            return expected
        def reader(self, schema):
            return TestReader()

    class TestReader(DataSourceReader):
        def read(self, partition):
            schema = to_arrow_schema(actual)
            yield pa.record_batch([[1], [2]], schema=schema)

    spark.dataSource.register(TestDataSource)
    spark.read.format("TestDataSource").load().show()
    ```
    Before:
    ```
    +---+---+
    |  a|  b|
    +---+---+
    |  1|  2|
    +---+---+
    ```
    Now:
    ```
    org.apache.spark.SparkException: [ARROW_TYPE_MISMATCH] Invalid schema from pandas_udf(): expected StructType(StructField(a,IntegerType,true),StructField(b,IntegerType,true)), got StructType(StructField(b,LongType,true),StructField(a,LongType,true)). SQLSTATE: 42K0G
    ```

2. For other schema mismatches, the error changed from internal error to a clearer `ARROW_TYPE_MISMATCH` error.

    This includes
    - wrong field types
    - less than expected number of fields

    Example:
    ```py
    from pyspark.sql.pandas.types import to_arrow_schema
    from pyspark.sql.types import StructType, StructField, IntegerType
    import pyarrow as pa

    expected = StructType([StructField("a", IntegerType()), StructField("b", IntegerType())])
    actual = StructType([StructField("a", IntegerType())])  # missing a column

    def fun(iterator):
        for batch in iterator:
            schema = to_arrow_schema(actual)
            yield pa.record_batch([[1]], schema=schema)

    spark.range(2).mapInArrow(fun, expected).show()
    ```
    Before:
    ```
    java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.apache.spark.sql.vectorized.ArrowColumnVector.getChild(ArrowColumnVector.java:134)
        at org.apache.spark.sql.execution.python.MapInBatchEvaluatorFactory$MapInBatchEvaluator.$anonfun$eval$3(MapInBatchEvaluatorFactory.scala:82)
        ...
    ```
    Now:
    ```
    org.apache.spark.SparkException: [ARROW_TYPE_MISMATCH] Invalid schema from pandas_udf(): expected StructType(StructField(a,IntegerType,true),StructField(b,IntegerType,true)), got StructType(StructField(a,IntegerType,true)). SQLSTATE: 42K0G
    ```

### How was this patch tested?

End-to-end tests in `python/pyspark/sql/tests/arrow/test_arrow_map.py`

### Was this patch authored or co-authored using generative AI tooling?

No

Closes #50531 from wengh/validate-arrow-type.

Authored-by: Haoyu Weng <wenghy02@gmail.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>