[SPARK-44281][SQL] Move QueryCompilation error that used by DataType to sql/api as DataTypeErrors
### What changes were proposed in this pull request?

Move QueryCompilation error that used by DataType to sql/api as DataTypeErrors.

### Why are the changes needed?

To further simplify DataType interface.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Exiting tests.

Closes #41835 from amaliujia/compilation_errors.

Authored-by: Rui Wang <rui.wang@databricks.com>
Signed-off-by: Herman van Hovell <herman@databricks.com>