Revert "[SPARK-46377][INFRA] Upgrade labeler action to v5"
### What changes were proposed in this pull request?
This reverts commit 270da6f9b7b331e455d1f0bd1309fb87bc8740ab.

### Why are the changes needed?
Master CI failed:

```
Run actions/labelerv5
The configuration file (path: .github/labeler.yml) was not found locally, fetching via the api
Error: Error: found unexpected type for label 'INFRA' (should be array of config options)
Error: found unexpected type for label 'INFRA' (should be array of config options)
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GA

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #44344 from panbingkun/SPARK-46377_revert.

Authored-by: panbingkun <pbk1982@gmail.com>
Signed-off-by: yangjie01 <yangjie01@baidu.com>