[SPARK-39216][SQL] Do not collapse projects in CombineUnions if it hasCorrelatedSubquery
### What changes were proposed in this pull request?

Makes `CombineUnions` do not collapse projects if it hasCorrelatedSubquery. For example:
```sql
SELECT (SELECT IF(x, 1, 0)) AS a
FROM (SELECT true) t(x)
UNION
SELECT 1 AS a
```

It will throw exception:
```
java.lang.IllegalStateException: Couldn't find x#4 in []
```

### Why are the changes needed?

Fix bug.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Unit test.

Closes #36595 from wangyum/SPARK-39216.

Authored-by: Yuming Wang <yumwang@ebay.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
(cherry picked from commit 85bb7bf008d0346feaedc2aab55857d8f1b19908)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>