[SPARK-53671][PYTHON] Exclude 0-args from `@udf` eval type inference
### What changes were proposed in this pull request?
Exclude 0-args from `udf` eval type inference

### Why are the changes needed?
this case fails after https://github.com/apache/spark/pull/52323

```
In [5]: from pyspark.sql.functions import udf

In [6]: udf()
   ...: def f1() -> int:
   ...:     return 1
   ...:

In [7]: spark.range(10).select(f1().alias("res")).collect()
25/09/23 10:08:16 ERROR Executor: Exception in task 0.0 in stage 5.0 (TID 21)
org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/Users/ruifeng.zheng/spark/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 473, in _create_array
    return pa.Array.from_pandas(
           ~~~~~~~~~~~~~~~~~~~~^
        series, mask=mask, type=arrow_type, safe=self._safecheck
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "pyarrow/array.pxi", line 1259, in pyarrow.lib.Array.from_pandas
  File "pyarrow/array.pxi", line 365, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 91, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: Expected a string or bytes dtype, got int64

The above exception was the direct cause of the following exception:
```

that is due to `f1` is inferred as a `SQL_GROUPED_AGG_PANDAS_UDF`.
I think 0-arg for `SQL_GROUPED_AGG_PANDAS_UDF` doesn't make sense, but to be conservative, I just exclude 0-arg in `udf` side in this PR. We can revisit the `pandas_udf` / `arrow_udf` later.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
added UTs

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #52416 from zhengruifeng/fix_udf_type_hint.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>