[SPARK-43968][PYTHON] Improve error messages for Python UDTFs with wrong number of outputs
### What changes were proposed in this pull request?

This PR improves the error messages for Python UDTFs when the number of outputs mismatches the number of outputs specified in the return type of the UDTFs.

### Why are the changes needed?

To make Python UDTFs more user-friendly.

### Does this PR introduce _any_ user-facing change?

Yes. This PR improves the error messages.
Before this change, the error thrown by Spark will be a java IllegalStateException:
```
java.lang.IllegalStateException: Input row doesn't have expected number of values required by the schema
```
After this PR, it will throw a clearer error message with an error class:
```
[UDTF_RETURN_SCHEMA_MISMATCH] The number of columns in the result does not match the specified schema
```

### How was this patch tested?

Existing tests and new unit tests.

Closes #42157 from allisonwang-db/spark-43968-py-udtf-checks.

Authored-by: allisonwang-db <allison.wang@databricks.com>
Signed-off-by: Takuya UESHIN <ueshin@databricks.com>