Revert "[SPARK-40047][TEST] Exclude unused `xalan` transitive dependency from `htmlunit`"
### What changes were proposed in this pull request?
This pr revert SPARK-40047 due to mvn test still need this dependency.

### Why are the changes needed?
mvn test still need `xalan` dependency although GA passed before this pr.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

- Pass GitHub Actions
- Manual test:

```
mvn clean install -DskipTests -pl core -am
build/mvn clean test -pl core -Dtest=noen -DwildcardSuites=org.apache.spark.ui.UISeleniumSuite
```

**Before**
```
UISeleniumSuite:
*** RUN ABORTED ***
  java.lang.NoClassDefFoundError: org/apache/xml/utils/PrefixResolver
  at java.lang.Class.getDeclaredFields0(Native Method)
  at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
  at java.lang.Class.getField0(Class.java:2975)
  at java.lang.Class.getField(Class.java:1701)
  at com.gargoylesoftware.htmlunit.svg.SvgElementFactory.<clinit>(SvgElementFactory.java:64)
  at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.<clinit>(HtmlUnitNekoHtmlParser.java:77)
  at com.gargoylesoftware.htmlunit.DefaultPageCreator.<clinit>(DefaultPageCreator.java:93)
  at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:191)
  at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:273)
  at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:263)
  ...
  Cause: java.lang.ClassNotFoundException: org.apache.xml.utils.PrefixResolver
  at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
  at java.lang.Class.getDeclaredFields0(Native Method)
  at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
  at java.lang.Class.getField0(Class.java:2975)
  at java.lang.Class.getField(Class.java:1701)
  at com.gargoylesoftware.htmlunit.svg.SvgElementFactory.<clinit>(SvgElementFactory.java:64)
  at com.gargoylesoftware.htmlunit.html.parser.neko.HtmlUnitNekoHtmlParser.<clinit>(HtmlUnitNekoHtmlParser.java:77)
  ...
```

**After**
```
UISeleniumSuite:
- all jobs page should be rendered even though we configure the scheduling mode to fair
- effects of unpersist() / persist() should be reflected
- failed stages should not appear to be active
- spark.ui.killEnabled should properly control kill button display
- jobs page should not display job group name unless some job was submitted in a job group
- job progress bars should handle stage / task failures
- job details page should display useful information for stages that haven't started
- job progress bars / cells reflect skipped stages / tasks
- stages that aren't run appear as 'skipped stages' after a job finishes
- jobs with stages that are skipped should show correct link descriptions on all jobs page
- attaching and detaching a new tab
- kill stage POST/GET response is correct
- kill job POST/GET response is correct
- stage & job retention
- live UI json application list
- job stages should have expected dotfile under DAG visualization
- stages page should show skipped stages
- Staleness of Spark UI should not last minutes or hours
- description for empty jobs
- Support disable event timeline
Run completed in 17 seconds, 986 milliseconds.
Total number of tests run: 20
Suites: completed 2, aborted 0
Tests: succeeded 20, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
```

Closes #37508 from LuciferYang/revert-40047.

Authored-by: yangjie01 <yangjie01@baidu.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
(cherry picked from commit afd7098c7fb6c95aece39acc32cdad764c984cd2)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>