[SPARK-50210][CORE] Fix `SparkSubmit` to show REST API `kill` response properly
### What changes were proposed in this pull request?

This PR aims to fix `SparkSubmit` to show `REST API` `kill` response properly.

### Why are the changes needed?

**PREPARE SPARK CLUSTER**
```
$ SPARK_MASTER_OPTS='-Dspark.master.rest.enabled=true' sbin/start-master.sh
$ sbin/start-worker.sh spark://$(hostname):7077
```

**BEFORE (4.0.0-preview2)**
`spark-submit` didn't show error messages properly.
```
$ bin/spark-submit --master spark://$(hostname):6066 --kill invalid-submission-id
```

**AFTER**
```
$ bin/spark-submit --master spark://$(hostname):6066 --kill invalid-submission-id
Error: Driver invalid-submission-id has already finished or does not exist
```

```
$ sh examples/src/main/scripts/submit-pi.sh
{
  "action" : "CreateSubmissionResponse",
  "message" : "Driver successfully submitted as driver-20241102232042-0000",
  "serverSparkVersion" : "4.0.0-SNAPSHOT",
  "submissionId" : "driver-20241102232042-0000",
  "success" : true
}%

$ bin/spark-submit --master spark://$(hostname):6066 --kill driver-20241102232042-0000
driver-20241102232042-0000 is killed successfully.
```

### Does this PR introduce _any_ user-facing change?

Yes, but this logs show additional log messages.

### How was this patch tested?

Manual tests because this requires a Spark Standalone Cluster and the difference is only a log of `spark-submit`.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #48742 from dongjoon-hyun/SPARK-50210.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: yangjie01 <yangjie01@baidu.com>
(cherry picked from commit 9cf98ed41b2de1b44c44f0b4d1273d46761459fe)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>