[SPARK-50133][PYTHON][CONNECT] Support DataFrame conversion to table argument in Spark Connect Python Client
### What changes were proposed in this pull request?
Support DataFrame conversion to table argument in Spark Connect Python Client.

### Why are the changes needed?

User-Defined Table Functions (UDTFs) are widely used in Spark workflows, which often require a table argument. While Spark SQL supports constructs like TABLE() for this purpose, there is no direct API in PySpark convert a DataFrame into a table argument. So we propose to support DataFrame conversion to table arguments, and enable UDTFs to accept table arguments.

PySpark Classic already has this implemented. The PR proposes to implement this in Spark Connect Python Client.

### Does this PR introduce _any_ user-facing change?
Yes DataFrame conversion to table argument is supported in Spark Connect Python Client, and UDTFs accept table arguments as shown below.
```py
>>> spark
<pyspark.sql.connect.session.SparkSession object at 0x13dcf0eb0>
>>> from pyspark.sql.functions import udtf
>>> from pyspark.sql import Row
>>>
>>> udtf(returnType="a: int")
... class TestUDTF:
...     def eval(self, row: Row):
...         if row[0] > 5:
...             yield row[0],
...
>>> df = spark.range(8)
>>>
>>> TestUDTF(df.asTable()).show()
+---+
|  a|
+---+
|  6|
|  7|
+---+
>>> TestUDTF(df.asTable().partitionBy(df.id)).show()
+---+
|  a|
+---+
|  6|
|  7|
+---+
>>> TestUDTF(df.asTable().partitionBy(df.id).orderBy(df.id)).show()
+---+
|  a|
+---+
|  6|
|  7|
+---+
>>> TestUDTF(df.asTable().withSinglePartition()).show()
+---+
|  a|
+---+
|  6|
|  7|
+---+
>>> TestUDTF(df.asTable().partitionBy(df.id).withSinglePartition()).show()
Traceback (most recent call last):
...
    raise PySparkValueError(
pyspark.errors.exceptions.base.PySparkValueError: Cannot call withSinglePartition() after partitionBy() or withSinglePartition() has been called.
```

### How was this patch tested?
Unit tests.

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #49424 from xinrong-meng/tableArgConnect.

Authored-by: Xinrong Meng <xinrong@apache.org>
Signed-off-by: Xinrong Meng <xinrong@apache.org>
(cherry picked from commit e037cb119a286fa8e5260a4bbd93760806050443)
Signed-off-by: Xinrong Meng <xinrong@apache.org>