[SPARK-50492][SS][FOLLOWUP][3.5] Change `def references` to `lazy val references` in `DeduplicateWithinWatermark` to fix the compilation issue
### What changes were proposed in this pull request?
This pr change `def references` to `lazy val references` in `DeduplicateWithinWatermark` to fix the following compilation error：

- https://github.com/apache/spark/actions/runs/12191807324/job/34011354774

```
[error] /home/runner/work/spark/spark/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/basicLogicalOperators.scala:1948:16: overriding lazy value references in class QueryPlan of type org.apache.spark.sql.catalyst.expressions.AttributeSet;
[error]  method references needs to be a stable, immutable value
[error]   override def references: AttributeSet = AttributeSet(keys) ++
[error]                ^
[error] one error found
```

### Why are the changes needed?
Fix compile error.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #49087 from LuciferYang/SPARK-50492-FOLLOWUP-3.5.

Authored-by: yangjie01 <yangjie01@baidu.com>
Signed-off-by: yangjie01 <yangjie01@baidu.com>