[SPARK-52346][SDP] Propagate partition columns from destination for BatchTableWrite
### What changes were proposed in this pull request?

Propagate partition columns specified in the destination table into during flow execution for batch table write.

Fix below exception during flow execution:
```
org.apache.spark.sql.AnalysisException: Specified partitioning does not match that of the existing table spark_catalog.default.mv.
Specified partition columns: [].
Existing partition columns: [id_mod].
```

### Why are the changes needed?

In "append" mode with saveAsTable, partition columns must be specified in query because the format and options of the existing table is used, and the table could have been created with partition columns.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

New unit tests

### Was this patch authored or co-authored using generative AI tooling?

No

Closes #52119 from JiaqiWang18/flow-exe-propagate-partition-columns.

Authored-by: Jacky Wang <jacky.wang@databricks.com>
Signed-off-by: Gengliang Wang <gengliang@apache.org>