[SPARK-38033][SS] The SS processing cannot be started because the com…
### What changes were proposed in this pull request?

The code of method: populateStartOffsets in class: org.apache.spark.sql.execution.streaming.MicroBatchExecution is modified.

### Why are the changes needed?

In some unexpected cases, commit and offset are inconsistent, and offset is not written into HDFS continuously, as follows:

        commits
        /tmp/streaming_xxxxxxxx/commits/113256
        /tmp/streaming_xxxxxxxx/commits/113257

        offsets
        /tmp/streaming_xxxxxxxx/offsets/113257
        /tmp/streaming_xxxxxxxx/offsets/113259
When we start the streaming program, batch ${latestBatchId - 1} is 113258, but offsets 113258 doesn't exist, an exception will be thrown, resulting in the program cannot be started. As an improvement, Spark doesn‘t need to repair itself, but we could probably do some simply analysis and give better error message.

### Does this PR introduce _any_ user-facing change?

Yes.
An error message is logged if the exception is thrown.

### How was this patch tested?

I have provided a test case that can output logs correctly.
We can run test("SPARK-38033: SS cannot be....") in the MicroBatchExecutionSuite class. In fact, I simulated a corresponding scenario to test the original exception.This exception validates normally and outputs a new error message, as follows:

    11:00:26.271 WARN org.apache.spark.sql.execution.streaming.ResolveWriteToStream: spark.sql.adaptive.enabled is not supported in streaming DataFrames/Datasets and will be disabled.
    11:00:26.675 ERROR org.apache.spark.sql.execution.streaming.MicroBatchExecution: The offset log for batch 3 doesn't exist, which is required to restart the query from the latest batch 4 from the offset log. Please ensure there are two subsequent offset logs available for the latest batch via manually deleting the offset file(s). Please also ensure the latest batch for commit log is equal or one batch earlier than the latest batch for offset log.
    11:00:26.690 ERROR org.apache.spark.sql.execution.streaming.MicroBatchExecution: Query [id = d4358946-170c-49a7-823b-d8e4e9126616, runId = 9e7f12b8-6c10-4f36-b5c5-136e1bace8de] terminated with error
    java.lang.IllegalStateException: batch 3 doesn't exist
	    at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$populateStartOffsets$1(MicroBatchExecution.scala:338) ~[classes/:?]
	    at scala.Option.getOrElse(Option.scala:189) ~[scala-library-2.12.15.jar:?]
	    at org.apache.spark.sql.execution.streaming.MicroBatchExecution.populateStartOffsets(MicroBatchExecution.scala:331) ~[classes/:?]
	    at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$2(MicroBatchExecution.scala:222) ~[classes/:?]
	    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23) ~[scala-library-2.12.15.jar:?]
	    at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:375) ~[classes/:?]
	    at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:373) ~[classes/:?]

Authored-by: LeeeeLiu liuqt1024gmail.com

Closes #35513 from LeeeeLiu/SPARK-38033-m.

Authored-by: qitao liu <liuqitao@haizhi.com>
Signed-off-by: Jungtaek Lim <kabhwan.opensource@gmail.com>