[SPARK-24703][SQL]: To add support to multiply CalendarInterval with Integral Type.         ## What changes were proposed in this pull request?
        This change adds capability to multiply Calender interval.

        Earlier the multiplication was throwing exception as follow:
        spark.sql("select  interval '1' day * 3").show()

        org.apache.spark.sql.AnalysisException: cannot resolve '(interval 1 days * 3)' due to data type mismatch: differing types in '(interval 1 days) * 3' (int and calendarinterval).; line 1 pos 7;
        'Project [unresolvedalias((interval 1 days * 3) , None)]

        +- OneRowRelation

        at org.apache.spark.sql.catalyst.analysis.package.failAnalysis(package.scala:42)
        at org.apache.spark.sql.catalyst.analysis.CheckAnalysis1433anonfun1433anonfun.applyOrElse(CheckAnalysis.scala:93)
        at

        but now, we have added this support.

        ## How was this patch tested?

        Added test case in CalendarIntervalSuite.java, ArithmeticExpressionSuite.scala and ExpressionTypeCheckingSuite.scala
        Also, tested by spark-shell by multiplying calendarinterval with Integral type.