[SPARK-26564] Fix misleading error message about spark.network.timeout and spark.executor.heartbeatInterval
If users set equivalent values to spark.network.timeout and spark.executor.heartbeatInterval, they get the following message:

```
java.lang.IllegalArgumentException: requirement failed: The value of spark.network.timeout=120s must be no less than the value of spark.executor.heartbeatInterval=120s.
```

But it's misleading since it can be read as they could be equal. So this fix replaces "no less than" with "greater than".