[MINOR][PYTHON][DOCS] Fix documentation for Python's recentProgress & lastProgress
This small PR fixes incorrect documentation in Structured Streaming Guide where Python's  `recentProgress` & `lastProgress` where shown as functions although they are [properties](https://github.com/apache/spark/blob/master/python/pyspark/sql/streaming.py#L117), so if they are called as functions it generates error:

```
>>> query.lastProgress()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'dict' object is not callable
```

The documentation was erroneous, and needs to be fixed to avoid confusion by readers

yes, it's a fix of the documentation

Not necessary

Closes #34947 from alexott/fix-python-recent-progress-docs.

Authored-by: Alex Ott <alexott@gmail.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
(cherry picked from commit bad96e6d029dff5be9efaf99f388cd9436741b6f)
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>