[SPARK-42487][BUILD] Upgrade Netty to 4.1.89
### What changes were proposed in this pull request?
This pr aims upgrade netty from 4.1.88 to 4.1.89.

### Why are the changes needed?
This is a bug fix version, this release contains a fix for two regressions that were introduced by 4.1.88.Final:

- Don't fail on HttpObjectDecoder's maxHeaderSize greater then (Integer.MAX_VALUE - 2) ([#13216](https://github.com/netty/netty/pull/13216))
- dyld: Symbol not found: _netty_jni_util_JNI_OnLoad when upgrading from 4.1.87.Final to 4.1.88.Final ([#13214](https://github.com/netty/netty/pull/13214))

All changes between 4.1.88 and 4.1.89 as follows:

- https://github.com/netty/netty/compare/netty-4.1.88.Final...netty-4.1.89.Final

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass Github Actions

Closes #40081 from LuciferYang/SPARK-42487.

Authored-by: yangjie01 <yangjie01@baidu.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>