[SPARK-51074][SS][CONNECT] Set timeout for communicating init configs in streaming foreachBatch
### What changes were proposed in this pull request?

We observed that when the python process is stuck during initialization (sending init configs, e.g. serialized python function), the jvm has no way to know. As a result, there are cases of the jvm stuck at `dataIn.readInt()` ƒrom a stuck python process. Then the job won't be showing as failed, although no queries are successfully started.

Here we add a timeout for this socket during initialization so we fail fast.

### Why are the changes needed?

Spark Connect improvement

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

I can't find a way to write a integration test, so I test it by manually setting the timeout from jvm side to 5 seconds, and let the python foreach_batch_worker to sleep for 30 sec in this PR: https://github.com/apache/spark/pull/49783

And I was able to see the error:
```
>>> q = df.writeStream.foreachBatch(feb2).trigger(processingTime="30 seconds").start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wei.liu/oss-spark/python/pyspark/sql/connect/streaming/readwriter.py", line 656, in start
    return self._start_internal(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wei.liu/oss-spark/python/pyspark/sql/connect/streaming/readwriter.py", line 625, in _start_internal
    (_, properties, _) = self._session.client.execute_command(cmd)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wei.liu/oss-spark/python/pyspark/sql/connect/client/core.py", line 1121, in execute_command
    data, _, metrics, observed_metrics, properties = self._execute_and_fetch(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wei.liu/oss-spark/python/pyspark/sql/connect/client/core.py", line 1533, in _execute_and_fetch
    for response in self._execute_and_fetch_as_iterator(
  File "/Users/wei.liu/oss-spark/python/pyspark/sql/connect/client/core.py", line 1510, in _execute_and_fetch_as_iterator
    self._handle_error(error)
  File "/Users/wei.liu/oss-spark/python/pyspark/sql/connect/client/core.py", line 1784, in _handle_error
    self._handle_rpc_error(error)
  File "/Users/wei.liu/oss-spark/python/pyspark/sql/connect/client/core.py", line 1860, in _handle_rpc_error
    raise convert_exception(
pyspark.errors.exceptions.connect.SparkConnectGrpcException: (org.apache.spark.api.python.StreamingPythonRunner$StreamingPythonRunnerInitializationTimeoutException) [STREAMING_PYTHON_RUNNER_INITIALIZATION_TIMEOUT_FAILURE] Streaming Runner initialization failed. Socket connection timeout. Cause: Read timed out SQLSTATE: XXKST

JVM stacktrace:
org.apache.spark.api.python.StreamingPythonRunner$StreamingPythonRunnerInitializationTimeoutException
	at org.apache.spark.api.python.StreamingPythonRunner.init(StreamingPythonRunner.scala:104)
	at org.apache.spark.sql.connect.planner.StreamingForeachBatchHelper$.pythonForeachBatchWrapper(StreamingForeachBatchHelper.scala:140)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.handleWriteStreamOperationStart(SparkConnectPlanner.scala:3058)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.process(SparkConnectPlanner.scala:2483)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.handleCommand(ExecuteThreadRunner.scala:322)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1(ExecuteThreadRunner.scala:224)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1$adapted(ExecuteThreadRunner.scala:196)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:341)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:794)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:341)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:94)
	at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:112)
	at org.apache.spark.sql.artifact.ArtifactManager.withClassLoaderIfNeeded(ArtifactManager.scala:106)
	at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:111)
	at org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:340)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.executeInternal(ExecuteThreadRunner.scala:196)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.org$apache$spark$sql$connect$execution$ExecuteThreadRunner$$execute(ExecuteThreadRunner.scala:125)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.run(ExecuteThreadRunner.scala:347)
```

### Was this patch authored or co-authored using generative AI tooling?

No

Closes #49784 from WweiL/feb-timoeut-init.

Authored-by: Wei Liu <wei.liu@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>