[SPARK-53486][ML][PYTHON] Avoid setting `weights_only=False` in torch model load
### What changes were proposed in this pull request?
Avoid setting `weights_only=False` in torch model load.

By applying the default value of `weights_only`:
1, torch<2.6.0, the default value is false, no behavior change;
2, torch>=2.6.0, the default value is true, then the model load will require setting safe globals:
```
_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint.
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL torch.nn.modules.container.Sequential was not an allowed
global by default. Please use `torch.serialization.add_safe_globals([torch.nn.modules.container.Sequential])` or the `torch.serialization.safe_globals([torch.nn.modules.container.Sequential])` context manager to allowlist this global if you trust this class/function.
```

After this change, the behavior is the same as the pytorch

### Why are the changes needed?

> Loading un-trusted checkpoint with weights_only=False MUST never be done.

as per https://github.com/pytorch/pytorch/security

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #52231 from zhengruifeng/torch_weights_only.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>