[SPARK-57711][SQL][TEST][FOLLOWUP] Fix linter failure
### What changes were proposed in this pull request?
This PR fixes a liter failure which is introduced by #56790.
https://github.com/HyukjinKwon/spark/actions/runs/28169229008/job/83432207959
```
Had test failures in pyspark.sql.tests.connect.test_parity_python_streaming_datasource with python3.12; see logs.
Error:  running /__w/spark/spark/python/run-tests --modules=pyspark-streaming,pyspark-structured-streaming,pyspark-structured-streaming-connect --parallelism=1 --python-executables=python3.12 ; received return code 255
Error: Process completed with exit code 19.
```

### Why are the changes needed?
To recover CI.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
GA.

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #56829 from sarutak/fix-SQLAppStatusListenerSuit-style.

Authored-by: Kousuke Saruta <sarutak@apache.org>
Signed-off-by: Hyukjin Kwon <hyukjin.kwon@databricks.com>