[SPARK-53729][PYTHON][CONNECT] Fix serialization of `pyspark.sql.connect.window.WindowSpec`
### What changes were proposed in this pull request?
Fix serialization of `pyspark.sql.connect.window.WindowSpec`

### Why are the changes needed?
this query fails
```
from pyspark.sql import Window, WindowSpec
from pyspark.sql.functions import *

df = ( spark.readStream.format("rate-micro-batch")
        .option("rowsPerBatch", 1000)
        .option("numPartitions", 2)
        .load()
        .withColumn("some_string",lit("apples")) )

window_spec = Window.partitionBy("some_string").orderBy("value")

def get_calculate_row_number_in_batch(window_spec):
    def calculate_row_number_in_batch(df, batch_id):
        df.withColumn("row_number", row_number().over(window_spec)).show()
    return calculate_row_number_in_batch

(df.writeStream
 .queryName('streaming_query')
 .foreachBatch(get_calculate_row_number_in_batch(window_spec))
 .trigger(processingTime='30 seconds')
 .start()
 )
```

due to
```
TypeError: WindowSpec.__new__() missing 3 required positional arguments: 'partitionSpec', 'orderSpec', and 'frame'
```

### Does this PR introduce _any_ user-facing change?
bug-fix

### How was this patch tested?
added test, and also manually checked above-mentioned query

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #52464 from zhengruifeng/fix_win_spec.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>
(cherry picked from commit 984d578c162de2e8ebcfc5eee15f1f2822a9f723)
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>