[SPARK-39762][INFRA][PS] Support latest numpy in infra
### What changes were proposed in this pull request?
Remove infra numpy<1.23.0 version limit to support numpy 1.23+ (latest) in infra.

### Why are the changes needed?
After below two PRs merged:

https://github.com/apache/spark/pull/37117: Fix annotation: `python/pyspark/pandas/frame.py:9970: error: Need type annotation for "raveled_column_labels"  [var-annotated]`
https://github.com/apache/spark/pull/37078: Fix wrong aliases in __array_ufunc__: `NotImplementedError: pandas-on-Spark objects currently do not support <ufunc 'divide'>`

We can now remove limit on infra file to support numpy > 1.23.0.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
CI passed and [numpy 1.23.1](https://github.com/Yikun/spark/runs/7314545823?check_suite_focus=true#step:9:49) installed in CI

Closes #37175 from Yikun/patch-24.

Authored-by: Yikun Jiang <yikunkero@gmail.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>