[SPARK-46425][INFRA] Pin the bundler version in CI
Currently documentation build is broken:

https://github.com/apache/spark/actions/runs/7226413850/job/19691970695

```
...
ERROR:  Error installing bundler:
	The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.0.0.
```

This PR uses the suggestion.

To recover the CI.

No, dev-only.

CI in this PR verify it.

No.

Closes #44376 from HyukjinKwon/SPARK-46425.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
(cherry picked from commit d0da1172b7d87b68a8af8464c6486aa586324241)
Signed-off-by: Dongjoon Hyun <dhyun@apple.com>