[SPARK-45409][INFRA] Pin `torch<=2.0.1`
### What changes were proposed in this pull request?

This PR aims to pin `torch` to recover Python Linter failure.

### Why are the changes needed?

`torch 2.1.0` is released and breaks `mypy` in a weird way.

- https://github.com/apache/spark/actions/runs/6399720715/job/17372994437

```
starting mypy annotations test...
annotations failed mypy checks:
/usr/local/lib/python3.9/dist-packages/torch/_dynamo/variables/tensor.py:369: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 0.982
/usr/local/lib/python3.9/dist-packages/torch/_dynamo/variables/tensor.py:369: : note: please use --show-traceback to print a traceback when reporting a bug
2
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Recover `Python Linter` in CIs.

I also manually verified this.
```
$ pip3 freeze | grep torch
torch==2.0.1
torcheval==0.0.7
torchvision==0.15.2

$ dev/lint-python
...
all lint-python tests passed!
```

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #43207 from dongjoon-hyun/traitlets.

Authored-by: Dongjoon Hyun <dhyun@apple.com>
Signed-off-by: Dongjoon Hyun <dhyun@apple.com>