[SPARK-49387][PYTHON] Fix type hint for `accuracy` in `percentile_approx` and `approx_percentile`
### What changes were proposed in this pull request?
Fix type hint for `accuracy` in `percentile_approx` and `approx_percentile`

### Why are the changes needed?
float `accuracy` is not supported:
```
In [9]: df.select(approx_percentile("value", [0.25, 0.5, 0.75], 1.1).alias("quantiles")).show()

...

AnalysisException: [DATATYPE_MISMATCH.UNEXPECTED_INPUT_TYPE] Cannot resolve "approx_percentile(value, array(0.25, 0.5, 0.75), 1.1)" due to data type mismatch: The third parameter requires the "INTEGRAL" type, however "1.1" has the type "DOUBLE". SQLSTATE: 42K09;
```

### Does this PR introduce _any_ user-facing change?
yes, minor doc change

### How was this patch tested?
CI

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #47869 from zhengruifeng/py_approx_percentile_acc.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>