[SPARK-51920][SS][PYTHON] Fix type handling of namedTuple for transfromWithState
### What changes were proposed in this pull request?
Fix type handling of namedTuple for transfromWithState

### Why are the changes needed?
We hit the issue when using namedTuple as value of structType like

```
class Person(NamedTuple):
    age: Integer
    name: String

 def handleInputRows(
        self,
        key: Any,
        rows: Iterator[Row],
        timerValues: TimerValues
    ) -> Iterator[Row]:
        person: Person = Person(age = 1, name= "peter")
        person_list = []
        person_list.append(person)
        self.person_list.update((person_list,))
```

The `_serialize_to_bytes` cannot construct the namedTuple correctly and hit
```
File "/databricks/spark/python/pyspark/sql/streaming/stateful_processor_api_client.py", line 575, in normalize_value
    return type(v)(normalize_value(e) for e in v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Person.__new__() missing 2 required positional arguments: 'age' and 'name'
```
It's because NamedTuple cannot accept generator as parameter.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
UT

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #53314 from zeruibao/zeruibao/SPARK-5192-fix-namedtuple-type.

Lead-authored-by: zeruibao <zerui.bao@databricks.com>
Co-authored-by: Zerui Bao <125398515+zeruibao@users.noreply.github.com>
Signed-off-by: Jungtaek Lim <kabhwan.opensource@gmail.com>