[SPARK-50052][PYTHON] Make NumpyArrayConverter support empty str ndarray
### What changes were proposed in this pull request?
Make `NumpyArrayConverter` support empty str ndarray

### Why are the changes needed?
existing implementation needs the str ndarray to be non-empty, so fails:
```
In [6]: spark.range(1).select(sf.lit(np.array(["a", "b"], np.str_)))
Out[6]: DataFrame[ARRAY('a', 'b'): array<string>]

In [7]: spark.range(1).select(sf.lit(np.array([], np.int32)))
Out[7]: DataFrame[ARRAY(): array<int>]

In [8]: spark.range(1).select(sf.lit(np.array([], np.str_)))
...

PySparkTypeError: [UNSUPPORTED_NUMPY_ARRAY_SCALAR] The type of array scalar '<U1' is not supported.

```

### Does this PR introduce _any_ user-facing change?
support empty string array

```
In [3]: spark.range(1).select(sf.lit(np.array([], np.str_)))
Out[3]: DataFrame[ARRAY(): array<string>]
```

### How was this patch tested?
added test

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #48575 from zhengruifeng/classic_np_array_conv.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>