Spark history log show IOException Error while a application is still running
After adding SPARK-6197 as a patch to spark-1.3.1, I found it no longer
prints out an Error Exception in history log after a application is
failed. But while a application is running, it may still print out a
IOException Error, like this "ERROR FsHistoryProvider: Failed to load
application log data from
FileStatus{path=hdfs://yarncluster/history/sparkhistory/application_1426843812583_0085.snappy.inprogress;
isDirectory=false; length=270; replication=2; blocksize=134217728;
modification_time=1432797327877; access_time=1432797327877;
owner=hadoop; group=supergroup; permission=rwxrwx---; isSymlink=false}.
java.io.IOException: failed to read chunk"