[SPARK-52862][PYTHON][CONNECT] Fix the nullability check of `Decimal('NaN')`
### What changes were proposed in this pull request?
Fix the nullability check of Decimal('NaN')

### Why are the changes needed?
It is a long-standing issue that the nullability check of Decimal('NaN') is not correct:

```py
from decimal import Decimal
from pyspark.sql.types import *

data = [Row(dec=Decimal("NaN"))]
schema = StructType([StructField("dec", DecimalType(), False)])
df = spark.createDataFrame(data=data, schema=schema)

In [4]: df.collect()
Out[4]: [Row(dec=None)]

In [5]: df.show()
...
Py4JJavaError: An error occurred while calling o67.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 6 in stage 2.0 failed 1 times, most recent failure: Lost task 6.0 in stage 2.0 (TID 11) (localhost executor driver): java.lang.NullPointerException: Cannot invoke "org.apache.spark.sql.types.Decimal.toPlainString()" because "<local2>" is null
...
```

it should fail on creation, because `Decimal("NaN")` will be treated as `Null` value

### Does this PR introduce _any_ user-facing change?
The creation should fail

### How was this patch tested?
new tests

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #51548 from zhengruifeng/fix_dec_nan_null.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>