[SPARK-43968][PYTHON] Improve error messages for Python UDTFs with wrong number of outputs
This PR improves the error messages for Python UDTFs when the number of outputs mismatches the number of outputs specified in the return type of the UDTFs.

To make Python UDTFs more user-friendly.

Yes. This PR improves the error messages.
Before this change, the error thrown by Spark will be a java IllegalStateException:
```
java.lang.IllegalStateException: Input row doesn't have expected number of values required by the schema
```
After this PR, it will throw a clearer error message with an error class:
```
[UDTF_RETURN_SCHEMA_MISMATCH] The number of columns in the result does not match the specified schema
```

Existing tests and new unit tests.

Closes #42157 from allisonwang-db/spark-43968-py-udtf-checks.

Authored-by: allisonwang-db <allison.wang@databricks.com>
Signed-off-by: Takuya UESHIN <ueshin@databricks.com>
(cherry picked from commit 7194ce9263fe1683c039a1aaf9462657b1672a99)
Signed-off-by: allisonwang-db <allison.wang@databricks.com>