[SPARK-36213][SQL][FOLLOWUP][3.0] Fix compilation error due to type mismatch
### What changes were proposed in this pull request?

This patch fixes a compilation error of backported PR of SPARK-36213.

### Why are the changes needed?

To fix compilation error:

```
[error] /spark/sql/core/src/main/scala/org/apache/spark/sql/execution/command/tables.scala:695: type mismatch;
[error]  found   : org.apache.spark.sql.types.StructType
[error]  required: Seq[String]
[error] Error occurred in an application involving default arguments.
[error]       metadata.partitionSchema,
[error]                ^
```

`PartitioningUtils.normalizePartitionSpec`'s `partColNames` is `Seq[String]` in 3.0.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit test

Closes #33504 from viirya/SPARK-36213-followup.

Authored-by: Liang-Chi Hsieh <viirya@gmail.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>