[SPARK-43886][PYTHON] Accept generics tuple as typing hints of Pandas UDF
### What changes were proposed in this pull request?
Accept generics tuple as typing hints in Pandas UDF.

### Why are the changes needed?
Adapt to [PEP 585](https://peps.python.org/pep-0585/) with Python 3.9.

### Does this PR introduce _any_ user-facing change?
Yes. `tuple` is accepted as typing hints of Pandas UDF.

FROM
```py
>>> pandas_udf("long")
... def multiply(iterator: Iterator[tuple[pd.Series, pd.DataFrame]]) -> Iterator[pd.Series]:
...   for s1, df in iterator:
...     yield s1 * df.v
...
Traceback (most recent call last):
...
    raise PySparkNotImplementedError(
pyspark.errors.exceptions.base.PySparkNotImplementedError: [UNSUPPORTED_SIGNATURE] Unsupported signature: (iterator: Iterator[tuple[pandas.core.series.Series, pandas.core.frame.DataFrame]]) -> Iterator[pandas.core.series.Series].
```

TO
```py
>>> pandas_udf("long")
... def multiply(iterator: Iterator[tuple[pd.Series, pd.DataFrame]]) -> Iterator[pd.Series]:
...   for s1, df in iterator:
...     yield s1 * df.v
...
>>> multiply._unwrapped.evalType
204  # SQL_SCALAR_PANDAS_ITER_UDF
```

### How was this patch tested?
Unit tests.

Closes #41388 from xinrong-meng/tuple.

Authored-by: Xinrong Meng <xinrong@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>