Revert "[SPARK-40165][BUILD] Update test plugins to latest versions"
### What changes were proposed in this pull request?
This reverts commit 3ed382f391911ec4a79fb204f4986728017dfa4a. https://github.com/apache/spark/pull/37598

### Why are the changes needed?
This patch cause the error like:
```
[error] /home/runner/work/spark/spark/sql/hive-thriftserver/src/main/java/org/apache/hive/service/auth/HttpAuthUtils.java:36:1:  error: package org.apache.http.protocol does not exist
[error] import org.apache.http.protocol.BasicHttpContext;
[error]                                ^
[error] /home/runner/work/spark/spark/sql/hive-thriftserver/src/main/java/org/apache/hive/service/auth/HttpAuthUtils.java:156:1:  error: cannot find symbol
[error]     private final HttpContext httpContext;
[error]                   ^  symbol:   class HttpContext
[error]   location: class HttpKerberosClientAction
[error] 3 errors
```

The old cache + new pom passed. Then, cache is outdate, the real error happened.

According investigation, I found that this https://github.com/apache/spark/commit/3ed382f391911ec4a79fb204f4986728017dfa4a should be the real first bad commit.

I just found this job are using cache:
https://github.com/panbingkun/spark/runs/7938361118?check_suite_focus=true

With old cache + new: passed. (that's the reason that the original PR passed)

Without any cache + new pom: failed. (that's reason that CI break)

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
CI passed, especially, 2.13 passed

Closes #37618 from Yikun/xxxx1.

Authored-by: Yikun Jiang <yikunkero@gmail.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>