[SPARK-39574][PS] Better error message when `ps.Index` is used for DataFrame/Series creation
### What changes were proposed in this pull request?
Better error message when `ps.Index` is used for DataFrame/Series creation.

### Why are the changes needed?
As part of [SPARK-39581](https://issues.apache.org/jira/browse/SPARK-39581).

The current error message is confusing and is from the pandas library. We should improve that.

### Does this PR introduce _any_ user-facing change?
Yes.
**From:**
```py
>>> ps.DataFrame([1, 2], index=ps.Index([1, 2]))
Traceback (most recent call last):
...
ValueError: The truth value of a Int64Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

>>> ps.Series([1, 2], index=ps.Index([1, 2]))
Traceback (most recent call last):
...
ValueError: The truth value of a Int64Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**To:**
```py
>>> ps.DataFrame([1, 2], index=ps.Index([1, 2]))
Traceback (most recent call last):
...
TypeError: The given index cannot be a pandas-on-Spark index. Try pandas index or array-like.

>>> ps.Series([1, 2], index=ps.Index([1, 2]))
Traceback (most recent call last):
...
TypeError: The given index cannot be a pandas-on-Spark index. Try pandas index or array-like.
```

### How was this patch tested?
Unit tests.

Closes #36981 from xinrong-databricks/err_pd.

Authored-by: Xinrong Meng <xinrong.meng@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>