[SPARK-44388][CONNECT] Fix protobuf cast issue when UDF instance is updated
### What changes were proposed in this pull request?

This PR modifies the arguments of the `ScalarUserDefinedFunction` case class to take in `serializedUdfPacket`, `inputTypes` and `outputType` instead of calculating these types internally from `function`, `inputEncoders` and `outputEncoder`. This allows the class to copy over the serialized udf value from the parent instance instead of re-creating it. Through this, we avoid hitting a variant of the issue mentioned in [SPARK-43198](https://issues.apache.org/jira/browse/SPARK-43198) which seems to cause protobuf cast for instances that are made through a copy operation.

### Why are the changes needed?

Bugfix. Consider the following code:
```
class A(x: Int) { def get = x * 7 }
val myUdf = udf((x: Int) => new A(x).get)
val modifiedUdf = myUdf.withName("myUdf").asNondeterministic()
spark.range(5).select(modifiedUdf(col("id"))).as[Int].collect()
```

Executing this code currently results in hitting the following error:
```
java.lang.ClassCastException: org.apache.spark.connect.proto.ScalarScalaUDF cannot be cast to com.google.protobuf.MessageLite
    at com.google.protobuf.GeneratedMessageLite$SerializedForm.readResolve(GeneratedMessageLite.java:1462)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1274)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
...
```
If we do not include the `myUdf.withName("myUdf").asNondeterministic()`, the UDF runs as expected.

### Does this PR introduce _any_ user-facing change?

Yes, fixes the bug mentioned above.

### How was this patch tested?

Added a new E2E test in `ReplE2ESuite`.

Closes #41959 from vicennial/SPARK-44388.

Lead-authored-by: vicennial <venkata.gudesa@databricks.com>
Co-authored-by: Venkata Sai Akhil Gudesa <venkata.gudesa@databricks.com>
Co-authored-by: Venkata Sai Akhil Gudesa <gvs.akhil1997@gmail.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>