[SPARK-41971][CONNECT][PYTHON][FOLLOWUP] Fix to_pandas to support the older Spark
### What changes were proposed in this pull request?

This is a follow-up of #40988.

Fix `to_pandas` to support the older Spark.

For the server:

```py
% ./sbin/start-connect-server.sh --packages org.apache.spark:spark-connect_2.12:3.4.0
```

with the client with the change here:

```py
>>> spark.sql("values (1, struct('x' as x)) as t(a, b)").toPandas()
   a           b
0  1  {'x': 'x'}
```

### Why are the changes needed?

The config `spark.sql.execution.pandas.structHandlingMode` introduced in #40988 does not exist in the older Spark, `<3.5`

```py
>>> spark.sql("values (1, struct('x' as x)) as t(a, b)").toPandas()
Traceback (most recent call last):
...
pyspark.errors.exceptions.connect.SparkConnectGrpcException: (java.util.NoSuchElementException) spark.sql.execution.pandas.structHandlingMode
```

### Does this PR introduce _any_ user-facing change?

The newer Spark Connect client will work with `Spark<3.5`.

### How was this patch tested?

Manually.

Closes #41390 from ueshin/issues/SPARK-41971/config_with_default.

Authored-by: Takuya UESHIN <ueshin@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>