[SPARK-37390][PYTHON][DOCS] Add default value to getattr(app, add_javascript)
### What changes were proposed in this pull request?

This PR adds `default` (`None`) value to `getattr(app, add_javascript)`.

### Why are the changes needed?

Current logic fails on `getattr(app, "add_javascript")` when executed with Sphinx 4.x. The problem can be illustrated with a simple snippet.

```python
>>> class Sphinx:
...     def add_js_file(self, filename: str, priority: int = 500, **kwargs: Any) -> None: ...
...
>>> app = Sphinx()
>>> getattr(app, "add_js_file", getattr(app, "add_javascript"))
Traceback (most recent call last):
  File "<ipython-input-11-442ab6dfc933>", line 1, in <module>
    getattr(app, "add_js_file", getattr(app, "add_javascript"))
AttributeError: 'Sphinx' object has no attribute 'add_javascript'
```
After this PR is merged we'll fallback to `getattr(app, "add_js_file")`:

```python
>>> getattr(app, "add_js_file", getattr(app, "add_javascript", None))
<bound method Sphinx.add_js_file of <__main__.Sphinx object at 0x7f444456abe0>>
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual docs build.

Closes #34669 from zero323/SPARK-37390.

Authored-by: zero323 <mszymkiewicz@gmail.com>
Signed-off-by: zero323 <mszymkiewicz@gmail.com>
(cherry picked from commit b9e9167f589db372f0416425cdf35b48a6216b50)
Signed-off-by: zero323 <mszymkiewicz@gmail.com>