[SPARK-44878][SS] Disable strict limit for RocksDB write manager to avoid insertion exception on cache full
### What changes were proposed in this pull request?
Disable strict limit for RocksDB write manager to avoid insertion exception on cache full

### Why are the changes needed?
In some cases, if the memory limit is reached, on insert/get, we are seeing the following exception

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 42 in stage 9.0 failed 4 times, most recent failure: Lost task 42.3 in stage 9.0 (TID 2950) (96.104.176.55 executor 0): org.rocksdb.RocksDBException: Insert failed due to LRU cache being full.
	at org.rocksdb.RocksDB.get(Native Method)
	at org.rocksdb.RocksDB.get(RocksDB.java:2053)
	at org.apache.spark.sql.execution.streaming.state.RocksDB.get(RocksDB.scala:299)
	at org.apache.spark.sql.execution.streaming.state.RocksDBStateStoreProvider$RocksDBStateStore.get(RocksDBStateStoreProvider.scala:55)
```

It seems this is being thrown with strict memory limit within RocksDB here - https://github.com/facebook/rocksdb/blob/0fa0c97d3e9ac5dfc2e7ae94834b0850cdef5df7/cache/lru_cache.cc#L394

It seems this issue can only happen with the strict mode as described here - https://github.com/facebook/rocksdb/issues/5048#issuecomment-470788792

Seems like there is a pending issue for RocksDB around this as well - https://github.com/facebook/rocksdb/issues/8670

There is probably a relevant fix, but not sure whether this addresses the issue completely - https://github.com/facebook/rocksdb/pull/6619
(cc - siying )

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing tests

Closes #42567 from anishshri-db/task/SPARK-44878.

Authored-by: Anish Shrigondekar <anish.shrigondekar@databricks.com>
Signed-off-by: Jungtaek Lim <kabhwan.opensource@gmail.com>