[SPARK-51023][CORE] log remote address on RPC exception
### What changes were proposed in this pull request?
Add the remote address to the RPC exception log lines. It's already logged for `TransportRequestHandler.processStreamRequest()`, but not for other types of requests.

### Why are the changes needed?
To simplify troubleshooting. We hit this in our production deployments for two cases:
* when the executor and driver are running different Spark versions
* when vulnerability scanner (internal security tool) sends malformed messages

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
By verifying the logs of `RpcIntegrationSuite` -
```
25/01/28 15:06:07.439 shuffle-server-3-15 ERROR TransportRequestHandler: Error while invoking RpcHandler#receive() on RPC id 5952848813688034638 from /127.0.0.1:61697
java.lang.RuntimeException: Thrown: the
	at org.apache.spark.network.RpcIntegrationSuite$1.receive(RpcIntegrationSuite.java:73)
	at org.apache.spark.network.server.TransportRequestHandler.processRpcRequest(TransportRequestHandler.java:167)
	at org.apache.spark.network.server.TransportRequestHandler.handle(TransportRequestHandler.java:111)
```

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #49718 from fe2s/SPARK-51023-log_remote_address_on_RPC_exception.

Authored-by: oleksii.diagiliev <oleksii.diagiliev@workday.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>