[SPARK-52420][PYTHON][TESTS] Make test_udtf_with_invalid_return_type compatible with Python only client
This PR is a followup of https://github.com/apache/spark/pull/50997 that backports the test changes into branch-3.5.

To make the build pass (https://github.com/apache/spark/actions/runs/15522509263/job/43697654408).

```
======================================================================
FAIL [0.015s]: test_udtf_with_invalid_return_type (pyspark.sql.tests.connect.test_parity_udtf.UDTFParityTests.test_udtf_with_invalid_return_type)
----------------------------------------------------------------------
pyspark.errors.exceptions.connect.SparkConnectGrpcException: (org.apache.spark.sql.connect.common.InvalidPlanInput) [INVALID_SCHEMA_TYPE_NON_STRUCT] Invalid schema type. Expect a struct type, but got "INT". SQLSTATE: 42K09

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/spark/spark-3.5/python/pyspark/sql/tests/connect/test_parity_udtf.py", line 57, in test_udtf_with_invalid_return_type
    with self.assertRaisesRegex(
AssertionError: "Invalid Python user-defined table function return type." does not match "(org.apache.spark.sql.connect.common.InvalidPlanInput) [INVALID_SCHEMA_TYPE_NON_STRUCT] Invalid schema type. Expect a struct type, but got "INT". SQLSTATE: 42K09"

----------------------------------------------------------------------
```

Now that the error message has changed, the tests in branch-3.5 fails.

No, test-only.

Manually.

No.

Closes #51121 from HyukjinKwon/SPARK-52420.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
(cherry picked from commit c75e7c78b2d15b741698ce2c2f98e3c7e877ab91)
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>