[SPARK-44625][CONNECT] SparkConnectExecutionManager to track all executions
### What changes were proposed in this pull request?

SparkConnectExecutionManager tracks all executions (ExecuteHolder) in all sessions of Spark Connect. It tracks which executions have RPCs (ExecuteGrpcReponseSender) attached to them. If an execution gets abandoned (it's not cleared with ReleaseExecute by the client, but no new RPC arrives), it will be automatically interrupted and removed after a timeout.

Note for the failure:
```
Error: Field "2" on message "ReleaseExecuteResponse" moved from outside to inside a oneof.
Error: buf found 1 breaking changes.
```
The message ReleaseExecuteResponse has not been released yet, so it's not a breaking change compared to any released version.

### Why are the changes needed?

Need the SparkConnectExecutionManager to track reattachable executions that got abandoned by client.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Pending, but the SparkConnectExecutionManager allows tests to inspect execution state, so allows writing more unit tests about reattachable execution.

Closes #42423 from juliuszsompolski/SPARK-44625.

Authored-by: Juliusz Sompolski <julek@databricks.com>
Signed-off-by: Herman van Hovell <herman@databricks.com>