[SPARK-40128][SQL] Make the VectorizedColumnReader recognize DELTA_LENGTH_BYTE_ARRAY as a standalone column encoding
### What changes were proposed in this pull request?
Add DELTA_LENGTH_BYTE_ARRAY as a recognized encoding in VectorizedColumnReader so that
vectorized reads succeed when there are columns using DELTA_LENGTH_BYTE_ARRAY as a standalone
encoding.

### Why are the changes needed?

Spark currently throws an exception for DELTA_LENGTH_BYTE_ARRAY columns when vectorized
reads are enabled and trying to read `delta_length_byte_array.parquet` from https://github.com/apache/parquet-testing:

    java.lang.UnsupportedOperationException: Unsupported encoding: DELTA_LENGTH_BYTE_ARRAY

### Does this PR introduce _any_ user-facing change?
Yes - previously throw UNSUPPORTED exception. Now reads the encoding same as if vectorized reads are disabled.

### How was this patch tested?
Added test case to ParquetIOSuite; made sure it fails without the fix to VectorizedColumnReader and passes after.

Closes #37557 from sfc-gh-dhuo/support-parquet-delta-length-byte-array.

Authored-by: Dennis Huo <dennis.huo@snowflake.com>
Signed-off-by: Chao Sun <sunchao@apple.com>