[SPARK-37374][PYTHON] Fix StatCounter to use mergeStats when merging with self
### What changes were proposed in this pull request?

Fixes `StatCounter` to use `mergeStats` instead of `merge` when merging with `self`.

### Why are the changes needed?

`StatCounter` should use `mergeStats` instead of `merge` when merging with `self`.

```py
>>> from pyspark.statcounter import StatCounter
>>> stats = StatCounter([1.0, 2.0, 3.0, 4.0])
>>> stats.mergeStats(stats)
Traceback (most recent call last):

...

TypeError: unsupported operand type(s) for -: 'StatCounter' and 'float'
```

This is a long standing bug but usually this bug won't be hit unless users explicitly use `mergeStats` with `self`.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Added some tests.

Closes #34653 from ueshin/issues/SPARK-37374/statcounter.

Authored-by: Takuya UESHIN <ueshin@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>