[SPARK-38813][3.3][SQL][FOLLOWUP] Improve the analysis check for TimestampNTZ output
### What changes were proposed in this pull request?

In https://github.com/apache/spark/pull/36094, a check for failing TimestampNTZ output is added.
However, if there is an unresolved attribute in the plan, even if it is note related to TimestampNTZ, the error message becomes confusing
```
scala> val df = spark.range(2)
df: org.apache.spark.sql.Dataset[Long] = [id: bigint]

scala> df.select("i")
org.apache.spark.sql.AnalysisException: Invalid call to dataType on unresolved object;
'Project ['i]
+- Range (0, 2, step=1, splits=Some(16))

  at org.apache.spark.sql.catalyst.analysis.UnresolvedAttribute.dataType(unresolved.scala:137)
  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$4(CheckAnalysis.scala:164)
...
```

Before changes it was
```
org.apache.spark.sql.AnalysisException: Column 'i' does not exist. Did you mean one of the following? [id];
```

This PR is the improve the check for TimestampNTZ and restore the error message for unresolved attributes.
### Why are the changes needed?

Fix a regression in analysis error message.

### Does this PR introduce _any_ user-facing change?

No, it is not released yet.

### How was this patch tested?

Manual test

Closes #36316 from gengliangwang/bugFix.

Authored-by: Gengliang Wang <gengliang@apache.org>
Signed-off-by: Gengliang Wang <gengliang@apache.org>