[SPARK-53253][PYTHON] Fix register UDF of type `SQL_SCALAR_ARROW_ITER_UDF`
### What changes were proposed in this pull request?
Fix register UDF of type `SQL_SCALAR_ARROW_ITER_UDF`

### Why are the changes needed?
to fix bug that:
```
In [12]:         arrow_udf(LongType())
    ...:         def add_one(it: Iterator[pa.Array]) -> Iterator[pa.Array]:
    ...:             for s in it:
    ...:                 yield pa.compute.add(s, 1)
    ...:

...

In [15]: spark.udf.register("xxx", add_one)
---------------------------------------------------------------------------
PySparkTypeError                          Traceback (most recent call last)
Cell In[15], line 1
----> 1 spark.udf.register("xxx", add_one)

File ~/spark/python/pyspark/sql/udf.py:659, in UDFRegistration.register(self, name, f, returnType)
    649 f = cast("UserDefinedFunctionLike", f)
    650 if f.evalType not in [
    651     PythonEvalType.SQL_BATCHED_UDF,
    652     PythonEvalType.SQL_ARROW_BATCHED_UDF,
   (...)    657     PythonEvalType.SQL_GROUPED_AGG_ARROW_UDF,
    658 ]:
--> 659     raise PySparkTypeError(
    660         errorClass="INVALID_UDF_EVAL_TYPE",
    661         messageParameters={
    662             "eval_type": "SQL_BATCHED_UDF, SQL_ARROW_BATCHED_UDF, "
    663             "SQL_SCALAR_PANDAS_UDF, SQL_SCALAR_PANDAS_ITER_UDF, "
    664             "SQL_GROUPED_AGG_PANDAS_UDF or SQL_GROUPED_AGG_ARROW_UDF"
    665         },
    666     )
    667 source_udf = _create_udf(
    668     f.func,
    669     returnType=f.returnType,
   (...)    672     deterministic=f.deterministic,
    673 )
    674 register_udf = source_udf._unwrapped  # type: ignore[attr-defined]

PySparkTypeError: [INVALID_UDF_EVAL_TYPE] ...
```

### Does this PR introduce _any_ user-facing change?
no, this is a new feature in 4.1

### How was this patch tested?
added tests

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #51984 from zhengruifeng/fix_register_scalar_iter.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>