[SPARK-51680][SQL] Set the logical type for TIME in the parquet writer
### What changes were proposed in this pull request?
In the PR, I propose to modify the parquet schema converter for the TIME data type, and convert Catalyst's `TimeType(n)` to parquet physical type `INT64` annotated by the logical type:
```
TimeType(isAdjustedToUTC = false, unit = MICROS)
```
in the parquet writer.

### Why are the changes needed?
To fix a failure of non-vectorized reader. The code below portraits the issue:
```scala
scala> spark.conf.set("spark.sql.parquet.enableVectorizedReader", false)
scala> spark.read.parquet("/Users/maxim.gekk/tmp/time_parquet3").show()

org.apache.spark.SparkRuntimeException: [PARQUET_CONVERSION_FAILURE.UNSUPPORTED] Unable to create a Parquet converter for the data type "TIME(6)" whose Parquet type is optional int64 col. Please modify the conversion making sure it is supported. SQLSTATE: 42846
  at org.apache.spark.sql.errors.QueryExecutionErrors$.cannotCreateParquetConverterForDataTypeError(QueryExecutionErrors.scala:2000)
```

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
By running the modified test:
```
$ build/sbt "test:testOnly *ParquetFileFormatV1Suite"
$ build/sbt "test:testOnly *ParquetFileFormatV2Suite"
```

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #50476 from MaxGekk/parquet-time-nested.

Authored-by: Max Gekk <max.gekk@gmail.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>