[SPARK-38279][TESTS][3.2] Pin MarkupSafe to 2.0.1 fix linter failure
This PR proposes to pin the Python package `markupsafe` to 2.0.1 to fix the CI failure as below.

```
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/runner/work/_temp/setup-sam-43osIE/.venv/lib/python3.10/site-packages/markupsafe/__init__.py)
```

Since `markupsafe==2.1.0` has removed `soft_unicode`, `from markupsafe import soft_unicode` no longer working properly.

See https://github.com/aws/aws-sam-cli/issues/3661 for more detail.

To fix the CI failure on branch-3.2

No.

The existing tests are should be passed

Closes #35602 from itholic/SPARK-38279.

Authored-by: itholic <haejoon.lee@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
(cherry picked from commit 79099cf7baf6e094884b5f77e82a4915272f15c5)
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>