[SPARK-54326][INFRA] Recover MacOS CIs by installing `zstandard==0.25.0`
### What changes were proposed in this pull request?

This PR aims to recover MacOS CIs by installing `zstandard==0.25.0`.

### Why are the changes needed?

After SPARK-54194, `zstandard` Python package is required for `Connect`.
- https://github.com/apache/spark/pull/52894

Currently, MacOS CIs are broken.
- https://github.com/apache/spark/actions/workflows/build_python_3.11_macos26.yml
- https://github.com/apache/spark/actions/workflows/build_python_3.11_macos.yml

```
Traceback (most recent call last):
  File "/Users/runner/work/spark/spark/python/pyspark/sql/connect/utils.py", line 105, in require_minimum_zstandard_version
    import zstandard  # noqa
    ^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'zstandard'
```

### Does this PR introduce _any_ user-facing change?

No behavior change.

### How was this patch tested?

Pass the CIs and manual review because MacOS CIs are triggered daily CIs only.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #53025 from dongjoon-hyun/SPARK-54326.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>