[SPARK-54323][PYTHON] Change the way to access logs to TVF instead of system view
### What changes were proposed in this pull request?

Changes the way to access logs to TVF instead of system view.

```sql
SELECT * FROM python_worker_logs()
```

```py
spark.tvf.python_worker_logs()
```

Also blocks the TVF when the python worker logging is disabled.

```py
>>> spark.conf.get('spark.sql.pyspark.worker.logging.enabled')
'false'
>>> spark.tvf.python_worker_logs().show()
Traceback (most recent call last):
...
pyspark.errors.exceptions.captured.AnalysisException: [FEATURE_NOT_ENABLED] The feature Python Worker Logging is not enabled. Consider setting the config spark.sql.pyspark.worker.logging.enabled to true to enable this capability. SQLSTATE: 56038

>>> spark.conf.set('spark.sql.pyspark.worker.logging.enabled', True)
>>> spark.tvf.python_worker_logs().show()
+---+-----+---+-------+---------+------+
| ts|level|msg|context|exception|logger|
+---+-----+---+-------+---------+------+
+---+-----+---+-------+---------+------+
```

### Why are the changes needed?

There may be namespace conflicts with the other system tables/views, etc..

For example, the variables in SQL has the same namespace `system.session.varname`, which may potentially cause an issue.

### Does this PR introduce _any_ user-facing change?

Yes, the way to access python worker logs will be changed.

### How was this patch tested?

Modified the related tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #53021 from ueshin/issues/SPARK-54323/tvf.

Authored-by: Takuya Ueshin <ueshin@databricks.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
(cherry picked from commit fb8dbd7071b13549d672cc204cec7ab12e7dc520)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>