[SPARK-51634][SQL] Support TIME in off-heap column vectors
### What changes were proposed in this pull request?
In the PR, I propose to modify `OffHeapColumnVector.java` to support the new data type `TIME`, and move a test from `ParquetIOSuite` to `ParquetFileFormatSuite` to test read/write `TIME` value in parquet for both V1 and V2 versions.

### Why are the changes needed?
To fix the failure:
```scala
scala> spark.conf.set("spark.sql.columnVector.offheap.enabled", true)
scala> spark.read.parquet("/Users/maxim.gekk/tmp/test5").show()
org.apache.spark.SparkException: [FAILED_READ_FILE.NO_HINT] Encountered error while reading file file:///Users/maxim.gekk/tmp/test5/part-00000-855fbee0-1e15-460e-99ea-edf614e2415b-c000.snappy.parquet.  SQLSTATE: KD001
```

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
By running the modified test suite:
```
$ build/sbt "test:testOnly *ParquetFileFormatV1Suite"
$ build/sbt "test:testOnly *ParquetFileFormatV2Suite"
```

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #50428 from MaxGekk/time-parquet-tests.

Authored-by: Max Gekk <max.gekk@gmail.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>