[SPARK-54467][INFRA] Disable `actions/cache` on MacOS CIs
### What changes were proposed in this pull request?

This PR aims to disable `actions/cache` on MacOS CIs and remove `timeout-minutes` temporarily.

- SPARK-54466 (Re-enable `actions/cache` on MacOS) is filed to recover this back after GitHub Action outage is resolved.

### Why are the changes needed?

Currently, GitHub Action has an outage on `actions/cache` step due to `hashFiles` fails .

- https://github.com/orgs/community/discussions/180160
- https://github.com/actions/runner-images/issues/13341

Apache Spark MacOS CIs are affected like the following currently.

- https://github.com/apache/spark/actions/workflows/build_maven_java21_macos26.yml
- https://github.com/apache/spark/actions/workflows/build_python_3.11_macos.yml
- https://github.com/apache/spark/actions/workflows/build_python_3.11_macos26.yml

    > Error: The template is not valid. apache/spark/.github/workflows/python_hosted_runner_test.yml01fa49b9755f324d9d30cf1e61b07188a59342c7 (Line: 126, Col: 16): hashFiles('**/pom.xml, project/build.properties, build/mvn, build/sbt, build/sbt-launch-lib.bash, build/spark-build-info') failed. Fail to hash files under directory '/Users/runner/work/spark/spark'

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manual review.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #53180 from dongjoon-hyun/SPARK-54467.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>