[MINOR][INFRA] Upgrade actions in test_report.yml workflow
### What changes were proposed in this pull request?
Upgrade `dawidd6/action-download-artifact` from v1 to v6
Upgrade `scacap/action-surefire-report` from v1.0.13 to v1.8.0

### Why are the changes needed?
Current versions have the following problems:

`dawidd6/action-download-artifact` failing:
```
 ==> Downloading: apache~spark~ADIBKZ.dockerbuild.zip (44.7 kB)
Error: ﻿<?xml version="1.0" encoding="utf-8"?>
<Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:2c8b19f5-601e-007f-54e7-ffac7a000000
Time:2024-09-05T23:01:54.1979479Z</Message></Error>
```
https://github.com/apache/spark/actions/runs/10729437729/job/29756039009#step:2:15-17

`scacap/action-surefire-report` warning:
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
https://github.com/apache/spark/actions/runs/10723482700/job/29736875911#step:3:14

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
In GitHub CI:
The download succeeds (authentication issue above resolved), not hit by another bug: https://github.com/docker/build-push-action/issues/1167
```
==> Downloading: G-Research~spark~R7TXVG.dockerbuild.zip (23.76 kB)
Error: Invalid or unsupported zip format. No END header found
```
https://github.com/G-Research/spark/actions/runs/10733657395/job/29767392437#step:2:27

To be fixed in #48012.

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #48011 from EnricoMi/master.

Authored-by: Enrico Minack <github@enrico.minack.dev>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>