[SPARK-46317][INFRA][FOLLOWUP] Install `lxml` in PyPy3.8
### What changes were proposed in this pull request?

This PR aims to install `lxml` in PyPy3.8.

### Why are the changes needed?

#44247 seems to break the `PyPy3.8` daily CI.
- https://github.com/apache/spark/actions/runs/7239278196/job/19721018105
```
Traceback (most recent call last):
  File "/usr/local/pypy/pypy3.8/lib/pypy3.8/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/pypy/pypy3.8/lib/pypy3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/__w/spark/spark/python/pyspark/sql/tests/test_session.py", line 22, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #44391 from dongjoon-hyun/SPARK-46317.

Authored-by: Dongjoon Hyun <dhyun@apple.com>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>