[MINOR][PYTHON][DOCS] Fix the type hint for `extract`, `date_part` and `datepart`
### What changes were proposed in this pull request?
Fix the type hint for `extract`, `date_part` and `datepart`

### Why are the changes needed?
argument `field` never supports column name:

```python
In [6]: df = spark.createDataFrame([(datetime.datetime(2015, 4, 8, 13, 8, 15), "YEAR",)], ['ts', 'field'])

In [7]: df.select(sf.extract("field", "ts"))

...

AnalysisException: [NON_FOLDABLE_ARGUMENT] The function `extract` requires the parameter `field` to be a foldable expression of the type "STRING", but the actual argument is a non-foldable. SQLSTATE: 42K08
```

### Does this PR introduce _any_ user-facing change?
yes, doc only change

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #48613 from zhengruifeng/fix_extract_hint.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>