Catch all exceptions caused by BindExceptions
Looks like the actual exception thrown sometimes is
org.jboss.netty.channel.ChannelException: Failed to bind to:
localhost/127.0.0.1:60550, which is not a java.net.BindException.
We should catch these too.