[SPARK-49041][PYTHON][CONNECT] Raise proper error for `dropDuplicates` when wrong `subset` is given
### What changes were proposed in this pull request?

This PR proposes to raise proper error for `dropDuplicates` when wrong `subset` is given

### Why are the changes needed?

Current error message is hard to understand since it raises unrelated `INTERNAL_ERROR`:

**Classic**:
```python
>>> df.dropDuplicates(None)
[INTERNAL_ERROR] Undefined error message parameter for error class: '_LEGACY_ERROR_TEMP_1201', MessageTemplate: Cannot resolve column name "<colName>" among (<fieldNames>)., Parameters: Map(colName -> null, fieldNames -> name, age) SQLSTATE: XX000
```

**Connect**:
```python
>>> df.dropDuplicates(None)
TypeError: bad argument type for built-in operation
```

### Does this PR introduce _any_ user-facing change?

No API changes, but the user-facing error message is improved both in classic & connect:

```python
>>> df.dropDuplicates(None)
[NOT_STR] Argument `subset` should be a str, got NoneType.
```

### How was this patch tested?

Added UTs.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #47518 from itholic/SPARK-49041.

Authored-by: Haejoon Lee <haejoon.lee@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>