[SPARK-43487][SQL] Fix Nested CTE error message
### What changes were proposed in this pull request?
The batch of errors migrated to error classes as part of spark-40540 contains an error that got mixed up with the wrong error message:

[ambiguousRelationAliasNameInNestedCTEError](https://github.com/apache/spark/commit/43a6b932759865c45ccf36f3e9cf6898c1b762da#diff-744ac13f6fe074fddeab09b407404bffa2386f54abc83c501e6e1fe618f6db56R1983) uses the same error message as the following commandUnsupportedInV2TableError:

WITH t AS (SELECT 1), t2 AS ( WITH t AS (SELECT 2) SELECT * FROM t) SELECT * FROM t2;
AnalysisException: t is not supported for v2 tables

The error should be:

AnalysisException: Name tis ambiguous in nested CTE.
Please set spark.sql.legacy.ctePrecedencePolicy to CORRECTED so that name defined in inner CTE takes precedence. If set it to LEGACY, outer CTE definitions will take precedence. See more details in SPARK-28228.

### Does this PR introduce _any_ user-facing change?
Fix user-facing error message for ambiguous name in nested CTEs.

### How was this patch tested?

Closes #41155 from johanl-db/SPARK-43487-fix-nested-cte-error-message.

Authored-by: Johan Lasperas <johan.lasperas@databricks.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>