BugFix: TypeError in monitor_pod (#14513)
If the log read is interrupted before any logs are produced then
`last_log_time` will not be set and the line
`delta = pendulum.now() - last_log_time` will fail with
```
TypeError: unsupported operand type(s) for -: 'DateTime' and 'NoneType'
```

This commit fix this issue by only updating `read_logs_since_sec` if
`last_log_time` has been set.