[SPARK-51432][SQL][PYTHON] Throw a proper exception when Arrow schemas are mismatched
### What changes were proposed in this pull request?

This PR proposes to raise a proper error instead of `assert` when the returned Arrow schema is mismatched with specified SQL return type. Users can see this error, and this is not an internal error mssage.

### Why are the changes needed?

```python
import pandas as pd
from pyspark.sql.functions import pandas_udf

pandas_udf("int")
def func(s: pd.Series) -> pd.Series:
    return pd.Series([1.0] * len(s))

spark.range(1).select(func("id")).show()
```

Now it throws

```
org.apache.spark.SparkException: [ARROW_TYPE_MISMATCH] Invalid schema from pandas_udf(): expected IntegerType, got IntegerType. SQLSTATE: 42K0G
	at org.apache.spark.sql.errors.QueryExecutionErrors$.arrowDataTypeMismatchError(QueryExecutionErrors.scala:857)
	at org.apache.spark.sql.execution.python.ArrowEvalPythonEvaluatorFactory.$anonfun$evaluate$2(ArrowEvalPythonExec.scala:131)
	at scala.collection.Iterator$$anon$10.nextCur(Iterator.scala:594)
```

### Does this PR introduce _any_ user-facing change?

Yes, it changes the user-facing error mesasge.

### How was this patch tested?

Manually tested as described above.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #50201 from HyukjinKwon/SPARK-51432.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>