[SPARK-49137][SQL][FOLLOWUP] Assign a reasonable error condition, when the Boolean condition in the if statement returns an empty row
### What changes were proposed in this pull request?
The pr is following up https://github.com/apache/spark/pull/47648.
The pr aims to assign a reasonable `error condition`, when `the Boolean condition in the if statement` returns `an empty row`.

### Why are the changes needed?
In the previous PR, we overlooked a scenario where `the Boolean condition in the if statement` returns `an empty row`.

```
BEGIN
  CREATE TABLE t1 (a BOOLEAN) USING parquet;
  IF (select * from t1) THEN
    SELECT 46;
  END IF;
END
```

- Before:
```
[ROW_VALUE_IS_NULL] Found NULL in a row at the index 0, expected a non-NULL value. SQLSTATE: 22023
org.apache.spark.SparkRuntimeException: [ROW_VALUE_IS_NULL] Found NULL in a row at the index 0, expected a non-NULL value. SQLSTATE: 22023
	at org.apache.spark.sql.errors.DataTypeErrors$.valueIsNullError(DataTypeErrors.scala:275)
	at org.apache.spark.sql.Row.getAnyValAs(Row.scala:536)
	at org.apache.spark.sql.Row.getBoolean(Row.scala:224)
	at org.apache.spark.sql.Row.getBoolean$(Row.scala:224)
	at org.apache.spark.sql.catalyst.expressions.GenericRow.getBoolean(rows.scala:28)
	at org.apache.spark.sql.scripting.NonLeafStatementExec.evaluateBooleanCondition(SqlScriptingExecutionNode.scala:84)
	at org.apache.spark.sql.scripting.NonLeafStatementExec.evaluateBooleanCondition$(SqlScriptingExecutionNode.scala:71)
	at org.apache.spark.sql.scripting.IfElseStatementExec.evaluateBooleanCondition(SqlScriptingExecutionNode.scala:206)
	at org.apache.spark.sql.scripting.IfElseStatementExec$$anon$2.next(SqlScriptingExecutionNode.scala:230)
	at org.apache.spark.sql.scripting.IfElseStatementExec$$anon$2.next(SqlScriptingExecutionNode.scala:223)
	at org.apache.spark.sql.scripting.CompoundNestedStatementIteratorExec$$anon$1.next(SqlScriptingExecutionNode.scala:168)
	at org.apache.spark.sql.scripting.CompoundNestedStatementIteratorExec$$anon$1.next(SqlScriptingExecutionNode.scala:146)
```

- After:
```
{LINE:4} [BOOLEAN_STATEMENT_EMPTY_ROWS] Boolean statement (SELECT * FROM T1) is invalid. It returns an empty row. SQLSTATE: 21000
org.apache.spark.sql.exceptions.SqlScriptingException: {LINE:4} [BOOLEAN_STATEMENT_EMPTY_ROWS] Boolean statement (SELECT * FROM T1) is invalid. It returns an empty row. SQLSTATE: 21000
	at org.apache.spark.sql.errors.SqlScriptingErrors$.booleanStatementEmptyRows(SqlScriptingErrors.scala:85)
	at org.apache.spark.sql.scripting.NonLeafStatementExec.evaluateBooleanCondition(SqlScriptingExecutionNode.scala:87)
	at org.apache.spark.sql.scripting.NonLeafStatementExec.evaluateBooleanCondition$(SqlScriptingExecutionNode.scala:71)
	at org.apache.spark.sql.scripting.IfElseStatementExec.evaluateBooleanCondition(SqlScriptingExecutionNode.scala:211)
	at org.apache.spark.sql.scripting.IfElseStatementExec$$anon$2.next(SqlScriptingExecutionNode.scala:235)
	at org.apache.spark.sql.scripting.IfElseStatementExec$$anon$2.next(SqlScriptingExecutionNode.scala:228)
	at org.apache.spark.sql.scripting.CompoundNestedStatementIteratorExec$$anon$1.next(SqlScriptingExecutionNode.scala:173)
	at org.apache.spark.sql.scripting.CompoundNestedStatementIteratorExec$$anon$1.next(SqlScriptingExecutionNode.scala:151)
```

### Does this PR introduce _any_ user-facing change?
Yes, provide end-users with a more user-friendly error message.

### How was this patch tested?
Add new UT.

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #47754 from panbingkun/SPARK-49137_FOLLOWUP.

Authored-by: panbingkun <panbingkun@baidu.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>