[SPARK-6767][SQL] Fixed Query DSL error in spark sql Readme
Fixed the  following error
query.where('key > 30).select(avg('key)).collect()
<console>:43: error: value > is not a member of Symbol
              query.where('key > 30).select(avg('key)).collect()

Author: Tijo Thomas <tijoparacka@gmail.com>

Closes #5415 from tijoparacka/ERROR_SQL_DATAFRAME_EXAMPLE and squashes the following commits:

234751e [Tijo Thomas] Fixed Query DSL error in spark sql Readme

(cherry picked from commit 2f482d706b9d38820472c3152dbd1612c98729bd)
Signed-off-by: Reynold Xin <rxin@databricks.com>