[SPARK-48644][SQL] Do a length check and throw COLLECTION_SIZE_LIMIT_EXCEEDED error in Hex.hex
### What changes were proposed in this pull request?

A length check is necessary for heximalising the byte array as the new array size is 2x the original. If the length of the new byte array exceeds Int.MaxValue, we shall report the actual length and the threshold instead of NegativeArraySizeException

### Why are the changes needed?

improve error handling

### Does this PR introduce _any_ user-facing change?

Yes, we convert large strings or binary values to hex strings, if the max length exceeds, the raised error is changed

### How was this patch tested?

test manually without adding unit test because such a test case is quite memory consuming.
```
 org.apache.spark.sql.catalyst.expressions.Hex.hex((" " * (Int.MaxValue / 2 + 1)).getBytes)
org.apache.spark.SparkIllegalArgumentException: [COLLECTION_SIZE_LIMIT_EXCEEDED.INITIALIZE] Can't create array with 2147483648 elements which exceeding the array size limit 2147483647, cannot initialize an array with specified parameters. SQLSTATE: 54000
  at org.apache.spark.sql.errors.QueryExecutionErrors$.tooManyArrayElementsError(QueryExecutionErrors.scala:2517)
  at org.apache.spark.sql.catalyst.expressions.Hex$.hex(mathExpressions.scala:1042)
  ... 42 elided
```
### Was this patch authored or co-authored using generative AI tooling?
no

Closes #47001 from yaooqinn/SPARK-48644.

Authored-by: Kent Yao <yao@apache.org>
Signed-off-by: Kent Yao <yao@apache.org>