[SPARK-52096][SQL][SS] Reclassify kafka source offset assertion error
### What changes were proposed in this pull request?

This PR classifies the assertion error saying that the start offset of Kafka source is greater than end offset to either user error or Kafka internal error. There are different possible cases that can lead to this error. Here is a list in the time order that we can catch them:
1. If the user specifies startingOffset and endingOffset in a comparable way (either by index or timestamp), we can compare them before starting the query.
2. If the user provides startingOffset and endingOffset but they are incomparable initially, we should compare them as soon as they are resolved by contacting the kafka brokers.
3. If the user sets startingOffset to some value and endingOffset to latest, we should compare them after the query has started and the latest offset has been fetched.
4. It is a Kafka topic-partition is broken.
```
java.lang.AssertionError: assertion failed: Beginning offset 49041276637 is after the ending offset 48774253518 for topic xxx partition 1. You either provided an invalid fromOffset, or the Kafka topic has been damaged
	at scala.Predef$.assert(Predef.scala:223)
	at org.apache.spark.sql.kafka010.KafkaSourceRDD.compute(KafkaSourceRDD.scala:79)
	at org.apache.spark.rdd.RDD.$anonfun$computeOrReadCheckpoint$1(RDD.scala:409)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:406)
```

### Why are the changes needed?

Most of the time this assertion error is fired due to user errors, and we have the information to make it explicit. This PR tries to utilize all the information to separate user errors from system errors.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Creates some unit tests in `KafkaRelationSuiteBase`.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #50866 from eason-yuchen-liu/kafkaOffsetErrorMsg.

Authored-by: Yuchen Liu <170372783+eason-yuchen-liu@users.noreply.github.com>
Signed-off-by: Jungtaek Lim <kabhwan.opensource@gmail.com>