[SPARK-55831][FOLLOWUP] Fix Maven CI by replacing with dummy SPARK_HOME in test
### What changes were proposed in this pull request?

Create a dummy SPARK_HOME for test, so that the YARN test won't depend on `assembly` package.

### Why are the changes needed?

```
- YARN AM JavaOptions *** FAILED ***
  java.lang.IllegalStateException: Library directory '/home/runner/work/spark/spark/assembly/target/scala-2.13/jars' does not exist; make sure Spark is built.
  at org.apache.spark.launcher.CommandBuilderUtils.checkState(CommandBuilderUtils.java:230)
  at org.apache.spark.launcher.CommandBuilderUtils.findJarsDir(CommandBuilderUtils.java:320)
  at org.apache.spark.launcher.YarnCommandBuilderUtils$.findJarsDir(YarnCommandBuilderUtils.scala:36)
  at org.apache.spark.deploy.yarn.Client.prepareLocalResources(Client.scala:711)
  at org.apache.spark.deploy.yarn.Client.prepareLocalResources(Client.scala:529)
  at org.apache.spark.deploy.yarn.Client.createContainerLaunchContext(Client.scala:1042)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:569)
  ...
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass both Maven and SBT CI.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #54651 from pan3793/SPARK-55831-followup.

Authored-by: Cheng Pan <chengpan@apache.org>
Signed-off-by: yangjie01 <yangjie01@baidu.com>