[SPARK-47274][PYTHON][SQL] Provide more useful context for PySpark DataFrame API errors
### What changes were proposed in this pull request?

This PR introduces an enhancement to the error messages generated by PySpark's DataFrame API, adding detailed context about the location within the user's PySpark code where the error occurred.

This directly adds a PySpark user call site information into `DataFrameQueryContext` added from https://github.com/apache/spark/pull/43334, aiming to provide PySpark users with the same level of detailed error context for better usability and debugging efficiency for DataFrame APIs.

This PR also introduces `QueryContext.pysparkCallSite` and `QueryContext.pysparkFragment` to get a PySpark information from the query context easily.

This PR also enhances the functionality of `check_error` so that it can test the query context if it exists.

### Why are the changes needed?

To improve a debuggability. Errors originating from PySpark operations can be difficult to debug with limited context in the error messages. While improvements on the JVM side have been made to offer detailed error contexts, PySpark errors often lack this level of detail.

### Does this PR introduce _any_ user-facing change?

No API changes, but error messages will include a reference to the exact line of user code that triggered the error, in addition to the existing descriptive error message.

For example, consider the following PySpark code snippet that triggers a `DIVIDE_BY_ZERO` error:

```python
1  spark.conf.set("spark.sql.ansi.enabled", True)
2
3  df = spark.range(10)
4  df.select(df.id / 0).show()
```

**Before:**
```
pyspark.errors.exceptions.captured.ArithmeticException: [DIVIDE_BY_ZERO] Division by zero. Use `try_divide` to tolerate divisor being 0 and return NULL instead. If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error. SQLSTATE: 22012
== DataFrame ==
"divide" was called from
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**After:**
```
pyspark.errors.exceptions.captured.ArithmeticException: [DIVIDE_BY_ZERO] Division by zero. Use `try_divide` to tolerate divisor being 0 and return NULL instead. If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error. SQLSTATE: 22012
== DataFrame ==
"divide" was called from
/.../spark/python/test_pyspark_error.py:4
```

Now the error message points out the exact problematic code path with file name and line number that user writes.

## Points to the actual problem site instead of the site where the action was called

Even when action calling after multiple transform operations are mixed, the exact problematic site can be provided to the user:

**In:**

```python
  1 spark.conf.set("spark.sql.ansi.enabled", True)
  2 df = spark.range(10)
  3
  4 df1 = df.withColumn("div_ten", df.id / 10)
  5 df2 = df1.withColumn("plus_four", df.id + 4)
  6
  7 # This is problematic divide operation that occurs DIVIDE_BY_ZERO.
  8 df3 = df2.withColumn("div_zero", df.id / 0)
  9 df4 = df3.withColumn("minus_five", df.id / 5)
 10
 11 df4.collect()
```

**Out:**

```
pyspark.errors.exceptions.captured.ArithmeticException: [DIVIDE_BY_ZERO] Division by zero. Use `try_divide` to tolerate divisor being 0 and return NULL instead. If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error. SQLSTATE: 22012
== DataFrame ==
"divide" was called from
/.../spark/python/test_pyspark_error.py:8
```

### How was this patch tested?

Added UTs.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #45377 from itholic/error_context_for_dataframe_api.

Authored-by: Haejoon Lee <haejoon.lee@databricks.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>