[SPARK-51071][INFRA][3.5] Upgrade `upload-artifact` to v4 to recover `branch-3.5` CI
### What changes were proposed in this pull request?

This PR aims to upgrade `upload-artifact` to v4 to recover `branch-3.5` CI.

### Why are the changes needed?

`branch-3.5` GitHub Action CI is rejected because of `actions/upload-artifact: v3`.
- https://github.com/apache/spark/actions/workflows/build_main.yml?query=branch%3Abranch-3.5
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```

The rejection started on January 30th. We need to migrate immediately.
- https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Starting January 30th, 2025, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact).

### Does this PR introduce _any_ user-facing change?

No. This is an infra-only change.

### How was this patch tested?

The GitHub Action starts successfully on this PR.

```
$ git grep upload-artifactv4 | wc -l
      11
$ git grep upload-artifactv3 | wc -l
       0
```

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #49777 from dongjoon-hyun/SPARK-51071.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>