[SPARK-44247][BUILD] Upgrade Arrow to 13.0.0
### What changes were proposed in this pull request?
The pr aims to upgrade arrow from 12.0.1 to 13.0.0.

### Why are the changes needed?
1. Arrow 12.0.1 VS 13.0.0
https://github.com/apache/arrow/compare/apache-arrow-12.0.1...apache-arrow-13.0.0

2. Arrow 13.0.0 is the first version to support Java 21.
    - https://github.com/apache/arrow/pull/36370

When arrow version 12.0.1 running on Java21, the following error occurred:
```
java.lang.UnsupportedOperationException: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available
       org.apache.arrow.memory.util.MemoryUtil.directBuffer(MemoryUtil.java:167)
       org.apache.arrow.memory.ArrowBuf.getDirectBuffer(ArrowBuf.java:228)
       org.apache.arrow.memory.ArrowBuf.nioBuffer(ArrowBuf.java:223)
       org.apache.arrow.vector.ipc.ReadChannel.readFully(ReadChannel.java:87)
       org.apache.arrow.vector.ipc.message.MessageSerializer.readMessageBody(MessageSerializer.java:727)
       org.apache.arrow.vector.ipc.message.MessageChannelReader.readNext(MessageChannelReader.java:67)
       org.apache.arrow.vector.ipc.ArrowStreamReader.loadNextBatch(ArrowStreamReader.java:145)
```
After this PR, we can try to enable netty related testing in Java21.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
- Pass GA.

Closes #42181 from panbingkun/SPARK-44563.

Authored-by: panbingkun <pbk1982@gmail.com>
Signed-off-by: Dongjoon Hyun <dhyun@apple.com>