[SPARK-47096][INFRA] Upgrade Python version in Maven builds
### What changes were proposed in this pull request?

This PR upgrades Python version to make the build compatible with macos-14

### Why are the changes needed?

macos-14 build fails during Python 3.9 installation, see https://github.com/apache/spark/actions/runs/7964626045/job/21742574260

```
  Error: dyld[4738]: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
    Referenced from: <E2FD7085-038F
  Error: -3B8E-94C6-6649527BFDBE> /Users/runner/hostedtoolcache/Python/3.9.18/x64/bin/python3.9
    Reason: tried: '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/lib/libintl.8.dylib' (no such file), '/usr/lib/libintl.8.dylib' (no such file, not in dyld cache)
  ./setup.sh: line 52:  4738 Abort trap: 6           ./python -m ensurepip
```

In fact, marcos-14 already has Python 3.11 (https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md).

### Does this PR introduce _any_ user-facing change?

No, test-only.

### How was this patch tested?

Will monitor the scheduled build.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #45172 from HyukjinKwon/SPARK-47096.

Lead-authored-by: Hyukjin Kwon <gurwls223@apache.org>
Co-authored-by: Hyukjin Kwon <gurwls223@gmail.com>
Signed-off-by: Dongjoon Hyun <dhyun@apple.com>