[SPARK-46927][PYTHON] Make `assertDataFrameEqual` work properly without PyArrow
### What changes were proposed in this pull request?

This PR proposes to fix `assertDataFrameEqual` to work properly without PyArrow

### Why are the changes needed?

The current way does not work properly without PyArrow.

### Does this PR introduce _any_ user-facing change?

`assertDataFrameEqual` will raise proper error without PyArrow.

**Before**
```python
>>> from pyspark.testing.utils import assertDataFrameEqual
>>> dict1 = {"a": 1, "b": 2}
>>> dict2 = {"a": 1, "b": 2}
>>> assertDataFrameEqual(dict1, dict2)
AttributeError: 'dict' object has no attribute 'schema'
```

**After**
```python
>>> from pyspark.testing.utils import assertDataFrameEqual
>>> dict1 = {"a": 1, "b": 2}
>>> dict2 = {"a": 1, "b": 2}
>>> assertDataFrameEqual(dict1, dict2)
pyspark.errors.exceptions.base.PySparkAssertionError: [INVALID_TYPE_DF_EQUALITY_ARG] Expected type Union[DataFrame, ps.DataFrame, List[Row]] for `actual` but got type <class 'dict'>.
```

### How was this patch tested?

UT

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #44960 from itholic/SPARK-46927.

Authored-by: Haejoon Lee <haejoon.lee@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>