[SPARK-51229][BUILD][CONNECT] Fix dependency:analyze goal on connect common
### What changes were proposed in this pull request?
Update dependency of connect common library

### Why are the changes needed?
There are used and undeclared dependencies and also declared and not used:
```
[WARNING] Used undeclared dependencies found:
[WARNING]    com.google.guava:guava:jar:33.4.0-jre:provided
[WARNING]    org.apache.commons:commons-lang3:jar:3.17.0:compile
[WARNING]    org.scala-lang:scala-reflect:jar:2.13.16:compile
[WARNING]    com.google.api.grpc:proto-google-common-protos:jar:2.41.0:compile
[WARNING]    org.apache.arrow:arrow-vector:jar:18.1.0:compile
[WARNING]    org.apache.arrow:arrow-memory-core:jar:18.1.0:compile
[WARNING]    org.apache.spark:spark-connect-shims_2.13:jar:4.1.0-SNAPSHOT:compile
[WARNING]    org.apache.arrow:arrow-format:jar:18.1.0:compile
[WARNING]    org.slf4j:slf4j-api:jar:2.0.16:compile
[WARNING]    commons-codec:commons-codec:jar:1.17.2:compile
[WARNING]    org.json4s:json4s-core_2.13:jar:4.0.7:compile
[WARNING]    org.apache.spark:spark-unsafe_2.13:jar:4.1.0-SNAPSHOT:compile
[WARNING]    org.json4s:json4s-ast_2.13:jar:4.0.7:compile
[WARNING]    io.grpc:grpc-api:jar:1.67.1:compile
[WARNING]    org.apache.spark:spark-tags_2.13:jar:4.1.0-SNAPSHOT:compile
[WARNING]    org.apache.spark:spark-common-utils_2.13:jar:4.1.0-SNAPSHOT:compile
[WARNING] Unused declared dependencies found:
[WARNING]    io.grpc:grpc-netty:jar:1.67.1:compile
[WARNING]    io.grpc:grpc-services:jar:1.67.1:compile
[WARNING]    io.grpc:grpc-inprocess:jar:1.67.1:compile
[WARNING]    io.netty:netty-codec-http2:jar:4.1.117.Final:compile
[WARNING]    io.netty:netty-handler-proxy:jar:4.1.117.Final:compile
[WARNING]    io.netty:netty-transport-native-unix-common:jar:4.1.117.Final:compile
[WARNING]    org.apache.tomcat:annotations-api:jar:6.0.53:compile
[WARNING]    org.apache.spark:spark-tags_2.13:test-jar:tests:4.1.0-SNAPSHOT:test
[WARNING]    org.spark-project.spark:unused:jar:1.0.0:compile
[WARNING]    org.scalatest:scalatest_2.13:jar:3.2.19:test
[WARNING]    org.scalatestplus:scalacheck-1-18_2.13:jar:3.2.19.0:test
[WARNING]    org.scalatestplus:mockito-5-12_2.13:jar:3.2.19.0:test
[WARNING]    org.scalatestplus:selenium-4-21_2.13:jar:3.2.19.0:test
[WARNING]    org.junit.jupiter:junit-jupiter:jar:5.11.4:test
[WARNING]    com.github.sbt.junit:jupiter-interface:jar:0.13.3:test
```
and it causes errors while running JVM client tests:
```
./build/mvn -Dtest=none -DwildcardSuites=org.apache.spark.sql.connect.CatalogSuite test -pl sql/connect/client/jvm
...
*** RUN ABORTED ***
A needed class was not found. This could be due to an error in your runpath. Missing class: org/sparkproject/guava/cache/CacheLoader
  java.lang.NoClassDefFoundError: org/sparkproject/guava/cache/CacheLoader
  at org.apache.spark.sql.connect.test.SparkConnectServerUtils$.createSparkSession(RemoteSparkSession.scala:183)
  at org.apache.spark.sql.connect.test.RemoteSparkSession.beforeAll(RemoteSparkSession.scala:215)
  at org.apache.spark.sql.connect.test.RemoteSparkSession.beforeAll$(RemoteSparkSession.scala:213)
  at org.apache.spark.sql.connect.CatalogSuite.beforeAll(CatalogSuite.scala:30)
  at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
  at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
  at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
  at org.apache.spark.sql.connect.CatalogSuite.run(CatalogSuite.scala:30)
  at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1178)
  at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1225)
  ...
  Cause: java.lang.ClassNotFoundException: org.sparkproject.guava.cache.CacheLoader
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
  at org.apache.spark.sql.connect.test.SparkConnectServerUtils$.createSparkSession(RemoteSparkSession.scala:183)
  at org.apache.spark.sql.connect.test.RemoteSparkSession.beforeAll(RemoteSparkSession.scala:215)
  at org.apache.spark.sql.connect.test.RemoteSparkSession.beforeAll$(RemoteSparkSession.scala:213)
  at org.apache.spark.sql.connect.CatalogSuite.beforeAll(CatalogSuite.scala:30)
  at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
  at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
  at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
The patch was tested using `build/mvn install` and `dependency:analyze`.

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #49971 from vrozov/SPARK-51229.

Authored-by: Vlad Rozov <vrozov@amazon.com>
Signed-off-by: Herman van Hovell <herman@databricks.com>
(cherry picked from commit 7653b400333085e038c6bfbc019d0849957ea5d0)
Signed-off-by: Herman van Hovell <herman@databricks.com>