[SPARK-42429][BUILD] Fix a sbt compile error for `getArgument` when using IntelliJ
### What changes were proposed in this pull request?
When build with IntelliJ, I hit the following error from time to time:
```
spark/sql/core/src/test/scala/org/apache/spark/sql/execution/command/PlanResolutionSuite.scala:149:18
value getArgument is not a member of org.mockito.invocation.InvocationOnMock
      invocation.getArgument[Identifier](0).name match {
```
Sometimes the error can be solved by rebuilt with sbt or maven. But the best might be just avoid using the method that causes this compilation error.

### Why are the changes needed?
Make the life easier for IDE users.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Manual and existing tests

Closes #40004 from zhenlineo/fix-ide-old-errors.

Authored-by: Zhen Li <zhenlineo@users.noreply.github.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>