[SPARK-55896][PS] Use numpy functions instead of builtins
### What changes were proposed in this pull request?

Uses `numpy` functions instead of builtins and fix groupby-apply.

### Why are the changes needed?

In pandas 3, the given builtin functions won't implicitly be replaced with the corresponding `numpy` function anymore.

For example:

```py
>>> pdf = pd.DataFrame(
...     {"d": [1.0, 1.0, 1.0, 2.0, 2.0, 2.0], "v": [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]}
... )
```

- pandas 2

```py
>>> pdf.groupby("d").apply(sum)
<stdin>:1: FutureWarning: The provided callable <built-in function sum> is currently using np.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string np.sum instead.
       d     v
d
1.0  3.0   6.0
2.0  6.0  15.0
```

- pandas 3

```py
>>> pdf.groupby("d").apply(sum)
Traceback (most recent call last):
...
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

### Does this PR introduce _any_ user-facing change?

Yes, it will behave more like pandas 3.

### How was this patch tested?

Updated the related tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #54699 from ueshin/issues/SPARK-55896/builtin.

Authored-by: Takuya Ueshin <ueshin@databricks.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>