[SPARK-54745][PYTHON] Fix PySpark import error caused by missing UnixStreamServer on Windows
### What changes were proposed in this pull request?

This PR fixes an error caused by `socketserver.UnixStreamServer` not being available on Windows. We define a fallback `AccumulatorUnixServer` to raise an exception on construction and inform the user to disable `spark.python.unix.domain.socket.enabled`.

### Why are the changes needed?

`import pyspark` fails with the following message on Windows since PySpark 4.1.0:

```
sedona\spark\__init__.py:19: in <module>
    import pyspark
.venv\Lib\site-packages\pyspark\__init__.py:71: in <module>
    from pyspark.accumulators import Accumulator, AccumulatorParam
.venv\Lib\site-packages\pyspark\accumulators.py:324: in <module>
    class AccumulatorUnixServer(socketserver.UnixStreamServer):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E   AttributeError: module 'socketserver' has no attribute 'UnixStreamServer'
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manually test this on Windows 11

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #53546 from Kontinuation/fix-uds-windows-compat.

Authored-by: Kristin Cowalcijk <bo@wherobots.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>