[SPARK-41821][CONNECT][PYTHON] Fix doc test for DataFrame.describe
### What changes were proposed in this pull request?
Currently, the python doc test failed caused by `DataFrame.describe`
```
File "/Users/s.singh/personal/spark-oss/python/pyspark/sql/connect/dataframe.py", line 898, in pyspark.sql.connect.dataframe.DataFrame.describe
Failed example:
    df.describe(['age']).show()
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest pyspark.sql.connect.dataframe.DataFrame.describe[1]>", line 1, in <module>
        df.describe(['age']).show()
      File "/Users/s.singh/personal/spark-oss/python/pyspark/sql/connect/dataframe.py", line 832, in describe
        raise TypeError(f"'cols' must be list[str], but got {type(s).__name__}")
    TypeError: 'cols' must be list[str], but got list
```

This PR also adds some tests into `test_connect_basic.py`.

### Why are the changes needed?
Let the python doc test success.
Adds test cases.

### Does this PR introduce _any_ user-facing change?
'No'.
New feature.

### How was this patch tested?
N/A

Closes #39378 from beliefer/SPARK-41821.

Authored-by: Jiaan Geng <beliefer@163.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>