[SPARK-41811][PYTHON][CONNECT] Implement SparkSession.sql's string formatter
### What changes were proposed in this pull request?
Implement SparkSession.sql's string formatter

### Why are the changes needed?
for parity

### Does this PR introduce _any_ user-facing change?
yes

before:
```
In [1]: spark.createDataFrame([("Alice", 6), ("Bob", 7), ("John", 10)], ['name', 'age']).createOrReplaceTempView("person")

In [2]: spark.sql("""SELECT * FROM person WHERE age < {age}""", age = 9).show()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 spark.sql("""SELECT * FROM person WHERE age < {age}""", age = 9).show()

TypeError: sql() got an unexpected keyword argument 'age'
```

after:
```
In [1]: spark.createDataFrame([("Alice", 6), ("Bob", 7), ("John", 10)], ['name', 'age']).createOrReplaceTempView("person")

In [2]: spark.sql("""SELECT * FROM person WHERE age < {age}""", age = 9).show()
+-----+---+
| name|age|
+-----+---+
|Alice|  6|
|  Bob|  7|
+-----+---+
```

### How was this patch tested?
enabled doc test

Closes #41980 from zhengruifeng/py_connect_sql_formatter.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>