[SPARK-51649][SQL] Dynamic writes/reads of TIME partitions
### What changes were proposed in this pull request?
In the PR, I propose to support partition values of the TIME type. In particular, if the desired type is `TimeType(n)`, cast partition values by the `Cast` expression to the type.

### Why are the changes needed?
To fix the failure on reading TIME partitions:
```scala
scala> spark.read.schema("t TIME, id INT").parquet("/Users/maxim.gekk/tmp/time_parquet").show(false)
org.apache.spark.SparkRuntimeException: [INVALID_PARTITION_VALUE] Failed to cast value '12%3A00%3A00' to data type "TIME(6)" for partition column `t`. Ensure the value matches the expected data type for this partition column. SQLSTATE: 42846
```

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
By running the new test:
```
$ build/sbt "test:testOnly *PartitionedWriteSuite"
```

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #50442 from MaxGekk/read-time-partition.

Authored-by: Max Gekk <max.gekk@gmail.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>