[SPARK-44722][CONNECT] ExecutePlanResponseReattachableIterator._call_iter: AttributeError: 'NoneType' object has no attribute 'message'
### What changes were proposed in this pull request?

Tiny error during exception handling: status might in some cases be None.

Make a similar change in scala client just to be defensive, because there it appears that it may never happen (when we catch `StatusRuntimeException`, `StatusProto.fromThrowable` should never return null).

### Why are the changes needed?

Fix an error during reattach retry handling.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Tests that will be published in a followup.

Closes #42397 from juliuszsompolski/SPARK-44722.

Authored-by: Juliusz Sompolski <julek@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
(cherry picked from commit ea00ecd1f88beda2f97b03ccdea5d78dd178f3b6)
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>