[SPARK-51983][PS][TESTS][FOLLOW-UP] Replace `assertEquals` with `assertEqual` for python 3.12+
### What changes were proposed in this pull request?
Replace `assertEquals` with `assertEqual' for python 3.12+

### Why are the changes needed?

`assertEquals` was removed in 3.12, see https://docs.python.org/3/whatsnew/3.12.html#id3

tests in python 3.12+ was broken https://github.com/apache/spark/actions/runs/14914041146/job/41895320048

```
======================================================================
ERROR: test_align (pyspark.pandas.tests.diff_frames_ops.test_align.DiffFramesAlignTests.test_align)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/spark/spark/python/pyspark/testing/pandasutils.py", line 482, in setUp
    self.assertEquals(
    ^^^^^^^^^^^^^^^^^
AttributeError: 'DiffFramesAlignTests' object has no attribute 'assertEquals'. Did you mean: 'assertEqual'?

======================================================================
ERROR: test_assert_classic_mode (pyspark.pandas.tests.diff_frames_ops.test_align.DiffFramesAlignTests.test_assert_classic_mode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/spark/spark/python/pyspark/testing/pandasutils.py", line 482, in setUp
    self.assertEquals(
    ^^^^^^^^^^^^^^^^^
AttributeError: 'DiffFramesAlignTests' object has no attribute 'assertEquals'. Did you mean: 'assertEqual'?

======================================================================
ERROR: test_assert_classic_mode (pyspark.testing.pandasutils.PandasOnSparkTestCase.test_assert_classic_mode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/spark/spark/python/pyspark/testing/pandasutils.py", line 482, in setUp
    self.assertEquals(
    ^^^^^^^^^^^^^^^^^
AttributeError: 'PandasOnSparkTestCase' object has no attribute 'assertEquals'. Did you mean: 'assertEqual'?
```

### Does this PR introduce _any_ user-facing change?
no, test-only

### How was this patch tested?
manually test

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #50842 from zhengruifeng/fix_assertEquals.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>