[SPARK-37865][SQL][FOLLOWUP] Fix compilation error for union deduplication correctness bug fixup
### What changes were proposed in this pull request?

Fixes compilation error following https://github.com/apache/spark/pull/35760.

### Why are the changes needed?

Compilation error: https://github.com/apache/spark/runs/5473941519?check_suite_focus=true

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unit tests

Closes #35842 from karenfeng/SPARK-37865-branch-3.0.

Authored-by: Karen Feng <karen.feng@databricks.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>