[SPARK-41155][SQL] Add error message to SchemaColumnConvertNotSupportedException
### What changes were proposed in this pull request?

This patch adds error message to `SchemaColumnConvertNotSupportedException`.

### Why are the changes needed?

Just found the fact that `SchemaColumnConvertNotSupportedException` doesn't have any error message is annoying for debugging.

In stack trace, we only see `SchemaColumnConvertNotSupportedException` but don't know what column is wrong.

After this change, we should be able to see it, e.g.,

```
org.apache.spark.sql.execution.datasources.SchemaColumnConvertNotSupportedException: column: [_1], physicalType: INT32, logicalType: bigint
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing tests.

Closes #38669 from viirya/add_error_message.

Authored-by: Liang-Chi Hsieh <viirya@gmail.com>
Signed-off-by: Liang-Chi Hsieh <viirya@gmail.com>