[SPARK-42936][SQL] Fix LCA bug when the having clause can be resolved directly by its child Aggregate
### What changes were proposed in this pull request?

The PR fixes the following bug in LCA + having resolution:
```sql
select sum(value1) as total_1, total_1
from values(1, 'name', 100, 50) AS data(id, name, value1, value2)
having total_1 > 0

SparkException: [INTERNAL_ERROR] Found the unresolved operator: 'UnresolvedHaving (total_1#353L > cast(0 as bigint))
```
To trigger the issue, the having condition need to be (can be resolved by) an attribute in the select.
Without the LCA `total_1`, the query works fine.

#### Root cause of the issue
`UnresolvedHaving` with `Aggregate` as child can use both the `Aggregate`'s output and the `Aggregate`'s child's output to resolve the having condition. If using the latter, `ResolveReferences` rule will replace the unresolved attribute with a `TempResolvedColumn`.
For a `UnresolvedHaving` that actually can be resolved directly by its child `Aggregate`, there will be no `TempResolvedColumn` after the rule `ResolveReferences` applies. This  `UnresolvedHaving` still needs to be transformed to `Filter` by rule `ResolveAggregateFunctions`. This rule recognizes the shape: `UnresolvedHaving - Aggregate`.
However, the current condition (the plan should not contain `TempResolvedColumn`) that prevents LCA rule to apply between `ResolveReferences` and `ResolveAggregateFunctions` does not cover the above case. It can insert `Project` in the middle and break the shape can be matched by `ResolveAggregateFunctions`.

#### Fix
The PR adds another condition for LCA rule to apply: the plan should not contain any `UnresolvedHaving`.

### Why are the changes needed?

See above reasoning to fix the bug.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing and added tests.

Closes #40558 from anchovYu/lca-having-bug-fix.

Authored-by: Xinyi Yu <xinyi.yu@databricks.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>