[SPARK-46337][SQL][CONNECT][PYTHON] Make `CTESubstitution` retain the `PLAN_ID_TAG`
### What changes were proposed in this pull request?
Make `CTESubstitution` retain the `PLAN_ID_TAG`

### Why are the changes needed?
before this PR:
```
df1 = spark.range(10)
df2 = spark.sql("with dt as (select 1 as ida) select ida as id from dt")
df1.join(df2, df1.id == df2.id)

AnalysisException: When resolving 'id, fail to find subplan with plan_id=2 in 'Join Inner, '`==`('id, 'id)
:- Range (0, 10, step=1, splits=Some(12))
+- WithCTE
   :- CTERelationDef 4, false
   :  +- SubqueryAlias dt
   :     +- Project [1 AS ida#22]
   :        +- OneRowRelation
   +- Project [ida#22 AS id#21]
      +- SubqueryAlias dt
         +- CTERelationRef 4, true, [ida#22], false
```

### Does this PR introduce _any_ user-facing change?
yes

### How was this patch tested?
added ut

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #44268 from zhengruifeng/connect_plan_id_cte.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>