[SPARK-41972][TESTS] Fix a flaky test in StreamingQueryStatusListenerSuite
### What changes were proposed in this pull request?

Fix flaky test in StreamingQueryStatusListenerSuite.
Example failed test https://github.com/gengliangwang/spark/actions/runs/3880260857/jobs/6629409770:
```
StreamingQueryStatusListenerSuite.test small retained queries
org.scalatest.exceptions.TestFailedDueToTimeoutException: The code passed to eventually never returned normally. Attempted 638 times over 10.006178314 seconds. Last failure message: Set(301dad06-8fd7-4766-8d61-a58724d2c966, fab95baf-25ad-47dc-89fd-ff49bf1a4c4e) did not equal Set(60d3b5b0-7397-4212-8a18-ff67a17f362a, fab95baf-25ad-47dc-89fd-ff49bf1a4c4e).
```
The retention queries after eviction(by the ending timestamp) are different from what is expected. I suspect that some of the input queries has the same ending timestamp.
Another proof: with RocksDB as backend, the test case always pass since writing to RocksDB takes more time.

So, I suggest adding `Thread.sleep` between the termination of these queries to fix the flakiness.

### Why are the changes needed?

Fix flaky test

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

GA test

Closes #39494 from gengliangwang/fixFlaky.

Authored-by: Gengliang Wang <gengliang@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>