[SPARK-50232][PYTHON][CONNECT] Add 'protobuf==5.28.3' in dev/requirements.txt
### What changes were proposed in this pull request?

This PR proposes to add 'protobuf==5.28.3' in `dev/requirements.txt`. If you have an old version in your env, you would face an error like:

```
google.protobuf.runtime_version.VersionError: Detected incompatible Protobuf Gencode/Runtime versions when loading spark/connect/base.proto: gencode 5.28.3 runtime 5.28.2. Runtime version cannot be older than the linked gencode version. See Protobuf version guarantees at https://protobuf.dev/support/cross-version-runtime-guarantee.
```

This PR is a sort of a followup of https://github.com/apache/spark/pull/48644

### Why are the changes needed?

So developers can easily set up their env.

### Does this PR introduce _any_ user-facing change?

No, dev-only.

### How was this patch tested?

Manually installed and tested.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #48763 from HyukjinKwon/note-protobuf.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>