Fix __repr__ behaviour for Rows.
Rows __repr__ assumes data is strings when column name is missing.

Examples,
>>> Row ("Alice", "11")
<Row(Alice, 11)>

>>> Row (name="Alice", age=11)
Row(age=11, name='Alice')

>>> Row ("Alice", 11)
<snip stack trace>
TypeError: sequence item 1: expected string, int found

This is because Row () when called without column names assumes
everything is string.