[SPARK-45113][PYTHON][DOCS][FOLLOWUP] Add sorting to the example of `collect_set/collect_list` to ensure stable results
### What changes were proposed in this pull request?
This PR adds a `sort_array` for the output results of `collect_set` and `collect_list` to ensure the output is stable.

### Why are the changes needed?
When executing the Example of `collect_set` and `collect_list` with different versions of Scala, the output results may differ, resulting in the failure of daily tests on Scala 2.13:

- https://github.com/apache/spark/actions/runs/6209111340/job/16856005714

```
**********************************************************************
File "/__w/spark/spark/python/pyspark/sql/connect/functions.py", line 1030, in pyspark.sql.connect.functions.collect_set
Failed example:
    df.select(sf.collect_set('age')).show()
Expected:
    +----------------+
    |collect_set(age)|
    +----------------+
    |          [5, 2]|
    +----------------+
Got:
    +----------------+
    |collect_set(age)|
    +----------------+
    |          [2, 5]|
    +----------------+
    <BLANKLINE>
**********************************************************************
   1 of   9 in pyspark.sql.connect.functions.collect_set
***Test Failed*** 1 failures.

Had test failures in pyspark.sql.connect.functions with python3.9; see logs.
Error:  running /__w/spark/spark/python/run-tests --modules=pyspark-connect --parallelism=1 ; received return code 255
Error: Process completed with exit code 19.
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GitHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #42968 from LuciferYang/SPARK-45113-FOLLOWUP.

Lead-authored-by: yangjie01 <yangjie01@baidu.com>
Co-authored-by: YangJie <yangjie01@baidu.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>