[SPARK-36742][PYTHON] Fix ps.to_datetime with plurals of keys like years, months, days
### What changes were proposed in this pull request?
Fix ps.to_datetime with plurals of keys like years, months, days.

### Why are the changes needed?
Fix ps.to_datetime with plurals of keys like years, months, days
Before this PR
``` python
# pandas
df_test = pd.DataFrame({'years': [2015, 2016], 'months': [2, 3], 'days': [4, 5]})
df_test['date'] = pd.to_datetime(df_test[['years', 'months', 'days']])
df_test

   years  months  days       date
0   2015       2     4 2015-02-04
1   2016       3     5 2016-03-05

# pandas on spark
df_test = ps.DataFrame({'years': [2015, 2016], 'months': [2, 3], 'days': [4, 5]})
df_test['date'] = ps.to_datetime(df_test[['years', 'months', 'days']])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u02/spark/python/pyspark/pandas/namespace.py", line 1643, in to_datetime
    psdf = arg[["year", "month", "day"]]
  File "/u02/spark/python/pyspark/pandas/frame.py", line 11888, in __getitem__
    return self.loc[:, list(key)]
  File "/u02/spark/python/pyspark/pandas/indexing.py", line 480, in __getitem__
    ) = self._select_cols(cols_sel)
  File "/u02/spark/python/pyspark/pandas/indexing.py", line 325, in _select_cols
    return self._select_cols_by_iterable(cols_sel, missing_keys)
  File "/u02/spark/python/pyspark/pandas/indexing.py", line 1356, in _select_cols_by_iterable
    raise KeyError("['{}'] not in index".format(name_like_string(key)))
KeyError: "['year'] not in index"
```

### Does this PR introduce _any_ user-facing change?
After this PR :
``` python
df_test = ps.DataFrame({'years': [2015, 2016], 'months': [2, 3], 'days': [4, 5]})
df_test['date'] = ps.to_datetime(df_test[['years', 'months', 'days']])
df_test

   years  months  days       date
0   2015       2     4 2015-02-04
1   2016       3     5 2016-03-05
```

### How was this patch tested?
Unit tests

Closes #34182 from dchvn/SPARK-36742.

Authored-by: dch nguyen <dgd_contributor@viettel.com.vn>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>