[SPARK-47144][CONNECT][SQL][PYTHON] Fix Spark Connect collation error by adding collateId protobuf field
### What changes were proposed in this pull request?

Collated expression `SELECT 'abc' COLLATE 'UCS_BASIC_LCASE'` is failing when connecting to sever using Spark Connect (in this case with pyspark):
```
pyspark.errors.exceptions.connect.SparkConnectGrpcException: (org.apache.spark.sql.connect.common.InvalidPlanInput) Does not support convert string(UCS_BASIC_LCASE) to connect proto types.
```
When using default collation `UCS_BASIC`, the error is not occurring.

Fix the error by making `StringType` protobuf compliant with Spark datatype which now includes collation id.

### Why are the changes needed?

To fix the error which collations introduce in Spark connect.

### Does this PR introduce _any_ user-facing change?

Yes, when previously running
```
$ ./bin/pyspark --remote 'sc://localhost'
...
>>> spark.sql("SELECT 'abc' COLLATE 'UCS_BASIC_LCASE'")
...
```
the described error would appear. These changes remove the error.

### How was this patch tested?

Changes include test which simulates described behavior by utilizing `SparkConnectServerTest` to establish client-server connection. Test is invoked by `build/sbt 'connect/testOnly *SparkConnectServiceE2ESuite'`.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #45233 from nikolamand-db/nikolamand-db/SPARK-47144.

Authored-by: Nikola Mandic <nikola.mandic@databricks.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>