[SPARK-41971][PYTHON][FOLLOWUP] Fix toPandas to support empty columns
### What changes were proposed in this pull request?

This is a follow-up of #40988.

Fixes `df.toPandas` to support empty columns.

The result will be no-column, same-length dataframe.

```py
>>> spark.range(2).select([]).toPandas()
Empty DataFrame
Columns: []
Index: [0, 1]
```

### Why are the changes needed?

Currently `df.toPandas()` fails if the columns are empty:

```py
>>> spark.range(2).select([]).toPandas()
Traceback (most recent call last):
...
ValueError: No objects to concatenate
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Added the related test.

Closes #41160 from ueshin/issues/SPARK-41971/empty_columns.

Authored-by: Takuya UESHIN <ueshin@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>