[SPARK-37041][SQL] Backport HIVE-15025: Secure-Socket-Layer (SSL) support for HMS
### What changes were proposed in this pull request?

This pr backport HIVE-15025: Secure-Socket-Layer (SSL) support for HMS.

### Why are the changes needed?

To make it easy upgrade Thrift:
```
[error] /home/jenkins/workspace/SparkPullRequestBuilder/sql/hive-thriftserver/src/main/java/org/apache/hive/service/auth/HiveAuthFactory.java:254:1:  error: incompatible types: String cannot be converted to TConfiguration
[error]     return new TSocket(host, port, loginTimeout);
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing test.

Closes #34312 from wangyum/SPARK-37041.

Authored-by: Yuming Wang <yumwang@ebay.com>
Signed-off-by: Yuming Wang <yumwang@ebay.com>