[SPARK-38911][CORE][TEST] Fix 'test 1 resource profile' failed when running it in IDEA
The test `test 1 resource profile` of DAGSchedulerSuite will fail if I run it in IDEA separately.
This issue does not exist when running all DAGSchedulerSuite one by one, since the SparkContext
will be initialized at the very beginning.

The root cause is the ResourceProfile is initialized before SparkContext, and it will take
`DEFAULT_RESOURCE_PROFILE_ID` as the resource profile id. But the test asserts that the id is not equal
to DEFAULT_RESOURCE_PROFILE_ID.

```
assert(expectedid.get != ResourceProfile.DEFAULT_RESOURCE_PROFILE_ID)
```

The exception is like as below,

```
0 equaled 0
ScalaTestFailureLocation: org.apache.spark.scheduler.DAGSchedulerSuite at (DAGSchedulerSuite.scala:3269)
org.scalatest.exceptions.TestFailedException: 0 equaled 0
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
	at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1231)
	at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:1295)
	at org.apache.spark.scheduler.DAGSchedulerSuite.$anonfun$new$191(DAGSchedulerSuite.scala:3269)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

This PR first calls SparkContext, and then requests the ResourceProfile.