[SPARK-37253][PYTHON] `try_simplify_traceback` should not fail when `tb_frame.f_lineno` is None
### What changes were proposed in this pull request?

This PR aims to handle the corner case when `tb_frame.f_lineno` is `None` in `try_simplify_traceback` which was added by https://github.com/apache/spark/pull/30309 at Apache Spark 3.1.0.

### Why are the changes needed?

This will handle the following corner case.
```python
Traceback (most recent call last):
  File "/Users/dongjoon/APACHE/spark-merge/python/lib/pyspark.zip/pyspark/worker.py", line 630, in main
    tb = try_simplify_traceback(sys.exc_info()[-1])
  File "/Users/dongjoon/APACHE/spark-merge/python/lib/pyspark.zip/pyspark/util.py", line 217, in try_simplify_traceback
    new_tb = types.TracebackType(
TypeError: 'NoneType' object cannot be interpreted as an integer
```

Python GitHub Repo also has the test case for this corner case.
- https://github.com/python/cpython/blob/main/Lib/test/test_exceptions.py#L2373
```python
None if frame.f_lineno is None else
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

N/A

Closes #34530 from dongjoon-hyun/SPARK-37253.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
(cherry picked from commit 8ae88d01b46d581367d0047b50fcfb65078ab972)
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>