[SPARK-36949][SQL] Disallow Hive provider tables with ANSI intervals
### What changes were proposed in this pull request?
In the PR, I propose to check column types of tables that use `Hive` as the **provider**, and disallow tables with ANSI intervals. Currently, Hive Metastore & SerDe don't support creating tables with interval types. So, even Spark converts Catalyst's ANSI interval types to Hive's types:
- `YearMonthIntervalType` -> [INTERVAL_YEAR_MONTH](https://github.com/apache/hive/blob/7b3ecf617a6d46f48a3b6f77e0339fd4ad95a420/serde/src/java/org/apache/hadoop/hive/serde2/thrift/Type.java#L78-L80)
- `DayTimeIntervalType` -> [INTERVAL_DAY_TIME](https://github.com/apache/hive/blob/7b3ecf617a6d46f48a3b6f77e0339fd4ad95a420/serde/src/java/org/apache/hadoop/hive/serde2/thrift/Type.java#L81-L83)

Hive Metastore fails with the error (for parquet SerDe):
```java
Caused by: java.lang.UnsupportedOperationException: Unknown field type: interval_year_month
	at org.apache.hadoop.hive.ql.io.parquet.serde.ArrayWritableObjectInspector.getObjectInspector(ArrayWritableObjectInspector.java:141)
	at org.apache.hadoop.hive.ql.io.parquet.serde.ArrayWritableObjectInspector.<init>(ArrayWritableObjectInspector.java:86)
	at org.apache.hadoop.hive.ql.io.parquet.serde.ArrayWritableObjectInspector.<init>(ArrayWritableObjectInspector.java:59)
	at org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe.initialize(ParquetHiveSerDe.java:129)
```
at https://github.com/apache/hive/blame/master/ql/src/java/org/apache/hadoop/hive/ql/io/parquet/serde/ArrayWritableObjectInspector.java#L94 .

After the changes, Spark will verify column types before sending unnecessary requests to Hive Metastore.

I more details, I added new check to the existing function `DDLUtils.checkDataColNames()`, and renamed the function to `checkTableColumns()` because it checks table column names together with column types.

**Note:** We still allow tables of non-Hive provider with ANSI intervals using Hive external catalog, see https://github.com/apache/spark/pull/34215.

### Why are the changes needed?
To make the error message more clear and independent from Hive Metastore.

### Does this PR introduce _any_ user-facing change?
Yes. This PR changes the error message.

Before:
```SQL
spark-sql> CREATE TABLE TBL STORED AS PARQUET AS SELECT INTERVAL '1-1' YEAR TO MONTH AS YM;
Error in query: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.IllegalArgumentException: Error: type expected at the position 0 of 'interval year to month' but 'interval year to month' is found.
```

After:
```SQL
spark-sql> CREATE TABLE TBL STORED AS PARQUET AS SELECT INTERVAL '1-1' YEAR TO MONTH AS YM;
21/10/12 16:51:14 ERROR SparkSQLDriver: Failed in [CREATE TABLE TBL STORED AS PARQUET AS SELECT INTERVAL '1-1' YEAR TO MONTH AS YM]
java.lang.UnsupportedOperationException: Hive table `default`.`TBL` with ANSI intervals is not supported
	at org.apache.spark.sql.errors.QueryExecutionErrors$.hiveTableWithAnsiIntervalsError(QueryExecutionErrors.scala:1831)
```

### How was this patch tested?
By running new tests:
```
$ build/sbt -Phive-2.3 "test:testOnly *HiveDDLSuite"
```

Closes #34259 from MaxGekk/ansi-intervals-error-stored-as.

Authored-by: Max Gekk <max.gekk@gmail.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>