[SPARK-37512][PYTHON] Support TimedeltaIndex creation (from Series/Index) and TimedeltaIndex.astype
### What changes were proposed in this pull request?
Support TimedeltaIndex creation given a timedelta Series/Index.

`astype` is also supported naturally in this PR.

### Why are the changes needed?
Follow panda's behavior.

### Does this PR introduce _any_ user-facing change?
Yes.

#### TimedeltaIndex creation (from Series/Index)
```py
>>> idx = ps.TimedeltaIndex([timedelta(1), timedelta(microseconds=2)])
>>> s = ps.Series([timedelta(1), timedelta(microseconds=2)], index=[10, 20])

## FROM ##
>>> ps.TimedeltaIndex(idx)
Traceback (most recent call last):
...
NotImplementedError: Create a TimedeltaIndex from Index/Series is not supported

>>> ps.TimedeltaIndex(s)
Traceback (most recent call last):
...
NotImplementedError: Create a TimedeltaIndex from Index/Series is not supported

## TO ##
>>> ps.TimedeltaIndex(idx)
TimedeltaIndex(['1 days 00:00:00', '0 days 00:00:00.000002'], dtype='timedelta64[ns]', freq=None)

>>> ps.TimedeltaIndex(s)
TimedeltaIndex(['1 days 00:00:00', '0 days 00:00:00.000002'], dtype='timedelta64[ns]', freq=None)

```
#### TimedeltaIndex.astype
```py
>>> psidx = ps.TimedeltaIndex([timedelta(1)])
>>> psidx.astype(str)
Index(['INTERVAL '1 00:00:00' DAY TO SECOND'], dtype='object')
>>> psidx.astype(int)
Int64Index([86400], dtype='int64')
>>> psidx.astype('category')
CategoricalIndex(['1 days'], categories=[1 days 00:00:00], ordered=False, dtype='category')
```

### How was this patch tested?
Unit tests.

Closes #34776 from xinrong-databricks/timedeltaCreate.

Authored-by: Xinrong Meng <xinrong.meng@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>