[SPARK-39432][SQL] Return ELEMENT_AT_BY_INDEX_ZERO from element_at(*, 0)
## What changes were proposed in this pull request?
SELECT element_at(array('a', 'b', 'c'), index) FROM VALUES(0), (2) AS T(index);
This should roll into ELEMENT_AT_BY_INDEX_ZERO.

### Why are the changes needed?
element_at(*, 0) should return ELEMENT_AT_BY_INDEX_ZERO to unify errors representation for users.

### Does this PR introduce any user-facing change?
Yes, it changes an user-facing error message.

### How was this patch tested?
Add new UT & By running manual test:
```scala
> sql("SELECT element_at(array('a', 'b', 'c'), index) FROM VALUES(0), (2) AS T(index)").collect()
```
throws error:
```
19:20:13.012 ERROR org.apache.spark.executor.Executor: Exception in task 0.0 in stage 0.0 (TID 0)
org.apache.spark.SparkRuntimeException: [ELEMENT_AT_BY_INDEX_ZERO] The index 0 is invalid. The indexes can be < 0 and > 0 (the first element has index 1).
	at org.apache.spark.sql.errors.QueryExecutionErrors$.elementAtByIndexZeroError(QueryExecutionErrors.scala:1203)
	at org.apache.spark.sql.errors.QueryExecutionErrors.elementAtByIndexZeroError(QueryExecutionErrors.scala)
...
```

Closes #36855 from panbingkun/SPARK-39432.

Authored-by: panbingkun <pbk1982@gmail.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>