[SPARK-37941][SQL] Use error classes in the compilation errors of casting
### What changes were proposed in this pull request?
Migrate the following errors in QueryCompilationErrors onto use error classes:
1. upCastFailureError => CANNOT_UP_CAST_DATATYPE
2. unsupportedAbstractDataTypeForUpCastError => UNSUPPORTED_FEATURE
3. cannotUpCastAsAttributeError => removed as no longer used.

### Why are the changes needed?
Porting casting errors to new error framework.

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
New UT added.

Closes #35366 from ivoson/SPARK-37941-new.

Authored-by: Tengfei Huang <tengfei.h@gmail.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>