Revert "[SPARK-47702][CORE] Remove Shuffle service endpoint from the locations list when RDD block is removed form a node"
### What changes were proposed in this pull request?
This reverts commit ec281547eed4cee1dab2b777b4a03c764bd15b54.

### Why are the changes needed?
branch-3.5 cannot be compiled successfully with commit ec281547eed4cee1dab2b777b4a03c764bd15b54

```
[error] /home/runner/work/spark/spark/core/src/test/scala/org/apache/spark/storage/BlockManagerReplicationSuite.scala:304:23: value TEST_SKIP_ESS_REGISTER is not a member of object org.apache.spark.internal.config.Tests
[error]     newConf.set(Tests.TEST_SKIP_ESS_REGISTER, true)
[error]                       ^
[error] one error found
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Pass GItHub Actions

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #48353 from LuciferYang/Revert-SPARK-47702.

Authored-by: yangjie01 <yangjie01@baidu.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>