[SPARK-38363][SQL] Avoid runtime error in Dataset.summary()/Dataset.describe() when ANSI mode is on
### What changes were proposed in this pull request?

When executing `df.summary()` or `df.describe()`, Spark SQL converts String columns as Double for the
 percentiles/mean/stddev stats.
```
scala> val person2: DataFrame = Seq(
     |     ("Bob", 16, 176),
     |     ("Alice", 32, 164),
     |     ("David", 60, 192),
     |     ("Amy", 24, 180)).toDF("name", "age", "height")

scala> person2.summary().show()
+-------+-----+------------------+------------------+
|summary| name|               age|            height|
+-------+-----+------------------+------------------+
|  count|    4|                 4|                 4|
|   mean| null|              33.0|             178.0|
| stddev| null|19.148542155126762|11.547005383792515|
|    min|Alice|                16|               164|
|    25%| null|                16|               164|
|    50%| null|                24|               176|
|    75%| null|                32|               180|
|    max|David|                60|               192|
+-------+-----+------------------+------------------+
```

This can cause runtime errors with ANSI mode on.
```
org.apache.spark.SparkNumberFormatException: invalid input syntax for type numeric: Bob
```
This PR is to fix it by using `TryCast` for String columns.

### Why are the changes needed?

For better adoption of the ANSI mode. Since both APIs are for getting a quick summary of the Dataframe, I suggest using `TryCast` for the problematic stats so that both APIs still work under ANSI mode.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

UT

Closes #35699 from gengliangwang/fixSummary.

Authored-by: Gengliang Wang <gengliang@apache.org>
Signed-off-by: Gengliang Wang <gengliang@apache.org>
(cherry picked from commit 80f25ad24a871f0ddef939f6a3e2f01370f1fa6f)
Signed-off-by: Gengliang Wang <gengliang@apache.org>