[SPARK-52721][PYTHON] Fix message parameter for CANNOT_PARSE_DATATYPE
Fix message parameter for CANNOT_PARSE_DATATYPE

bugfix

No

- Before
AssertionError: Undefined error message parameter for error class: CANNOT_PARSE_DATATYPE. Parameters: {'error':

- After
pyspark.errors.exceptions.base.PySparkValueError: [CANNOT_PARSE_DATATYPE] Unable to parse datatype.

no

Closes #51414 from yaooqinn/SPARK-52721.

Authored-by: Kent Yao <yao@apache.org>
Signed-off-by: Kent Yao <yao@apache.org>
(cherry picked from commit c6e864538e2d8e3c816ba0f0a7bb9e212adc0a9d)
Signed-off-by: Kent Yao <yao@apache.org>