[SPARK-42668][SS][FOLLOW-UP] Do not add file scheme to the Windows path
### What changes were proposed in this pull request?

This PR is a followup of https://github.com/apache/spark/pull/40273 that avoids adding `file://` into Windows path.

### Why are the changes needed?

To fix the broken AppVeyor build

```
== Failed ======================================================================
-- 1. Error ('test_streaming.R:55'): read.stream, write.stream, awaitTermination
Error: Error in start : org.apache.hadoop.HadoopIllegalArgumentException: Unsupported name: has scheme but relative path-part
...
```

See also https://ci.appveyor.com/project/ApacheSoftwareFoundation/spark/builds/46451196

### Does this PR introduce _any_ user-facing change?

No to end users because the change has not been released out yet.

### How was this patch tested?

AppVeyor build on windows.

Closes #41098 from HyukjinKwon/appveyor-testing.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Jungtaek Lim <kabhwan.opensource@gmail.com>