[SPARK-39445][SQL] Remove the window if windowExpressions is empty in column pruning
### What changes were proposed in this pull request?

This PR removes the window if windowExpressions is empty in column pruning.

### Why are the changes needed?

It will throw exception if user `set spark.sql.optimizer.excludedRules=org.apache.spark.sql.catalyst.optimizer.RemoveNoopOperators` before running this query:
```sql
SELECT id
FROM   (SELECT id,
               Row_number()
                 OVER (
                   partition BY id
                   ORDER BY id) AS rn
        FROM   Range(3)) t
```
Exception:
```
org.apache.spark.sql.AnalysisException: Window expression is empty in Window [id#11L], [id#11L ASC NULLS FIRST]
+- Project [id#11L]
   +- Range (0, 5, step=1, splits=None)
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Unit test.

Closes #36842 from wangyum/SPARK-39445.

Authored-by: Yuming Wang <yumwang@ebay.com>
Signed-off-by: Yuming Wang <yumwang@ebay.com>