[SPARK-39895][SQL][PYTHON] Support multiple column drop
### What changes were proposed in this pull request?
Pyspark dataframe drop has following signature:
`def drop(self, *cols: "ColumnOrName") -> "DataFrame":`

However when we try to pass multiple Column types to drop function it raises TypeError

`each col in the param list should be a string`

*Minimal reproducible example:*
```python
values = [("id_1", 5, 9), ("id_2", 5, 1), ("id_3", 4, 3), ("id_1", 3, 3), ("id_2", 4, 3)]
df = spark.createDataFrame(values, "id string, point int, count int")
df.drop(df.point, df.count)
```

It spits out following:
```
/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py in drop(self, *cols)
2537 for col in cols:
2538 if not isinstance(col, str):
-> 2539 raise TypeError("each col in the param list should be a string")
2540 jdf = self._jdf.drop(self._jseq(cols))
2541

TypeError: each col in the param list should be a string
```

### Why are the changes needed?
We expect that multiple columns can be handled by drop call on df because of its typing but that is not the case.

### Does this PR introduce _any_ user-facing change?
Yes, fixes issues related type confirmation in pyspark api

### How was this patch tested?
Added missing tests for regression testing. CI Pipeline on fork and CI here will test them.

Closes #37335 from santosh-d3vpl3x/master.

Lead-authored-by: Santosh Pingale <pingalesantosh@gmail.com>
Co-authored-by: Hyukjin Kwon <gurwls223@gmail.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>