[SPARK-44477][SQL] Treat TYPE_CHECK_FAILURE_WITH_HINT as an error subclass
### What changes were proposed in this pull request?

In `CheckAnalysis#checkAnalysis0`, qualify the error subclass `TYPE_CHECK_FAILURE_WITH_HINT` with the error class `DATATYPE_MISMATCH`.

### Why are the changes needed?

`CheckAnalysis` treats `TYPE_CHECK_FAILURE_WITH_HINT` as an error class, but it is actually an error subclass of `DATATYPE_MISMATCH`.
```
spark-sql (default)> select bitmap_count(12);
[INTERNAL_ERROR] Cannot find main error class 'TYPE_CHECK_FAILURE_WITH_HINT'
org.apache.spark.SparkException: [INTERNAL_ERROR] Cannot find main error class 'TYPE_CHECK_FAILURE_WITH_HINT'
	at org.apache.spark.SparkException$.internalError(SparkException.scala:83)
	at org.apache.spark.SparkException$.internalError(SparkException.scala:87)
	at org.apache.spark.ErrorClassesJsonReader.$anonfun$getMessageTemplate$1(ErrorClassesJSONReader.scala:68)
	at scala.collection.immutable.HashMap$HashMap1.getOrElse0(HashMap.scala:361)
	at scala.collection.immutable.HashMap$HashTrieMap.getOrElse0(HashMap.scala:594)
	at scala.collection.immutable.HashMap$HashTrieMap.getOrElse0(HashMap.scala:589)
	at scala.collection.immutable.HashMap.getOrElse(HashMap.scala:73)
```
This issue only occurs when an expression uses `TypeCheckResult.TypeCheckFailure` to indicate input type check failure. `TypeCheckResult.TypeCheckFailure` appears to be deprecated in favor of `TypeCheckResult.DataTypeMismatch`, but recently two expressions were added that use `TypeCheckResult.TypeCheckFailure`: `BitmapCount` and `BitmapOrAgg`.

`BitmapCount` and `BitmapOrAgg` should probably be fixed to use `TypeCheckResult.DataTypeMismatch`. Regardless, the code in `CheckAnalysis` that handles `TypeCheckResult.TypeCheckFailure` should either be fixed or removed. In this PR, I chose to fix it.

### Does this PR introduce _any_ user-facing change?

No, except for the user seeing the correct error message.

### How was this patch tested?

New unit test.

Closes #42064 from bersprockets/type_check_issue.

Authored-by: Bruce Robbins <bersprockets@gmail.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>
(cherry picked from commit 9619ada35059faf601ebefd5c225ae1ebf86f5ef)
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>