[SPARK-42983][CONNECT][PYTHON] Fix createDataFrame to handle 0-dim numpy array properly
### What changes were proposed in this pull request?

Fix `createDataFrame` to handle 0-dim numpy array properly.

### Why are the changes needed?

When 0-dim numpy array is passed to `createDataFrame`, it raises an unexpected error:

```py
>>> import numpy as np
>>> spark.createDataFrame(np.array(0))
Traceback (most recent call last):
...
TypeError: len() of unsized object
```

The error message should be:

```py
ValueError: NumPy array input should be of 1 or 2 dimensions.
```

### Does this PR introduce _any_ user-facing change?

It will show a proper error message.

### How was this patch tested?

Enabled/updated the related test.

Closes #40669 from ueshin/issues/SPARK-42983/zero_dim_nparray.

Authored-by: Takuya UESHIN <ueshin@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>