[SPARK-46666][PYTHON][TESTS] Make lxml as an optional testing dependency in test_session
### What changes were proposed in this pull request?

This PR proposes to make `lxml` as an optional testing dependency in the `test_session` test

### Why are the changes needed?

To make the tests pass without optional testing dependencies, see https://github.com/apache/spark/actions/runs/7476792796/job/20348097114

```
Starting test(python3.12): pyspark.sql.tests.test_session (temp output: /__w/spark/spark/python/target/5136bb6a-ba9d-4533-925c-adf338021fa0/python3.12__pyspark.sql.tests.test_session__yahhd4j3.log)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/__w/spark/spark/python/pyspark/sql/tests/test_session.py", line 22, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'

```

### Does this PR introduce _any_ user-facing change?

No, test-only.

### How was this patch tested?

Manaully.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #44676 from HyukjinKwon/SPARK-46666.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>