[SPARK-25509][CORE] Windows doesn't support POSIX permissions
SHS V2 cannot enabled in Windows, because windows doesn't support POSIX permission.

test case fails in windows without this fix.
org.apache.spark.deploy.history.HistoryServerDiskManagerSuite  test("leasing space")

SHS V2  cannot run successfully in Windows without this fix.

java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
  at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(WindowsSecurityDescriptor.java:358)

Closes #22520 from jianjianjiao/FixWindowsPermssionsIssue.

Authored-by: Rong Tang <rotang@microsoft.com>
Signed-off-by: Sean Owen <sean.owen@databricks.com>
(cherry picked from commit a2ac5a72ccd2b14c8492d4a6da9e8b30f0f3c9b4)
Signed-off-by: Sean Owen <sean.owen@databricks.com>