[SPARK-42679][CONNECT][PYTHON] createDataFrame doesn't work with non-nullable schema
### What changes were proposed in this pull request?

Fixes `spark.createDataFrame` to apply the given schema to work with non-nullable data types.

### Why are the changes needed?

Currently `spark.createDataFrame` won't work with non-nullable schema as below:

```py
>>> from pyspark.sql.types import *
>>> schema_false = StructType([StructField("id", IntegerType(), False)])
>>> spark.createDataFrame([[1]], schema=schema_false)
Traceback (most recent call last):
...
pyspark.errors.exceptions.connect.AnalysisException: [NULLABLE_COLUMN_OR_FIELD] Column or field `id` is nullable while it's required to be non-nullable.
```

whereas it works fine with nullable schema:

```py
>>> from pyspark.sql.types import *
>>> schema_false = StructType([StructField("id", IntegerType(), False)])
>>> spark.createDataFrame([[1]], schema=schema_false)
DataFrame[id: int]
```

### Does this PR introduce _any_ user-facing change?

`spark.createDataFrame` with non-nullable schema will work.

### How was this patch tested?

Added related tests.

Closes #40382 from ueshin/issues/SPARK-42679/non-nullable.

Lead-authored-by: panbingkun <pbk1982@gmail.com>
Co-authored-by: Takuya UESHIN <ueshin@databricks.com>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>
(cherry picked from commit fa5ca7fe87290c81ccd2ba214c8478beefe0c5ec)
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>