[SPARK-39374][SQL] Improve error message for user specified column list
### What changes were proposed in this pull request?

This PR improves error message for user specified column list. For example:
```sql
create table t1(c1 int, c2 bigint, c3 string) using parquet;
insert into t1(c1, c2, c4) values(1, 2, 3);
```
Before this PR:
```
Cannot resolve column name c4; line 1 pos 0
org.apache.spark.sql.AnalysisException: Cannot resolve column name c4; line 1 pos 0
```
After this PR:
```
[MISSING_COLUMN] Column 'c4' does not exist. Did you mean one of the following? [c1, c2, c3]; line 1 pos 0
org.apache.spark.sql.AnalysisException: [MISSING_COLUMN] Column 'c4' does not exist. Did you mean one of the following? [c1, c2, c3]; line 1 pos 0
```

### Why are the changes needed?

Improve error message.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Existing test.

Closes #36760 from wangyum/SPARK-39374.

Authored-by: Yuming Wang <yumwang@ebay.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>