[SPARK-45088][PYTHON][CONNECT] Make `getitem` work with duplicated columns
### What changes were proposed in this pull request?

- Make `getitem` work with duplicated columns
- ~~Disallow bool type index~~
- ~~Disallow negative index~~

### Why are the changes needed?
1, SQL feature OrderBy ordinal works with duplicated columns
```
In [4]: df = spark.sql("SELECT * FROM VALUES (1, 1.1, 'a'), (2, 2.2, 'b'), (4, 4.4, 'c') AS TAB(a, a, a)")

In [5]: df.createOrReplaceTempView("v")

In [6]: spark.sql("SELECT * FROM v ORDER BY 1, 2").show()
+---+---+---+
|  a|  a|  a|
+---+---+---+
|  1|1.1|  a|
|  2|2.2|  b|
|  4|4.4|  c|
+---+---+---+
```

To support it in DataFame APIs, we need to make `getitem` work with duplicated columns

~~2 & 3: should be unintentional~~

### Does this PR introduce _any_ user-facing change?
YES

1, Make `getitem` work with duplicated columns
before
```
In [1]: df = spark.sql("SELECT * FROM VALUES (1, 1.1, 'a'), (2, 2.2, 'b'), (4, 4.4, 'c') AS TAB(a, a, a)")

In [2]: df[0]
---------------------------------------------------------------------------
AnalysisException                         Traceback (most recent call last)
Cell In[2], line 1
----> 1 df[0]
...

AnalysisException: [AMBIGUOUS_REFERENCE] Reference `a` is ambiguous, could be: [`TAB`.`a`, `TAB`.`a`, `TAB`.`a`].

In [3]: df[1]
---------------------------------------------------------------------------
AnalysisException                         Traceback (most recent call last)
...

AnalysisException: [AMBIGUOUS_REFERENCE] Reference `a` is ambiguous, could be: [`TAB`.`a`, `TAB`.`a`, `TAB`.`a`].

In [4]: df.orderBy(1, 2).show()
---------------------------------------------------------------------------
AnalysisException                         Traceback (most recent call last)
Cell In[7], line 1
----> 1 df.orderBy(1, 2).show()

...

AnalysisException: [AMBIGUOUS_REFERENCE] Reference `a` is ambiguous, could be: [`TAB`.`a`, `TAB`.`a`, `TAB`.`a`].

```

after

```
In [1]: df = spark.sql("SELECT * FROM VALUES (1, 1.1, 'a'), (2, 2.2, 'b'), (4, 4.4, 'c') AS TAB(a, a, a)")

In [2]: df[0]
Out[2]: Column<'a'>

In [3]: df[1]
Out[3]: Column<'a'>

In [4]: df.orderBy(1, 2).show()
+---+---+---+
|  a|  a|  a|
+---+---+---+
|  1|1.1|  a|
|  2|2.2|  b|
|  4|4.4|  c|
+---+---+---+
```

### How was this patch tested?
added UTs

### Was this patch authored or co-authored using generative AI tooling?
NO

Closes #42828 from zhengruifeng/col_by_index.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>