[SPARK-50094][PYTHON][CONNECT] Better error message when using memory profiler on editors with no line numbers
### What changes were proposed in this pull request?
Better error message when using memory profiler on editors with no line numbers.

memory-profiler requires line numbers to function properly, the proposed error message directly communicates that requirement.

### Why are the changes needed?
Improve user experience and clarity in debugging.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Existing tests and mantual test:
```py
>>> from pyspark.sql.functions import pandas_udf
>>> df = spark.range(10)
>>> pandas_udf("long")
... def add1(x):
...   return x + 1
...
>>> spark.conf.set("spark.sql.pyspark.udf.profiler", "memory")
>>> added = df.select(add1("id"))
>>> spark.profile.show(type="memory")
...
pyspark.errors.exceptions.base.PySparkValueError: [MEMORY_PROFILE_INVALID_SOURCE] Memory profiler can only be used on editors with line numbers.
```

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #48634 from xinrong-meng/err_memory_profile.

Authored-by: Xinrong Meng <xinrong@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>