[SPARK-42655][SQL] Incorrect ambiguous column reference error
**What changes were proposed in this pull request?**
The result of attribute resolution should consider only unique values for the reference. If it has duplicate values, it will incorrectly result into ambiguous reference error.

**Why are the changes needed?**
The below query fails incorrectly due to ambiguous reference error.
val df1 = sc.parallelize(List((1,2,3,4,5),(1,2,3,4,5))).toDF("id","col2","col3","col4", "col5")
val op_cols_mixed_case = List("id","col2","col3","col4", "col5", "ID")
val df3 = df1.select(op_cols_mixed_case.head, op_cols_mixed_case.tail: _*)
df3.select("id").show()
org.apache.spark.sql.AnalysisException: Reference 'id' is ambiguous, could be: id, id.

df3.explain()
== Physical Plan ==
*(1) Project [_1#6 AS id#17, _2#7 AS col2#18, _3#8 AS col3#19, _4#9 AS col4#20, _5#10 AS col5#21, _1#6 AS ID#17]

Before the fix, attributes matched were:
attributes: Vector(id#17, id#17)
Thus, it throws ambiguous reference error. But if we consider only unique matches, it will return correct result.
unique attributes: Vector(id#17)

**Does this PR introduce any user-facing change?**
Yes, Users migrating from Spark 2.3 to 3.x will face this error as the scenario used to work fine in Spark 2.3 but fails in Spark 3.2. After the fix, iit will work correctly as it was in Spark 2.3.

**How was this patch tested?**
Added unit test.

Closes #40258 from shrprasa/col_ambiguous_issue.

Authored-by: Shrikant Prasad <shrprasa@visa.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>
(cherry picked from commit b283c6a0e47c3292dbf00400392b3a3f629dd965)
Signed-off-by: Wenchen Fan <wenchen@databricks.com>