Fix failing backport packages test (#13497)
In #13473 - I updated the deprecated packages but looks like it broke backport packages:

```
    File "/usr/local/lib/python3.6/site-packages/airflow/providers/google/cloud/example_dags/example_tasks.py", line 32, in <module>
      from airflow.models.baseoperator import chain
  ImportError: cannot import name 'chain'
```