[SPARK-37495][PYTHON] Skip identical index checking of Series.compare when config 'compute.eager_check' is disabled
### What changes were proposed in this pull request?
Skip identical index checking of Series.compare when config 'compute.eager_check' is disabled

### Why are the changes needed?
Identical index checking is expensive, so we should use config 'compute.eager_check' to skip this one

### Does this PR introduce _any_ user-facing change?
Yes

Before this PR
```python
>>> psser1 = ps.Series([1, 2, 3, 4, 5], index=pd.Index([1, 2, 3, 4, 5]))
>>> psser2 = ps.Series([1, 2, 3, 4, 5], index=pd.Index([1, 2, 4, 3, 6]))
>>> psser1.compare(psser2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u02/spark/python/pyspark/pandas/series.py", line 5851, in compare
    raise ValueError("Can only compare identically-labeled Series objects")
ValueError: Can only compare identically-labeled Series objects
```
After this PR, when config 'compute.eager_check' is False, pandas-on-Spark just proceeds and performs by ignoring the identical index checking.
```python
>>> with ps.option_context("compute.eager_check", False):
...     psser1.compare(psser2)
...
   self  other
3   3.0    4.0
4   4.0    3.0
5   5.0    NaN
6   NaN    5.0
```
### How was this patch tested?
Unit tests

Closes #34750 from dchvn/SPARK-37495.

Authored-by: dch nguyen <dgd_contributor@viettel.com.vn>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>