[SPARK-52959][PYTHON] Support UDT in Arrow-optimized Python UDTF
### What changes were proposed in this pull request?

Supports UDT in Arrow-optimized Python UDTF.

### Why are the changes needed?

Arrow-optimized Python UDTF doesn't work with UDTs.

```py
>>> udtf(returnType=StructType().add("point", ExamplePointUDT()), useArrow=True)
... class TestUDTFReturningUDT:
...   def eval(self, x: float, y: float):
...     yield ExamplePoint(x=x, y=y)
...
>>> df = spark.createDataFrame([(ExamplePoint(x=1.0, y=2.0),)], schema=StructType().add("point", ExamplePointUDT()))
>>> df.lateralJoin(TestUDTFTakingUDT(col("point").outer())).show()
...
AttributeError: 'list' object has no attribute 'x'

>>> udtf(returnType=StructType().add("point", ExamplePointUDT()), useArrow=True)
... class TestUDTFReturningUDT:
...   def eval(self, x: float, y: float):
...     yield ExamplePoint(x=x, y=y),
...
>>> df = spark.range(2).select((col("id") + 10.0).alias("x"), (col("id") * 10.0).alias("y"))
>>> df.lateralJoin(TestUDTFReturningUDT(col("x").outer(), col("y").outer())).show()
...
org.apache.spark.SparkException: [ARROW_TYPE_MISMATCH] Invalid schema from Python UDTF: expected org.apache.spark.sql.test.ExamplePointUDT7f511308, got ArrayType(DoubleType,false). SQLSTATE: 42K0G
```

### Does this PR introduce _any_ user-facing change?

Yes, UDTs are available as input / output for Arrow-optimized Python UDTF.

### How was this patch tested?

Added the related tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #51694 from ueshin/issues/SPARK-52959/udtf_udt.

Authored-by: Takuya Ueshin <ueshin@databricks.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>