[SPARK-36227][SQL][FOLLOWUP][3.2] Remove unused import in TimestampNTZType.scala
### What changes were proposed in this pull request?

This is a follow-up of https://github.com/apache/spark/pull/33837
It is to fix compilation error: https://github.com/apache/spark/runs/3431646840

### Why are the changes needed?

Fix a compilation error

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Pass existing UTs

Closes #33851 from gengliangwang/fixCompile.

Authored-by: Gengliang Wang <gengliang@apache.org>
Signed-off-by: Gengliang Wang <gengliang@apache.org>