[SPARK-37436][PYTHON] Uses Python's standard string formatter for SQL API in pandas API on Spark
### What changes were proposed in this pull request?

This PR proposes to use [Python's standard string formatter](https://docs.python.org/3/library/string.html#custom-string-formatting) instead of hacky custom SQL parser for SQL API in pandas API on Spark

### Why are the changes needed?

Current implementation of parsing is very hacky, and does not work. It is [dependent on Python's internal module](https://github.com/apache/spark/blob/master/python/pyspark/pandas/sql_processor.py#L291), and [Series is being treated as a table](https://github.com/apache/spark/blob/master/python/pyspark/pandas/sql_processor.py#L339-L340), etc.

We should have the Python standard string formatter with the standard interface and the standard support.

### Does this PR introduce _any_ user-facing change?

Yes.

**Disallowed:**

1. `Series` as a table

    ```python
    myser = ps.Series({'a': [1.0, 2.0, 3.0], 'b': [15.0, 30.0, 45.0]})
    ps.sql("SELECT * from {myser}", myser=myser)
    ```

2. `list` and `range`

    ```python
    strs = ['a', 'b']
    ps.sql("SELECT 'a' IN {strs}", strs=strs)
    ```

3. Automatic local/global variable detection:

    ```python
    strs = ['a', 'b']
    ps.sql("SELECT 'a' IN {strs}")
    ```

**Allowed:**

1. `Series` as a column

    ```python
    mydf = ps.range(10)
    ps.sql("SELECT {ser} FROM {mydf}", ser=mydf.id, mydf=mydf)
    ```

2. Reference checking (between `Series` and `DataFrame`)

    ```python
    mydf = ps.range(10)
    ps.sql("SELECT {ser} FROM tblA", ser=mydf.id)
    ```

    ```
    ValueError: The series in {ser} does not refer any dataframe specified.
    ```

3. Attribute supports from frame (standard Python support):

    ```python
    mydf = ps.range(10)
    ps.sql("SELECT {tbl.id} FROM {tbl}", tbl=mydf)
    ```

### How was this patch tested?

Doctests were added.

Closes #34677 from HyukjinKwon/custom-formatter.

Authored-by: Hyukjin Kwon <gurwls223@apache.org>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>