[SPARK-37069][SQL] Properly fallback when Hive.getWithoutRegisterFns is not available
### What changes were proposed in this pull request?

Properly fallback to `Hive.get` when `Hive.getWithoutRegisterFns` is unavailable to a Hive version.

### Does this PR introduce _any_ user-facing change?

In SPARK-35321 we switched to use the new method `Hive.getWithoutRegisterFns` introduced by [HIVE-21563](https://issues.apache.org/jira/browse/HIVE-21563). The code path is supposed to only active for Hive versions that are >= 2.3.9. However, due to how `HiveVersion` is initialized in `IsolatedClientLoader`, if users set `spark.sql.hive.metastore.version` to `2.3.8`, Spark will still convert it to "2.3.9" and thus will subsequently fail with `NoSuchMethodError`.

This fixes it by always fallback on `NoSuchMethodError`. By doing this we are also able to support other Hive versions with `Hive.getWithoutRegisterFns` implemented.

### How was this patch tested?

I manually tested via launching a Spark session with custom Hive version:

```
$SPARK_HOME/bin/spark-shell --conf spark.sql.hive.metastore.version=2.3.8 --conf spark.sql.hive.metastore.jars="/tmp/apache-hive-2.3.8-bin/lib/*
```

And then tried this command:
```
import org.apache.spark.sql.SparkSession
val spark = SparkSession.builder()
  .master("local[*]")
  .enableHiveSupport()
  .config("spark.sql.hive.metastore.version", "2.3.8")
  .config("spark.sql.hive.metastore.jars", "/tmp/apache-hive-2.3.8-bin/lib/*")
  .getOrCreate()
spark.sql("show tables").show
```

The command is failing before this PR, but working afterwards.

Closes #34360 from sunchao/SPARK-37069.

Authored-by: Chao Sun <sunchao@apple.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>