[SPARK-42022][CONNECT][PYTHON] Fix createDataFrame to autogenerate missing column names
### What changes were proposed in this pull request?

Fixes `createDataFrame` to autogenerate missing column names.

### Why are the changes needed?

Currently the number of the column names specified to `createDataFrame` does not match the actual number of columns, it raises an error:

```py
>>> spark.createDataFrame([["a", "b"]], ["col1"])
Traceback (most recent call last):
...
ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements
```

but it should auto-generate the missing column names.

### Does this PR introduce _any_ user-facing change?

It will auto-generate the missing columns:

```py
>>> spark.createDataFrame([["a", "b"]], ["col1"])
DataFrame[col1: string, _2: string]
```

### How was this patch tested?

Enabled the related test.

Closes #40310 from ueshin/issues/SPARK-42022/columns.

Authored-by: Takuya UESHIN <ueshin@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>