[SPARK-44520][SQL] Replace the term UNSUPPORTED_DATA_SOURCE_FOR_DIRECT_QUERY with UNSUPPORTED_DATASOURCE_FOR_DIRECT_QUERY and disclosure root AE
### What changes were proposed in this pull request?

1. UNSUPPORTED_DATA_SOURCE_FOR_DIRECT_QUERY is duplicated with UNSUPPORTED_DATASOURCE_FOR_DIRECT_QUERY. This PR uses the shorter one.

2. Bugfix for hiding root AE from UNSUPPORTED_DATASOURCE_FOR_DIRECT_QUERY

### Why are the changes needed?

UNSUPPORTED_DATA_SOURCE_FOR_DIRECT_QUERY is duplicated.

Bugfix for hiding root AE from UNSUPPORTED_DATASOURCE_FOR_DIRECT_QUERY

For example,

```scala
 select id from parquet.`abc`;

[UNSUPPORTED_DATASOURCE_FOR_DIRECT_QUERY] Unsupported data source type for direct query on files: parquet; line 1 pos 15
org.apache.spark.sql.AnalysisException: [UNSUPPORTED_DATASOURCE_FOR_DIRECT_QUERY] Unsupported data source type for direct query on files: parquet; line 1 pos 15
```

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

existing tests

Closes #42124 from yaooqinn/SPARK-44520.

Authored-by: Kent Yao <yao@apache.org>
Signed-off-by: Kent Yao <yao@apache.org>