[SPARK-45137][CONNECT] Support map/array parameters in parameterized `sql()`
### What changes were proposed in this pull request?
In the PR, I propose to extend the proto protocol, and add two more fields to `SqlCommand`: `arguments` and `pos_arguments`. This should allow to construct arrays/maps/structs by the `map()`, `array()`, `struct()`, `map_from_arrays()` and `map_from_entries()`, and pass them to `sql()` as arguments.

### Why are the changes needed?
To fix the issue demonstrated by the example:
```scala
spark.sql("select element_at(?, 1)", Array(array(lit(1)))).collect()
java.lang.UnsupportedOperationException: literal unresolved_function {
[info]   function_name: "array"
[info]   arguments {
[info]     literal {
[info]       integer: 1
[info]     }
[info]   }
[info] }
[info]  not supported (yet).
```

Note: The PR https://github.com/apache/spark/pull/42752 supported constructors, and this PR extends the feature on Scala connect client.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
By new checks:
```
$ build/sbt -Phive-2.3 -Phive-thriftserver "test:testOnly *.ClientE2ETestSuite"
```

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #42931 from MaxGekk/fix-parameterized-sql-connect-map.

Authored-by: Max Gekk <max.gekk@gmail.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>