[SPARK-43817][SPARK-43702][PYTHON] Support UserDefinedType in createDataFrame from pandas DataFrame and toPandas
### What changes were proposed in this pull request?

Support `UserDefinedType` in `createDataFrame` from pandas DataFrame and `toPandas`.

For the following schema and pandas DataFrame:

```py
schema = (
    StructType()
    .add("point", ExamplePointUDT())
    .add("struct", StructType().add("point", ExamplePointUDT()))
    .add("array", ArrayType(ExamplePointUDT()))
    .add("map", MapType(StringType(), ExamplePointUDT()))
)
data = [
    Row(
        ExamplePoint(1.0, 2.0),
        Row(ExamplePoint(3.0, 4.0)),
        [ExamplePoint(5.0, 6.0)],
        dict(point=ExamplePoint(7.0, 8.0)),
    )
]

df = spark.createDataFrame(data, schema)

pdf = pd.DataFrame.from_records(data, columns=schema.names)
```

##### `spark.createDataFrame()`

For all, return the same results:

```py
>>> spark.createDataFrame(pdf, schema).show(truncate=False)
+----------+------------+------------+---------------------+
|point     |struct      |array       |map                  |
+----------+------------+------------+---------------------+
|(1.0, 2.0)|{(3.0, 4.0)}|[(5.0, 6.0)]|{point -> (7.0, 8.0)}|
+----------+------------+------------+---------------------+
```

##### `df.toPandas()`

```py
>>> spark.conf.set('spark.sql.execution.pandas.structHandlingMode', 'row')
>>> df.toPandas()
       point        struct        array                   map
0  (1.0,2.0)  ((3.0,4.0),)  [(5.0,6.0)]  {'point': (7.0,8.0)}
```

### Why are the changes needed?

Currently `UserDefinedType` in `spark.createDataFrame()` with pandas DataFrame and `df.toPandas()` is not supported with Arrow enabled or in Spark Connect.

##### `spark.createDataFrame()`

Works without Arrow:

```py
>>> spark.createDataFrame(pdf, schema).show(truncate=False)
+----------+------------+------------+---------------------+
|point     |struct      |array       |map                  |
+----------+------------+------------+---------------------+
|(1.0, 2.0)|{(3.0, 4.0)}|[(5.0, 6.0)]|{point -> (7.0, 8.0)}|
+----------+------------+------------+---------------------+
```

, whereas:

- With Arrow:

Works with fallback:

```py
>>> spark.createDataFrame(pdf, schema).show(truncate=False)
/.../python/pyspark/sql/pandas/conversion.py:351: UserWarning: createDataFrame attempted Arrow optimization because 'spark.sql.execution.arrow.pyspark.enabled' is set to true; however, failed by the reason below:
  [UNSUPPORTED_DATA_TYPE_FOR_ARROW_CONVERSION] ExamplePointUDT() is not supported in conversion to Arrow.
Attempting non-optimization as 'spark.sql.execution.arrow.pyspark.fallback.enabled' is set to true.
  warn(msg)
+----------+------------+------------+---------------------+
|point     |struct      |array       |map                  |
+----------+------------+------------+---------------------+
|(1.0, 2.0)|{(3.0, 4.0)}|[(5.0, 6.0)]|{point -> (7.0, 8.0)}|
+----------+------------+------------+---------------------+
```

- Spark Connect

```py
>>> spark.createDataFrame(pdf, schema).show(truncate=False)
Traceback (most recent call last):
...
pyspark.errors.exceptions.base.PySparkTypeError: [UNSUPPORTED_DATA_TYPE_FOR_ARROW_CONVERSION] ExamplePointUDT() is not supported in conversion to Arrow.
```

##### `df.toPandas()`

Works without Arrow:

```py
>>> spark.conf.set('spark.sql.execution.pandas.structHandlingMode', 'row')
>>> df.toPandas()
       point        struct        array                   map
0  (1.0,2.0)  ((3.0,4.0),)  [(5.0,6.0)]  {'point': (7.0,8.0)}
```

, whereas:

- With Arrow

Works with fallback:

```py
>>> spark.conf.set('spark.sql.execution.pandas.structHandlingMode', 'row')
>>> df.toPandas()
/.../python/pyspark/sql/pandas/conversion.py:111: UserWarning: toPandas attempted Arrow optimization because 'spark.sql.execution.arrow.pyspark.enabled' is set to true; however, failed by the reason below:
  [UNSUPPORTED_DATA_TYPE_FOR_ARROW_CONVERSION] ExamplePointUDT() is not supported in conversion to Arrow.
Attempting non-optimization as 'spark.sql.execution.arrow.pyspark.fallback.enabled' is set to true.
  warn(msg)
       point        struct        array                   map
0  (1.0,2.0)  ((3.0,4.0),)  [(5.0,6.0)]  {'point': (7.0,8.0)}
```

- Spark Connect

Results with the internal type:

```py
>>> spark.conf.set('spark.sql.execution.pandas.structHandlingMode', 'row')
>>> df.toPandas()
        point         struct         array                    map
0  [1.0, 2.0]  ([3.0, 4.0],)  [[5.0, 6.0]]  {'point': [7.0, 8.0]}
```

### Does this PR introduce _any_ user-facing change?

Users will be able to use `UserDefinedType`.

### How was this patch tested?

Added the related tests.

Closes #41333 from ueshin/issues/SPARK-43817/udt.

Authored-by: Takuya UESHIN <ueshin@databricks.com>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>