[SPARK-53806][SQL] Allow empty input on AES decrypt to have error class
### What changes were proposed in this pull request?

also catch IllegalArgumentException for AES encrypt/decrypt expressions

### Why are the changes needed?

previously, if empty input is given to AES decrypt, it would return the error
```
IllegalArgumentException: Invalid buffer arguments
```

Now, with this change,
```
SparkRuntimeException: [INVALID_PARAMETER_VALUE.AES_KEY] The value of parameter(s) `expr`, `key` in `aes_encrypt`/`aes_decrypt` is invalid: detail message: Invalid buffer arguments
```

### Does this PR introduce _any_ user-facing change?

yes - see above. Error message change

### How was this patch tested?

added UT

### Was this patch authored or co-authored using generative AI tooling?

no

Closes #52523 from richardc-db/fix_error_class_in_aes_decrypt_empty_input.

Authored-by: Richard Chen <r.chen@databricks.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>