[SPARK-51920][SS][PYTHON][4.0] Fix composite/nested type in value state for python TWS
### What changes were proposed in this pull request?
Fix the bug in TransformWithStateInPandas in Python that it cannot handle composite/nested type in value state of python

### Why are the changes needed?
There are two issues in both Get side and Put side
In the **Put side**
Currently, all user provided state values are calling `_serialize_to_bytes` underneath to transmit user input object from state client to JVM. On Python worker, the user input state object is first serialized into Row type, and the pickler serialized the Row into Arrow Batch compatible format.

Issues happen if the user input schema for state schema contains composite type like ArrayType and MapType. `_serialize_to_bytes` is not able to parse StructType and serialize it into Row properly. This fix aims to fix `_serialize_to_bytes` so that it can handle recursive & composite user input types.

In the **Get side**
Current Pickler cannot handle Scala `ArraySeq` type so that it hit
```
25/08/08 16:47:30 ERROR TransformWithStateInPySparkStateServer: Error reading message: couldn't introspect javabean: java.lang.IllegalArgumentException: wrong number of arguments
net.razorvine.pickle.PickleException: couldn't introspect javabean: java.lang.IllegalArgumentException: wrong number of arguments
	at net.razorvine.pickle.Pickler.put_javabean(Pickler.java:833)
	at net.razorvine.pickle.Pickler.dispatch(Pickler.java:409)
	at net.razorvine.pickle.Pickler.save(Pickler.java:202)
	at org.apache.spark.sql.execution.python.EvaluatePython$RowPickler.pickle(EvaluatePython.scala:280)
```
This PR introduces a custom `IObjectPickler` for `ArraySeq` to ensure correct pickling and seamless deserialization on the Python side.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
UT

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #52066 from zeruibao/zeruibao/SPARK-51920-4-0-fix.

Authored-by: zeruibao <zerui.bao@databricks.com>
Signed-off-by: Jungtaek Lim <kabhwan.opensource@gmail.com>