[SPARK-56808][INFRA][3.5][FOLLOWUP] Pin get-pip.py to Python-version-specific URLs
`https://bootstrap.pypa.io/get-pip.py` now requires Python 3.10+:

    ERROR: This script does not work on Python 3.9.
    The minimum supported Python version is 3.10.
    Please use https://bootstrap.pypa.io/pip/3.9/get-pip.py instead.

Since branch-3.5 installs pip into python3.9 and pypy3.8, switch to the
version-pinned installers that pypa still maintains:

- python3.9 -> https://bootstrap.pypa.io/pip/3.9/get-pip.py
- pypy3 (3.8) -> https://bootstrap.pypa.io/pip/3.8/get-pip.py