[SPARK-54145][PYTHON][CONNECT] Fix column check of nested type in numeric aggregation
### What changes were proposed in this pull request?
Fix column check in numeric agg

### Why are the changes needed?
query:

```py
        df = spark.createDataFrame(
            [
                Row(a="a", b=Row(c=1)),
                Row(a="a", b=Row(c=2)),
                Row(a="a", b=Row(c=3)),
                Row(a="b", b=Row(c=4)),
                Row(a="b", b=Row(c=5)),
            ]
        )

        df.groupBy("a").max("b.c").show()
```

in classic:
```
+---+-------------+
|  a|max(b.c AS c)|
+---+-------------+
|  a|            3|
|  b|            5|
+---+-------------+
```

in connect:
```
---------------------------------------------------------------------------
PySparkTypeError                          Traceback (most recent call last)
Cell In[2], line 11
      1 df = spark.createDataFrame(
      2     [
      3         Row(a="a", b=Row(c=1)),
   (...)      8     ]
      9 )
---> 11 df.groupBy("a").max("b.c").show()

File ~/spark/python/pyspark/sql/connect/group.py:203, in GroupedData.max(self, *cols)
    202 def max(self: "GroupedData", *cols: str) -> "DataFrame":
--> 203     return self._numeric_agg("max", list(cols))

File ~/spark/python/pyspark/sql/connect/group.py:175, in GroupedData._numeric_agg(self, function, cols)
    173     invalid_cols = [c for c in cols if c not in numerical_cols]
    174     if len(invalid_cols) > 0:
--> 175         raise PySparkTypeError(
    176             errorClass="NOT_NUMERIC_COLUMNS",
    177             messageParameters={"invalid_columns": str(invalid_cols)},
    178         )
    179     agg_cols = cols
    180 else:
    181     # if no column is provided, then all numerical columns are selected

PySparkTypeError: [NOT_NUMERIC_COLUMNS] Numeric aggregation function can only be applied on numeric columns, got ['b.c'].

```

### Does this PR introduce _any_ user-facing change?
yes, above query works after this fix

### How was this patch tested?
added test

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #52844 from zhengruifeng/numeric_agg_nest_col.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
(cherry picked from commit 94e00ca8f5fcdc1d3c430e1b54de8012101f1d8d)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>