[SPARK-39261][CORE][FOLLOWUP] Improve newline formatting for error messages
### What changes were proposed in this pull request?
Use `java.nio.file.Files.delete` instead of `org.apache.commons.io.FileUtils#delete`

### Why are the changes needed?
`org.apache.commons.io.FileUtils#delete` is a method only available in version 2.9, hadoop2 uses version 2.4 of commons-io.

Build failed
```
./dev/make-distribution.sh --tgz -Pyarn -Phive -Phive-thriftserver -Phadoop-2 -DskipTests -Dmaven.javadoc.skip=true
```
```
spark/core/src/test/scala/org/apache/spark/SparkThrowableSuite.scala:92: value delete is not a member of object org.apache.commons.io.FileUtils
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
exist UT

Closes #36710 from cxzl25/SPARK-39261-FOLLOWUP.

Authored-by: sychen <sychen@ctrip.com>
Signed-off-by: Yuming Wang <yumwang@ebay.com>