[SPARK-36989][TESTS][PYTHON] Add type hints data tests
### What changes were proposed in this pull request?

This PR:

- Adds basic data test runner to `dev/lint-python`, using [`typeddjango/pytest-mypy-plugins`](https://github.com/typeddjango/pytest-mypy-plugins)
- Migrates data test cases from `pyspark-stubs`

In case of failure, a message similar to the following one

```
starting mypy annotations test...
annotations passed mypy checks.

starting mypy data test...
annotations failed data checks:
============================= test session starts ==============================
platform linux -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /path/to/spark/python, configfile: pyproject.toml
plugins: mypy-plugins-1.9.2
collected 37 items

python/pyspark/ml/tests/typing/test_classification.yml ..                [  5%]
python/pyspark/ml/tests/typing/test_evaluation.yml .                     [  8%]
python/pyspark/ml/tests/typing/test_feature.yml .                        [ 10%]
python/pyspark/ml/tests/typing/test_param.yml .                          [ 13%]
python/pyspark/ml/tests/typing/test_readable.yml .                       [ 16%]
python/pyspark/ml/tests/typing/test_regression.yml ..                    [ 21%]
python/pyspark/sql/tests/typing/test_column.yml F                        [ 24%]
python/pyspark/sql/tests/typing/test_dataframe.yml .......               [ 43%]
python/pyspark/sql/tests/typing/test_functions.yml .                     [ 45%]
python/pyspark/sql/tests/typing/test_pandas_compatibility.yml ..         [ 51%]
python/pyspark/sql/tests/typing/test_readwriter.yml ..                   [ 56%]
python/pyspark/sql/tests/typing/test_session.yml .....                   [ 70%]
python/pyspark/sql/tests/typing/test_udf.yml .......                     [ 89%]
python/pyspark/tests/typing/test_context.yml .                           [ 91%]
python/pyspark/tests/typing/test_core.yml .                              [ 94%]
python/pyspark/tests/typing/test_rdd.yml .                               [ 97%]
python/pyspark/tests/typing/test_resultiterable.yml .                    [100%]

=================================== FAILURES ===================================
______________________________ colDateTimeCompare ______________________________
/path/to/spark/python/pyspark/sql/tests/typing/test_column.yml:39:
E   pytest_mypy_plugins.utils.TypecheckAssertionError: Invalid output:
E   Actual:
E     main:20: note: Revealed type is "pyspark.sql.column.Column" (diff)
E   Expected:
E     main:20: note: Revealed type is "datetime.date*" (diff)
E   Alignment of first line difference:
E     E: ...ote: Revealed type is "datetime.date*"
E     A: ...ote: Revealed type is "pyspark.sql.column.Column"
E                                  ^
=========================== short test summary info ============================
FAILED python/pyspark/sql/tests/typing/test_column.yml::colDateTimeCompare -
======================== 1 failed, 36 passed in 56.13s =========================
```

will be displayed.

### Why are the changes needed?

Currently, type annotations are tested primarily for integrity and, to lesser extent, against actual API. Testing against examples is work in progress (SPARK-36997).  Data tests allow us to improve coverage and test negative cases (code, that should fail type checker validation).

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Running linter tests with additions proposed in this PR

Closes #34296 from zero323/SPARK-36989.

Authored-by: zero323 <mszymkiewicz@gmail.com>
Signed-off-by: zero323 <mszymkiewicz@gmail.com>