1. existing EmptyHashedRelation is an object and it will cause JavaDeserialization Exception as following
```
java.io.InvalidClassException: org.apache.spark.sql.execution.joins.EmptyHashedRelation$; no valid constructor
```

2. change EmptyHashedRelation not to extend NullAwareHashedRelation since it's already being used in other non-NAAJ joins

Change-Id: If54756558546906f00e1cf7496f52b60eb998645