Improve SparkConf typing
Right now SparkConf accepts any iterable, but the type annotation says
it only accepts list of tuples, so the following code works at runtime,
but fails in mypy:

```python
from pyspark.conf import SparkConf

d = {"a": "b"}
SparkConf().setAll(d.items())
```
mypy output:
```
tmp.py:4: error: Argument 1 to "setAll" of "SparkConf" has incompatible type "dict_items[str, str]"; expected "list[tuple[str, str]]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```