[SPARK-33189][FOLLOWUP][2.4] Fix syntax error in python/run-tests.py
### What changes were proposed in this pull request?

This PR aims to fix syntax error.

### Why are the changes needed?

```
========================================================================
Running Python style checks
========================================================================
pycodestyle checks failed.
*** Error compiling './python/run-tests.py'...
  File "./python/run-tests.py", line 80
    'PYARROW_IGNORE_TIMEZONE': '1',
                            ^
SyntaxError: invalid syntax
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Pass the Jenkins.

Closes #30124 from dongjoon-hyun/SPARK-33189.

Authored-by: Dongjoon Hyun <dhyun@apple.com>
Signed-off-by: HyukjinKwon <gurwls223@apache.org>