[SPARK-53500][PYTHON][TESTS] Make `test_unpivot` deterministic
### What changes were proposed in this pull request?
Make `test_unpivot` deterministic

### Why are the changes needed?
it occasionally fails with:
```
======================================================================
FAIL [0.000s]: test_unpivot (pyspark.sql.tests.connect.test_parity_stat.DataFrameStatParityTests.test_unpivot) (ids=[], desc='with no identifier')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/python/pyspark/sql/tests/test_stat.py", line 435, in test_unpivot
    self.assertEqual(
AssertionError: Lists differ: [Row([26 chars]var='int', val=20.0), Row(var='int', val=30.0)[80 chars]3.0)] != [Row([26 chars]var='double', val=1.0), Row(var='int', val=20.[80 chars]3.0)]
First differing element 1:
Row(var='int', val=20.0)
Row(var='double', val=1.0)
  [Row(var='int', val=10.0),
+  Row(var='double', val=1.0),
   Row(var='int', val=20.0),
+  Row(var='double', val=2.0),
   Row(var='int', val=30.0),
-  Row(var='double', val=1.0),
-  Row(var='double', val=2.0),
   Row(var='double', val=3.0)]
======================================================================
FAIL [0.000s]: test_unpivot (pyspark.sql.tests.connect.test_parity_stat.DataFrameStatParityTests.test_unpivot) (ids=(), desc='with no identifier')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jenkins/python/pyspark/sql/tests/test_stat.py", line 435, in test_unpivot
    self.assertEqual(
AssertionError: Lists differ: [Row([26 chars]var='int', val=20.0), Row(var='int', val=30.0)[80 chars]3.0)] != [Row([26 chars]var='double', val=1.0), Row(var='int', val=20.[80 chars]3.0)]
First differing element 1:
Row(var='int', val=20.0)
Row(var='double', val=1.0)
  [Row(var='int', val=10.0),
+  Row(var='double', val=1.0),
   Row(var='int', val=20.0),
+  Row(var='double', val=2.0),
   Row(var='int', val=30.0),
-  Row(var='double', val=1.0),
-  Row(var='double', val=2.0),
   Row(var='double', val=3.0)]
```

### Does this PR introduce _any_ user-facing change?
no, test-only

### How was this patch tested?
CI

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #52245 from zhengruifeng/test_unpivot_fix.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>