[SPARK-55746][SQL][TESTS] Fix unable to load custom metric object SupportedV1WriteMetric
### What changes were proposed in this pull request?

Bug was introduced by SPARK-50315 (https://github.com/apache/spark/pull/48867), won't fail the test, just causes lots of warning logs
```
$ build/sbt "sql/testOnly *V1WriteFallbackSuite"
...
18:06:25.108 WARN org.apache.spark.sql.execution.ui.SQLAppStatusListener: Unable to load custom metric object for class `org.apache.spark.sql.connector.SupportedV1WriteMetric`. Please make sure that the custom metric class is in the classpath and it has 0-arg constructor.
org.apache.spark.SparkException: org.apache.spark.sql.connector.SupportedV1WriteMetric did not have a zero-argument constructor or a single-argument constructor that accepts SparkConf. Note: if the class is defined inside of another Scala class, then its constructors may accept an implicit parameter that references the enclosing class; in this case, you must define the class as a top-level class in order to prevent this extra parameter from breaking Spark's ability to find a valid constructor.
	at org.apache.spark.util.Utils$.$anonfun$loadExtensions$1(Utils.scala:2871)
	at scala.collection.immutable.List.flatMap(List.scala:283)
	at scala.collection.immutable.List.flatMap(List.scala:79)
	at org.apache.spark.util.Utils$.loadExtensions(Utils.scala:2853)
	at org.apache.spark.sql.execution.ui.SQLAppStatusListener.$anonfun$aggregateMetrics$3(SQLAppStatusListener.scala:220)
	at scala.Option.map(Option.scala:242)
	at org.apache.spark.sql.execution.ui.SQLAppStatusListener.$anonfun$aggregateMetrics$2(SQLAppStatusListener.scala:214)
... (repeat many times)
```

### Why are the changes needed?

Fix UT.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Verified locally, no warnings printed after fixing.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #54544 from pan3793/SPARK-55746.

Authored-by: Cheng Pan <chengpan@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>