[SPARK-54508][PYTHON] Fix `spark-pipelines` to resolve `spec` file path more robustly
### What changes were proposed in this pull request?

Fixes a bug that causes executing `spark-pipelines` with a spec file in a subdirectory to fail:

```
spark-pipelines run --spec subdir/spark-pipelines.yml
```

results in

```
pyspark.errors.exceptions.connect.AnalysisException: [RUN_EMPTY_PIPELINE] Pipelines are expected to have at least one non-temporary dataset defined (tables, persisted views) but no non-temporary datasets were found in your pipeline.
```

### Why are the changes needed?

Fix a bug.

### Does this PR introduce _any_ user-facing change?

Fixes a user-facing bug

### How was this patch tested?

Ran
```
spark-pipelines run --spec subdir/spark-pipelines.yml
```

Observed it fail before the change and succeed after.

With our current Pipelines CLI unit testing setup, there isn't a straightforward way to write a test for this, but I'm investigating whether we can augment it.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #53219 from sryza/cli-relative-path.

Authored-by: Sandy Ryza <sandy.ryza@databricks.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
(cherry picked from commit c61d40c88f7bb50e81b7fb98852a96b2e6296b59)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>