[SPARK-39359][SQL] Restrict DEFAULT columns to allowlist of supported data source types
### What changes were proposed in this pull request?

Restrict DEFAULT columns to allowlist of supported data source types.

Example:

```
> create table t(a string) using avro
> alter table t add column(b int default 42)
AnalysisException: Failed to execute command because target data source type avro does not support assigning DEFAULT column values
```

### Why are the changes needed?

This change is necessary for correctness because each data source allowing DEFAULT column values must include support for returning these values when missing in the corresponding storage.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

This PR adds unit test coverage.

Closes #36745 from dtenedor/restrict-datasources.

Authored-by: Daniel Tenedorio <daniel.tenedorio@databricks.com>
Signed-off-by: Gengliang Wang <gengliang@apache.org>