[SPARK-54599][PYTHON] Refactor PythonException so it can take errorClass with sqlstate
### What changes were proposed in this pull request?

In general we want an `sqlstate` with `PythonException` to be better categorized. This PR basically rewrite `PythonException` to `SparkPythonException` style. For now we report `38000` for all existing exceptions, but we leave the flexibility to future changes.

I also want to take this chance to make the user side exception print a bit more pythonic.

### Why are the changes needed?

Many reported PythonExceptions can't be categorized by `sqlstate` which is not helpful to triage and build metrics.

### Does this PR introduce _any_ user-facing change?

Yes. Some `Py4JJavaError` will become `PythonException` now - those raised by python workers. I think that's an improvement.

Also, the exception report would be different.

code:
```python
from pyspark.sql import SparkSession
from pyspark.sql import functions as F

spark = SparkSession.builder.getOrCreate()

F.udf
def add_one(x):
    raise ValueError()

df = spark.createDataFrame([(1,), (2,), (3,)], ["value"])
df = df.withColumn("value_plus_one", add_one("value"))

df.show()
```

Current traceback:

```
Traceback (most recent call last):
  File "/Users/gaotian/programs/spark/python/example.py", line 15, in <module>
    df.show()
  File "/Users/gaotian/programs/spark/python/pyspark/sql/classic/dataframe.py", line 285, in show
    print(self._show_string(n, truncate, vertical))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gaotian/programs/spark/python/pyspark/sql/classic/dataframe.py", line 303, in _show_string
    return self._jdf.showString(n, 20, vertical)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gaotian/programs/spark/venv/lib/python3.12/site-packages/py4j/java_gateway.py", line 1362, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/Users/gaotian/programs/spark/python/pyspark/errors/exceptions/captured.py", line 269, in deco
    raise converted from None
  File "/Users/gaotian/programs/spark/python/example.py", line 9, in add_one
    raise ValueError()
      ^^^^^^^^^^^^^^^^^
pyspark.errors.exceptions.captured.PythonException:
  An exception was thrown from the Python worker. Please see the stack trace below.
Traceback (most recent call last):
  File "/Users/gaotian/programs/spark/python/example.py", line 8, in add_one
    raise ValueError()
ValueError
```

Without any change, the worker part traceback would be like

```
pyspark.errors.exceptions.captured.PythonException: [PYTHON_EXCEPTION] Python worker failed with the following error:
Traceback (most recent call last):
  File "/Users/gaotian/programs/spark/python/example.py", line 8, in add_one
    raise ValueError()
ValueError
 SQLSTATE: 38000
```

I think moving the exception explanation right after the Exception type is good - that's intuitive to Python users compared to having a new line. But that line is too long. I think we should have a special `__str__` method for `PythonException` instead of using the default `getMessage()`

Option 1: Remove the errorClass and SQLSTATE because end users are not that interested

```
pyspark.errors.exceptions.captured.PythonException: Python worker failed with the following error:
Traceback (most recent call last):
  File "/Users/gaotian/programs/spark/python/example.py", line 8, in add_one
    raise ValueError()
ValueError
```

Option 2: Do some magic to print the exception that user is supposed to use to catch - instead of exposing our implementation details.

```
pyspark.errors.PythonException: Python worker failed with the following error:
Traceback (most recent call last):
  File "/Users/gaotian/programs/spark/python/example.py", line 8, in add_one
    raise ValueError()
ValueError
```

Option 3: We actually have two traceback from worker printed, which is weird. I think we should just keep one. We should not artificially combine the tracebacks from the driver and the worker

```
  File "/Users/gaotian/programs/spark/python/pyspark/errors/exceptions/captured.py", line 269, in deco
    raise converted from None
  File "/Users/gaotian/programs/spark/python/example.py", line 9, in add_one. -> THIS SHOULD BE REMOVED!
    raise ValueError()
      ^^^^^^^^^^^^^^^^^
pyspark.errors.PythonException: Python worker failed with the following error:
Traceback (most recent call last):
  File "/Users/gaotian/programs/spark/python/example.py", line 8, in add_one
    raise ValueError()
ValueError
```

New print:

```
Traceback (most recent call last):
  File "/Users/gaotian/programs/spark/python/example.py", line 15, in <module>
    df.show()
  File "/Users/gaotian/programs/spark/python/pyspark/sql/classic/dataframe.py", line 285, in show
    print(self._show_string(n, truncate, vertical))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gaotian/programs/spark/python/pyspark/sql/classic/dataframe.py", line 303, in _show_string
    return self._jdf.showString(n, 20, vertical)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gaotian/programs/spark/venv/lib/python3.12/site-packages/py4j/java_gateway.py", line 1362, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/Users/gaotian/programs/spark/python/pyspark/errors/exceptions/captured.py", line 269, in deco
    raise converted from None
pyspark.errors.PythonException: Python worker failed with the following error:
Traceback (most recent call last):
  File "/Users/gaotian/programs/spark/python/example.py", line 8, in add_one
    raise ValueError()
ValueError
```

### How was this patch tested?

CI

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #53099 from gaogaotiantian/add-sqlstate-python-exception.

Authored-by: Tian Gao <gaogaotiantian@hotmail.com>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>