[SPARK-55730][PYTHON] Not make timezone lower case
### What changes were proposed in this pull request?

Not make timezone lower case.

### Why are the changes needed?

The resolution of timezone has been changed in pandas 3:

- https://pandas.pydata.org/pandas-docs/version/3.0/whatsnew/v3.0.0.html#pytz-now-an-optional-dependency

which caused the issue that a lowercase timezone is not recognized by pandas' search in some environment.

```
...
  File "/.../pandas/_libs/tslibs/timezones.pyx", line 133, in pandas._libs.tslibs.timezones.maybe_get_tz
  File "/.../pandas/_libs/tslibs/timezones.pyx", line 158, in pandas._libs.tslibs.timezones.maybe_get_tz
  File "/.../zoneinfo/_common.py", line 24, in load_tzdata
    raise ZoneInfoNotFoundError(f"No time zone found with key {key}")
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key etc/utc'
```

If it's `Etc/UTC`, it works.

### Does this PR introduce _any_ user-facing change?

Yes, it will behave more like pandas 3.

### How was this patch tested?

Manually.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #54528 from ueshin/issues/SPARK-55730/timezone.

Authored-by: Takuya Ueshin <ueshin@databricks.com>
Signed-off-by: Takuya Ueshin <ueshin@databricks.com>