[SPARK-55696][SQL] Add explicit error to Encoders.bean for interface class
### What changes were proposed in this pull request?
Add explicit error message to Encoders.bean against interfaces

### Why are the changes needed?

For bean Encoders, the de-serializer uses the constructor inferred from the bean Encoder.  ie, we get the bytes back, the Dataset deserialization will use the Encoder's interface class to try to construct  , and fail.

Code ref:
https://github.com/apache/spark/blob/b3703755d80585297367d539de9fa8c5783b1c6b/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/DeserializerBuildHelper.scala#L482

### Does this PR introduce _any_ user-facing change?
No, it already fails today with another message:
```
java.lang.IllegalStateException: found an unhandled type: null
      at org.apache.commons.lang3.reflect.TypeUtils.getTypeArguments(TypeUtils.java:915)
      at org.apache.commons.lang3.reflect.TypeUtils.getTypeArguments(TypeUtils.java:791)
      at org.apache.commons.lang3.reflect.TypeUtils.getTypeArguments(TypeUtils.java:886)
      at org.apache.commons.lang3.reflect.TypeUtils.getTypeArguments(TypeUtils.java:873)
      at org.apache.spark.sql.catalyst.JavaTypeInference$.encoderFor(JavaTypeInference.scala:159)
      at org.apache.spark.sql.catalyst.JavaTypeInference$.encoderFor(JavaTypeInference.scala:63)
      at org.apache.spark.sql.catalyst.JavaTypeInference$.encoderFor(JavaTypeInference.scala:56)
      at org.apache.spark.sql.Encoders$.bean(Encoders.scala:211)
      at org.apache.spark.sql.Encoders.bean(Encoders.scala)

```
it will now fail more explicitly.

### How was this patch tested?
Added unit test in JavaDatasetSuite

### Was this patch authored or co-authored using generative AI tooling?
Yes, cursor

Closes #54494 from szehon-ho/encoder_interface.

Authored-by: Szehon Ho <szehon.apache@gmail.com>
Signed-off-by: Cheng Pan <chengpan@apache.org>