[SPARK-52593][PS] Avoid CAST_INVALID_INPUT of `MultiIndex.to_series`, `Series.dot` and `DataFrame.dot` in ANSI mode
### What changes were proposed in this pull request?
Under ANSI, `MultiIndex.to_series` fails with CAST_INVALID_INPUT, which further fails `Series.dot` and `DataFrame.dot`.

The PR aims to avoid CAST_INVALID_INPUT in the above three API.

### Why are the changes needed?
Ensure pandas on Spark works well with ANSI mode on.
Part of https://issues.apache.org/jira/browse/SPARK-52556.

### Does this PR introduce _any_ user-facing change?
Yes. The root cause `MultiIndex.to_series` works as show below:

```py
>>> arrays = [[1,  2], ["red", "blue"]]
>>> pidx = pd.MultiIndex.from_arrays(arrays, names=("number", "color"))
>>> psidx = ps.from_pandas(pidx)
```

FROM
```py
>>> psidx.to_series()
...
org.apache.spark.SparkNumberFormatException: [CAST_INVALID_INPUT] The value 'blue' of the type "STRING" cannot be cast to "BIGINT" because it is malformed. Correct the value as per the syntax, or change its target type. Use `try_cast` to tolerate malformed input and return NULL instead. SQLSTATE: 22018
...
```

TO
```py
>>> psidx.to_series()
number  color
1       red       [1, red]
2       blue     [2, blue]
dtype: object
```

So `Series.dot` and `DataFrame.dot` work under ANSI.

### How was this patch tested?
Unit tests.
Commands below pass.

```
 1019  SPARK_ANSI_SQL_MODE=true ./python/run-tests --python-executables=python3.11 --testnames "pyspark.pandas.tests.indexes.test_conversion ConversionTests.test_to_series"
 1020  SPARK_ANSI_SQL_MODE=false ./python/run-tests --python-executables=python3.11 --testnames "pyspark.pandas.tests.indexes.test_conversion ConversionTests.test_to_series"
```

```
 1060  SPARK_ANSI_SQL_MODE=true  ./python/run-tests --python-executables=python3.11 --testnames "pyspark.pandas.tests.series.test_series SeriesTests.test_dot"
 1061  SPARK_ANSI_SQL_MODE=false  ./python/run-tests --python-executables=python3.11 --testnames "pyspark.pandas.tests.series.test_series SeriesTests.test_dot"
```

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #51310 from xinrong-meng/series_dot.

Lead-authored-by: Xinrong Meng <xinrong@apache.org>
Co-authored-by: Xinrong Meng <xinrong.apache@gmail.com>
Signed-off-by: Xinrong Meng <xinrong@apache.org>