[SPARK-55403][PS] Fix `no attribute 'draw'` error in the plot tests with pandas 3
### What changes were proposed in this pull request?

Fixes `no attribute 'draw'` error in the plot tests with pandas 3.

### Why are the changes needed?

The plot tests fail with the following error working with pandas 3:

```
Traceback (most recent call last):
...
  File "/.../python/pyspark/pandas/plot/matplotlib.py", line 971, in _plot
    plot_obj.draw()
    ^^^^^^^^^^^^^
AttributeError: 'PandasOnSparkAreaPlot' object has no attribute 'draw'
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

The existing tests should pass.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #54186 from ueshin/issues/SPARK-55403/plot.

Authored-by: Takuya Ueshin <ueshin@databricks.com>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>