[SPARK-54348][INFRA] Recover Python unit tests CI by installing `zstandard==0.25.0`
### What changes were proposed in this pull request?

In https://github.com/apache/spark/pull/53024#issuecomment-3530340077, PR CI Python unit tests failed due to
```
pyspark.errors.exceptions.base.PySparkImportError: [PACKAGE_NOT_INSTALLED] zstandard >= 0.25.0 must be installed; however, it was not found.
```
This PR add the required dependency to the pre-merge CI.

### Why are the changes needed?

Recover Python unit tests CI

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

PR #53024 Python CI back to healthy with this change

### Was this patch authored or co-authored using generative AI tooling?

No

Closes #53058 from SCHJonathan/jonathan-chang_data/fix-python-ci-dep.

Authored-by: Yuheng Chang <jonathanyuheng@gmail.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
(cherry picked from commit a916690d6101419297c98a4c42ecf47e24f97f43)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>