[SPARK-52671][SQL] RowEncoder shall not lookup a resolved UDT
### What changes were proposed in this pull request?

This PR fixes a bug shown below
```sql
spark-sql (default)> select submissionTime from bbb;
xxx
spark-sql (default)> cache table a as select submissionTime from bbb;
org.apache.spark.SparkException: xxx is not annotated with SQLUserDefinedType nor registered with UDTRegistration.}
	at org.apache.spark.sql.errors.ExecutionErrors.userDefinedTypeNotAnnotatedAndRegisteredError(ExecutionErrors.scala:167)
	at org.apache.spark.sql.errors.ExecutionErrors.userDefinedTypeNotAnnotatedAndRegisteredError$(ExecutionErrors.scala:163)
	at org.apache.spark.sql.errors.ExecutionErrors$.userDefinedTypeNotAnnotatedAndRegisteredError(ExecutionErrors.scala:259)
	at org.apache.spark.sql.catalyst.encoders.RowEncoder$.$anonfun$encoderForDataType$1(RowEncoder.scala:108)
	at scala.Option.getOrElse(Option.scala:201)
	at org.apache.spark.sql.catalyst.encoders.RowEncoder$.encoderForDataType(RowEncoder.scala:108)
	at org.apache.spark.sql.catalyst.encoders.RowEncoder$.$anonfun$encoderForDataType$2(RowEncoder.scala:128)
	at scala.collection.ArrayOps$.map$extension(ArrayOps.scala:936)
	at org.apache.spark.sql.catalyst.encoders.RowEncoder$.encoderForDataType(RowEncoder.scala:125)
	at org.apache.spark.sql.catalyst.encoders.RowEncoder$.encoderFor(RowEncoder.scala:69)
	at org.apache.spark.sql.catalyst.encoders.RowEncoder$.encoderFor(RowEncoder.scala:65)
	at org.apache.spark.sql.classic.Dataset.toDF(Dataset.scala:519)
	at org.apache.spark.sql.classic.Dataset.groupBy(Dataset.scala:941)
	at org.apache.spark.sql.classic.Dataset.count(Dataset.scala:1501)
```

The RowEncoder tried to relookup a UDT which is already resolved

### Why are the changes needed?
bugfix

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?

modified tests in sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/encoders/RowEncoderSuite.scala

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #51360 from yaooqinn/SPARK-52671.

Authored-by: Kent Yao <yao@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>