[SPARK-53165][CORE] Add `SparkExitCode.CLASS_NOT_FOUND`
### What changes were proposed in this pull request?

This PR aims to promote the existing exit code, 101, to the official `SparkExitCode` at Apache Spark 4.1.0.

### Why are the changes needed?

`SparkSubmit` has been exposing the exit code, `101`, in case of `ClassNotFoundException` or `NoClassDefFoundError`. We had better register this as `SparkExitCode` class for consistency.

https://github.com/apache/spark/blob/46fd5258a16523637f7ac5fa7ece16f626816454/core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala#L1083

### Does this PR introduce _any_ user-facing change?

No behavior change.

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #51892 from dongjoon-hyun/SPARK-53165.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>