Extract VertexRDD interface and move implementation to VertexRDDImpl
This breaks binary compatibility with the error

    java.lang.IncompatibleClassChangeError: Found interface
    org.apache.spark.graphx.VertexRDD, but class was expected

The solution is to do a clean rebuild (sbt/sbt clean assembly).