[SPARK-40648][YARN][TESTS] Add `@ExtendedLevelDBTest` to `LevelDB` relevant tests in the `yarn` module
### What changes were proposed in this pull request?
SPARK-40490 make  the test case related to `YarnShuffleIntegrationSuite` starts to verify the `registeredExecFile` reload test scenario again，so this pr add `ExtendedLevelDBTest` to `LevelDB` relevant tests in the `yarn` module so that the `MacOs/Apple Silicon` can skip the tests through `-Dtest.exclude.tags=org.apache.spark.tags.ExtendedLevelDBTest`.

### Why are the changes needed?
According to convention, Add `ExtendedLevelDBTest` to LevelDB relevant tests to make `yarn` module can skip these tests through `-Dtest.exclude.tags=org.apache.spark.tags.ExtendedLevelDBTest` on `MacOs/Apple Silicon`.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
- Pass GitHub Actions
- Manual test on `MacOs/Apple Silicon`

```
mvn clean install -pl resource-managers/yarn -Pyarn -am -DskipTests
mvn clean install -pl resource-managers/yarn -Pyarn -Dtest.exclude.tags=org.apache.spark.tags.ExtendedLevelDBTest
```

**Before**

```
*** RUN ABORTED ***
  java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no leveldbjni64-1.8 in java.library.path, no leveldbjni-1.8 in java.library.path, no leveldbjni in java.library.path, /Users/yangjie01/SourceCode/git/spark-source/resource-managers/yarn/target/tmp/libleveldbjni-64-1-7057248091178764836.8: dlopen(/Users/yangjie01/SourceCode/git/spark-source/resource-managers/yarn/target/tmp/libleveldbjni-64-1-7057248091178764836.8, 1): no suitable image found.  Did find:
	/Users/yangjie01/SourceCode/git/spark-source/resource-managers/yarn/target/tmp/libleveldbjni-64-1-7057248091178764836.8: no matching architecture in universal wrapper
	/Users/yangjie01/SourceCode/git/spark-source/resource-managers/yarn/target/tmp/libleveldbjni-64-1-7057248091178764836.8: no matching architecture in universal wrapper]
  at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
  at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
  at org.fusesource.leveldbjni.JniDBFactory.<clinit>(JniDBFactory.java:48)
  at org.apache.spark.network.util.LevelDBProvider.initLevelDB(LevelDBProvider.java:48)
  at org.apache.spark.network.util.DBProvider.initDB(DBProvider.java:40)
  at org.apache.spark.network.shuffle.ExternalShuffleBlockResolver.<init>(ExternalShuffleBlockResolver.java:131)
  at org.apache.spark.network.shuffle.ExternalShuffleBlockResolver.<init>(ExternalShuffleBlockResolver.java:100)
  at org.apache.spark.network.shuffle.ExternalBlockHandler.<init>(ExternalBlockHandler.java:90)
  at org.apache.spark.network.yarn.YarnShuffleService.serviceInit(YarnShuffleService.java:276)
  at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
  ...
```

**After**

```
Run completed in 9 minutes, 46 seconds.
Total number of tests run: 164
Suites: completed 23, aborted 0
Tests: succeeded 164, failed 0, canceled 1, ignored 0, pending 0
All tests passed.
```

Closes #38095 from LuciferYang/SPARK-40648.

Authored-by: yangjie01 <yangjie01@baidu.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>