[SPARK-55901][PS] Raise an error from Series.replace() with no arguments
### What changes were proposed in this pull request?

Raises an error from `Series.replace()` with no arguments.

### Why are the changes needed?

In pandas 3, `Series.replace()` doesn't allow no arguments.

For example:

```py
>>> pser = pd.Series([10, 20, 15, 30, np.nan], name="x")
```

- pandas 2

```py
>>> pser.replace()
<stdin>:1: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
0    10.0
1    20.0
2    15.0
3    30.0
4    30.0
Name: x, dtype: float64
```

- pandas 3

```py
>>> pser.replace()
Traceback (most recent call last):
...
ValueError: Series.replace must specify either 'value', a dict-like 'to_replace', or dict-like 'regex'.
```

### Does this PR introduce _any_ user-facing change?

Yes, it will behave more like pandas 3.

### How was this patch tested?

Updated the related tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #54703 from ueshin/issues/SPARK-55901/replace.

Authored-by: Takuya Ueshin <ueshin@databricks.com>
Signed-off-by: Takuya Ueshin <ueshin@databricks.com>