[SPARK-44643][SQL][PYTHON] Fix Row.__repr__ for the case the field is empty Row
### What changes were proposed in this pull request?

Fix `Row.__repr__` for the case the field is empty `Row`.

```py
>>> repr(Row(Row()))
'<Row(<Row()>)>'
```

### Why are the changes needed?

`Row.__repr__` is broken when it contains an empty `Row`:

```py
>>> repr(Row(Row()))
Traceback (most recent call last):
...
TypeError: not enough arguments for format string
```

### Does this PR introduce _any_ user-facing change?

`Row` that contains an empty `Row` will be shown in the REPL.

### How was this patch tested?

Added the related test.

Closes #42303 from ueshin/issues/SPARK-44643/repr_row.

Authored-by: Takuya UESHIN <ueshin@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>