[SPARK-43968][PYTHON][3.5] Improve error messages for Python UDTFs with wrong number of outputs
### What changes were proposed in this pull request?

This PR cherry-picks 7194ce9263fe1683c039a1aaf9462657b1672a99. It improves the error messages for Python UDTFs when the number of outputs mismatches the number of outputs specified in the return type of the UDTFs.

### Why are the changes needed?

To make Python UDTFs more user-friendly.

### Does this PR introduce _any_ user-facing change?

Yes. This PR improves the error messages.
Before this change, the error thrown by Spark will be a java IllegalStateException:
```
java.lang.IllegalStateException: Input row doesn't have expected number of values required by the schema
```
After this PR, it will throw a clearer error message with an error class:
```
[UDTF_RETURN_SCHEMA_MISMATCH] The number of columns in the result does not match the specified schema
```

### How was this patch tested?

Existing tests and new unit tests.

Closes #42192 from allisonwang-db/spark-43968-3.5.

Authored-by: allisonwang-db <allison.wang@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>