[SPARK-45619][CONNECT][PYTHON] Apply the observed metrics to Observation object
### What changes were proposed in this pull request?

Apply the observed metrics to `Observation` object.

### Why are the changes needed?

When using `Observation`, the observed metrics should be applied to the object.

For example, in vanilla PySpark:

```py
>>> df = spark.createDataFrame([["Alice", 2], ["Bob", 5]], ["name", "age"])
>>> observation = Observation("my metrics")
>>> observed_df = df.observe(observation, count(lit(1)).alias("count"), max(col("age")))
>>> observed_df.count()
2
>>>
>>> observation.get
{'count': 2, 'max(age)': 5}
```

whereas in Spark Connect, currently it fails with `PySparkNotImplementedError`:

```py
>>> observation.get
Traceback (most recent call last):
...
    raise PySparkNotImplementedError(
pyspark.errors.exceptions.base.PySparkNotImplementedError: [NOT_IMPLEMENTED] Observation support for Spark Connect is not implemented.
```

### Does this PR introduce _any_ user-facing change?

Yes, the `Observation` will see the changes.

### How was this patch tested?

Added/modified the related tests.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #43469 from ueshin/issues/SPARK-45619/observation.

Authored-by: Takuya UESHIN <ueshin@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>