[SPARK-44760][INFRA] Fix list index out of range for JIRA resolution in merge_spark_pr
### What changes were proposed in this pull request?

This PR fixes list index out-of-range error for the merge_spark_pr script

The error occurs when the branch we merge into does not have a jira project version.

```python
>>> versions = sorted(versions, key=lambda x: x.name, reverse=True)
>>> versions
[<JIRA Version: name='4.0.0', id='12353359'>, <JIRA Version: name='3.5.1', id='12353495'>, <JIRA Version: name='3.5.0', id='12352848'>, <JIRA Version: name='3.4.2', id='12353368'>, <JIRA Version: name='3.3.4', id='12353505'>, <JIRA Version: name='3.3.3', id='12352932'>]
>>> list(filter(lambda x: x.name.startswith(""), versions))[-1]
<JIRA Version: name='3.3.3', id='12352932'>
>>> list(filter(lambda x: x.name.startswith("3.2"), versions))[-1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
```

Unlike other archived branches or versions, v3.2.5 is missing from our JIRA. This crushes the merging scripts during JIRA resolution if branch-3.2 is chosen.

### Why are the changes needed?

happy merging

### Does this PR introduce _any_ user-facing change?

no, infra only change

### How was this patch tested?

manually tested

```python
>>> default_fix_versions = []
>>> for b in merge_branches:
...     if b == "master":
...         default_fix_versions.append(versions[0])
...     else:
...         found = False
...         for v in versions:
...             if v.name.startswith(b.replace("branch-", "")):
...                 default_fix_versions.append(v)
...                 found = True
...         if not found:
...             print(
...                 "Target version for %s is not found on JIRA, it may be archived or "
...                 "not created. Skipping it." % b)
...
Target version for branch-3.2 is not found on JIRA, it may be archived or not created. Skipping it.
>>> default_fix_versions
[<JIRA Version: name='4.0.0', id='12353359'>, <JIRA Version: name='3.5.0', id='12352848'>, <JIRA Version: name='3.5.1', id='12353495'>, <JIRA Version: name='3.4.2', id='12353368'>, <JIRA Version: name='3.3.3', id='12352932'>, <JIRA Version: name='3.3.4', id='12353505'>]
>>> quit
```

Closes #42429 from yaooqinn/SPARK-44760.

Authored-by: Kent Yao <yao@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>