[SPARK-40156][SQL] `url_decode()` should the return an error class
### What changes were proposed in this pull request?

url_decode() return an error class when Invalid parameter input. like :
```
spark.sql("SELECT url_decode('http%3A%2F%2spark.apache.org')").show
```

output:
```
org.apache.spark.SparkIllegalArgumentException: [CANNOT_DECODE_URL] Cannot decode url : http%3A%2F%2spark.apache.org.
URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "2s"
	at org.apache.spark.sql.errors.QueryExecutionErrors$.illegalUrlError(QueryExecutionErrors.scala:351)
	at org.apache.spark.sql.catalyst.expressions.UrlCodec$.decode(urlExpressions.scala:117)
	at org.apache.spark.sql.catalyst.expressions.UrlCodec.decode(urlExpressions.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.sql.catalyst.expressions.objects.InvokeLike.invoke(objects.scala:148)
```

### Why are the changes needed?

To improve user experience w/ Spark SQL.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

```
$ build/sbt "sql/testOnly org.apache.spark.sql.SQLQueryTestSuite -- -z url-functions.sql"
```

Closes #37636 from zzzzming95/SPARK-40156.

Lead-authored-by: zhiming she <505306252@qq.com>
Co-authored-by: zzzzming95 <505306252@qq.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>