[SPARK-53594][PYTHON] Make arrow UDF respect user-specified eval type
### What changes were proposed in this pull request?
Make arrow UDF respect user-specified eval type

### Why are the changes needed?
to be consistent with pandas UDF, which allow type hints be partially set:

```
In [4]: arrow_udf("long", ArrowUDFType.SCALAR_ITER)
   ...: def add_one(it: Iterator[pa.Array]):
   ...:     for v in it:
   ...:         yield pa.compute.add(v, 1)
```

before:
```
PySparkValueError: [TYPE_HINT_SHOULD_BE_SPECIFIED] Type hints for the return type should be specified; however, got (it: Iterator[pyarrow.lib.Array]).
```

after:
```
In [4]: arrow_udf("long", ArrowUDFType.SCALAR_ITER)
   ...: def add_one(it: Iterator[pa.Array]):
   ...:     for v in it:
   ...:         yield pa.compute.add(v, 1)
   ...:
/Users/ruifeng.zheng/Dev/spark/python/pyspark/sql/pandas/functions.py:766: UserWarning: It is preferred to specify type hints for arrow UDF instead of specifying arrow UDF type.
  warnings.warn(
```

### Does this PR introduce _any_ user-facing change?
yes

### How was this patch tested?
new tests

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #52351 from zhengruifeng/make_arrow_udf_respect_type.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>