[SPARK-48803][SQL] Throw internal error in Orc(De)serializer to align with ParquetWriteSupport
### What changes were proposed in this pull request?

Kind of follow-up of https://github.com/apache/spark/pull/44275, this PR aligned 2 similar code paths with different error messages into one.

```java
24/07/03 16:29:01 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
org.apache.spark.SparkException: [INTERNAL_ERROR] Unsupported data type VarcharType(64). SQLSTATE: XX000
	at org.apache.spark.SparkException$.internalError(SparkException.scala:92)
	at org.apache.spark.SparkException$.internalError(SparkException.scala:96)
```

```java
org.apache.spark.SparkUnsupportedOperationException: VarcharType(64) is not supported yet.
	at org.apache.spark.sql.errors.QueryExecutionErrors$.dataTypeUnsupportedYetError(QueryExecutionErrors.scala:993)
	at org.apache.spark.sql.execution.datasources.orc.OrcSerializer.newConverter(OrcSerializer.scala:209)
	at org.apache.spark.sql.execution.datasources.orc.OrcSerializer.$anonfun$converters$2(OrcSerializer.scala:35)
	at scala.collection.immutable.List.map(List.scala:247)
```

### Why are the changes needed?

improvement

### Does this PR introduce _any_ user-facing change?

No, users shouldn't face such errors in regular cases.
### How was this patch tested?

passing existing tests

### Was this patch authored or co-authored using generative AI tooling?

no

Closes #47208 from yaooqinn/SPARK-48803.

Authored-by: Kent Yao <yao@apache.org>
Signed-off-by: Dongjoon Hyun <dhyun@apple.com>