[SPARK-54056][SQL] resolve substitution for SQLConf settings in Catalogs
### What changes were proposed in this pull request?
Pass `SQLConf` values through `ConfigReader` bindings, allowing for `${env:xyz} -> sys.env.get("xyz")` substitution before passing the settings to `CatalogPlugin` implementations.

### Why are the changes needed?
Settings for custom (table) catalog are not being rendered the same way as any other `SQLConf` settings. Particular catalog can define its own set of properties along with custom name for that catalog, e.g. "spark.sql.catalog.test-name". This prevents from registering these properties using [SQLConf.buildConf](https://github.com/apache/spark/blob/54dee4a4b59cf3817f15da46d35f42a81a3b1c07/sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala#L111) machinery, meaning that [ConfigReader bindings](https://github.com/apache/spark/blob/fe904e6973b7a8fdadc5e253a6a74e8ccb359287/common/utils/src/main/scala/org/apache/spark/internal/config/ConfigReader.scala#L54-L57) are being skipped during properties resolution flow.
This becomes an issue if such props are set in config files like `spark-defaults.conf` and not through code (where we can access `sys.env` directly).

```
scala> spark.conf.set("spark.sql.catalog.mssql", "org.apache.spark.sql.execution.datasources.v2.jdbc.JDBCTableCatalog")
scala> spark.conf.set("spark.sql.catalog.mssql.url", "jdbc:sqlserver://...")
scala> spark.conf.set("spark.sql.catalog.mssql.user", "${env:MSSQL_USER}")
scala> spark.conf.set("spark.sql.catalog.mssql.password", "${env:MSSQL_PASSWORD}")
scala> spark.sql("show tables in mssql").show()
com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user '${env:MSSQL_PASSWORD}'. ClientConnectionId:4f9efa06-90bb-4498-9099-b1d9d3fac935
  at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:278)
```

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
* unit testing is tricky for this change cause' we need to deal with `sys.env` or `sys.props`. At the same time, `Catalogs` is object which doesn't allow us to override `ConfigReader` the same way its done in [ConfigReaderSuite](https://github.com/apache/spark/blob/b7763a7eae2b9609012cbb4ce981276c6471cc4e/core/src/test/scala/org/apache/spark/internal/config/ConfigReaderSuite.scala#L27-L31)
* manual testing via `spark-shell`
```
export MSSQL_USER=...
export MSSQL_PASSWORD=...
./bin/spark-shell --master local --driver-class-path mssql-jdbc-13.2.0.jre11.jar --jars mssql-jdbc-13.2.0.jre11.jar
...
scala> sys.env.get("MSSQL_USER")
val res0: Option[String] = Some(...)

scala> spark.conf.set("spark.sql.catalog.mssql", "org.apache.spark.sql.execution.datasources.v2.jdbc.JDBCTableCatalog")
scala> spark.conf.set("spark.sql.catalog.mssql.url", "jdbc:sqlserver://...")
scala> spark.conf.set("spark.sql.catalog.mssql.user", "${env:MSSQL_USER}")
scala> spark.conf.set("spark.sql.catalog.mssql.password", "${env:MSSQL_PASSWORD}")
scala> spark.sql("show tables in mssql").show()
+---------+-------------------+-----------+
|namespace|          tableName|isTemporary|
+---------+-------------------+-----------+
...
```

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #52759 from EugeneYushin/catalogs-load-conf.

Lead-authored-by: EugenYushin <evgenij.ushin@gmail.com>
Co-authored-by: Wenchen Fan <cloud0fan@gmail.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>
(cherry picked from commit a1428d40970fdf9f884b0d63d2f0aefd2a18bc4e)
Signed-off-by: Wenchen Fan <wenchen@databricks.com>