[MINOR][BUILD] Fix merge_spark_pr script for no jira case
### What changes were proposed in this pull request?

This patch tries to fix the merge script `merge_spark_pr` for no jira case by defining the `asf_jira` variable in the script.

### Why are the changes needed?

When I just tried to merge one minor PR which doesn't have jira, I didn't have jira settings and got the following error:

```
Continue without jira? (y/N): y
git rev-parse --abbrev-ref HEAD
Which pull request would you like to merge? (e.g. 34): ...
Restoring head pointer to master
git checkout master
Already on 'master'
git branch
Traceback (most recent call last):
  File "/.../dev/merge_spark_pr.py", line 737, in <module>
    main()
  File "/.../dev/merge_spark_pr.py", line 696, in main
    if asf_jira is not None:
NameError: name 'asf_jira' is not defined
```

For the non jira case, `asf_jira` should be defined to avoid the error.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Locally tested.

### Was this patch authored or co-authored using generative AI tooling?

No

Closes #50237 from viirya/fix_merge_script.

Authored-by: Liang-Chi Hsieh <viirya@gmail.com>
Signed-off-by: Liang-Chi Hsieh <viirya@gmail.com>