[SPARK-51941][SQL] Fix the precision problem for convertToCatalyst when the Input is BigDecimal between -1.0 and 1.0
### What changes were proposed in this pull request?
In [SPARK-20211](https://issues.apache.org/jira/browse/SPARK-20211), we addressed a fix with BigDecimal type conversion exceptions. However, the CatalystTypeConverters.convertToCatalyst method was not updated accordingly, causing users to still encounter exceptions when attempting to convert BigDecimal types. Below is a reproducible example case for this problem.
```
CatalystTypeConverters.convertToCatalyst(BigDecimal("0.01"))
```
```
Decimal scale (2) cannot be greater than precision (1).
org.apache.spark.sql.AnalysisException: Decimal scale (2) cannot be greater than precision (1).
    at org.apache.spark.sql.errors.DataTypeErrors$.decimalCannotGreaterThanPrecisionError(DataTypeErrors.scala:122)
    at org.apache.spark.sql.types.DecimalType.<init>(DecimalType.scala:46)
    at org.apache.spark.sql.catalyst.CatalystTypeConverters$.convertToCatalyst(CatalystTypeConverters.scala:578)
    at org.apache.spark.sql.catalyst.CatalystTypeConvertersSuite.$anonfun$new$18(CatalystTypeConvertersSuite.scala:159)
```

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Newly added test.

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #50747 from jackylee-ch/fix_convertToCatalyst_with_BigDecimal.

Authored-by: jackylee-ch <lijunqing@baidu.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>