[SPARK-55071][CONNECT][PYTHON] Make spark.addArtifact work with Windows paths
### What changes were proposed in this pull request?

Currently, `spark.addArtifact` in pyspark connect does not support absolute Windows paths.
E.g. this code
```
spark.addArtifact("C:\\path\\to\\file.py", pyfile=True)
```
will result in the following error
```
PySparkRuntimeError: [UNSUPPORTED_OPERATION] c scheme is not supported.
```
This error is caused by the `urlparse` function in [artifact.py.](https://github.com/apache/spark/blob/ac13473fff64919e8e7756e3a42ce3a68627dd73/python/pyspark/sql/connect/client/artifact.py#L188). It incorrectly interprets local Windows path, e.g. `C:\\path\\to\\file`, as a URI with 'C' scheme and throws an error because this URI scheme is not known and not supported.

The fix is to detect absolute windows paths before calling `urlparse`, to convert them to a `file://` URI, for example `"C:\\Users\\alex.khakhlyuk\\test.py"` -> `"file:///C:/Users/alex.khakhlyuk/test.py"`, and to proceed parsing the `URI` with urlparse as for regular paths and URIs.

### Why are the changes needed?

`spark.addArtifact` currently doesn't support absolute Windows paths, this should be fixed.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

I ran a test locally on a windows machine.
```
bin/pyspark --remote "local[*]"
spark.addArtifact("C:\\Users\\alex.khakhlyuk\\test.py", pyfile=True)
```
before:
```
PySparkRuntimeError: [UNSUPPORTED_OPERATION] c scheme is not supported.
```
after:
- artifact upload succeeds

It is quite tricky to write a test for windows path handling that will run on a linux CI machine.
You can't create a real absolute Windows path on a Linux machine. If you run tests with a non-existent absolute Windows path, `Path(windows_path).resolve().as_uri()` will intrerpret it as a relative path and will resolve it to `{cwd}/C:\\...` which also doesn't exist.

I could create some test with a bunch of mocking but I doubt how useful that would be.

Existing tests make sure that we don't break existing behaviour.

### Was this patch authored or co-authored using generative AI tooling?

No

Closes #53834 from khakhlyuk/fix-addartifact-on-windows.

Authored-by: Alex Khakhlyuk <alex.khakhlyuk@gmail.com>
Signed-off-by: Herman van Hövell <herman@databricks.com>
(cherry picked from commit 888fb67699ca936ef302b1924e8e6fa63dd68b34)
Signed-off-by: Herman van Hövell <herman@databricks.com>