Revert "[MINOR][PYTHON][DOC] Fixed some links in documentation."
This reverts commit c198adcf3268e934f14a1bb76504b84163ef3bb5.

since it's failing the master CI

https://github.com/apache/spark/actions/runs/29875592188/job/88788942949

```
*****************************
* Building Python API docs. *
*****************************
Running Sphinx v8.2.3
loading translations [en]... done
making output directory... done
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
[autosummary] generating autosummary for: development/contributing.rst, development/debugging.rst, development/errors.rst, development/index.rst, development/logger.rst, development/setting_ide.rst, development/testing.rst, getting_started/index.rst, getting_started/install.rst, getting_started/quickstart_connect.ipynb, ..., tutorial/sql/type_conversions.rst, user_guide/ansi_migration_guide.ipynb, user_guide/bugbusting.ipynb, user_guide/dataframes.ipynb, user_guide/dataprep.ipynb, user_guide/index.rst, user_guide/loadandbehold.ipynb, user_guide/sql.ipynb, user_guide/touroftypes.ipynb, user_guide/udfandudtf.ipynb
WARNING: [autosummary] failed to import pyspark.sql.DataStreamReader.
Possible hints:
* AttributeError: module 'pyspark.sql' has no attribute 'DataStreamReader'
* ModuleNotFoundError: No module named 'pyspark.sql.DataStreamReader'
* ImportError:
WARNING: [autosummary] failed to import pyspark.sql.DataStreamWriter.
Possible hints:
* ModuleNotFoundError: No module named 'pyspark.sql.DataStreamWriter'
* AttributeError: module 'pyspark.sql' has no attribute 'DataStreamWriter'
* ImportError:
```

Closes #57415 from zhengruifeng/revert-57359-dev0.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>
(cherry picked from commit dccff5579c4e2f200dc4e7f1bb5d41ec1edccce0)
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>