[SPARK-37657][FOLLOWUP][PYTHON] Separate the tests for pandas < 1.1.0
### What changes were proposed in this pull request?

This follow-ups for SPARK-37657 to separate the test based on pandas version, as the supported minimum pandas version is 1.0.5, but some tests require pandas 1.1.0 and above.

For pandas < 1.1.0, we should test by manually creating the expected result DataFrame.

### Why are the changes needed?

Because pandas < 1.1.0 doesn't support the `datetime_is_numeric` for `(Series|DataFrame).describe()` as below:
```python
>>> pdf.describe(datetime_is_numeric=True)
Traceback (most recent call last):
...
TypeError: describe() got an unexpected keyword argument 'datetime_is_numeric'
```

But we support pandas 1.0.5 as minimum version.

### Does this PR introduce _any_ user-facing change?

No, it's test only

### How was this patch tested?

Unittests

Closes #35063 from itholic/SPARK-37657-fu.

Authored-by: itholic <haejoon.lee@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>