[SPARK-55179][PYTHON][CONNECT] Skip eager column name validation in `df.col_name`
### What changes were proposed in this pull request?
Follow up of https://github.com/apache/spark/pull/51400, also skip eager column name validation in `df.col_name`

### Why are the changes needed?
to be consistent with `df["col_name"]`

### Does this PR introduce _any_ user-facing change?
yes, `df.bad_column` failure will be delayed to analysis or execution

before:
```
In [1]: df = spark.range(10)

In [2]: df.abc
---------------------------------------------------------------------------
...

PySparkAttributeError: [ATTRIBUTE_NOT_SUPPORTED] Attribute `abc` is not supported.

In [3]: df._abc
---------------------------------------------------------------------------
...

PySparkAttributeError: [ATTRIBUTE_NOT_SUPPORTED] Attribute `_abc` is not supported.

In [4]: df.__abc
---------------------------------------------------------------------------
...

PySparkAttributeError: [ATTRIBUTE_NOT_SUPPORTED] Attribute `__abc` is not supported.
```

after:
```
In [1]: df = spark.range(10)

In [2]: df.abc
Out[2]: Column<'abc'>

In [3]: df._abc
Out[3]: Column<'_abc'>

In [4]: df.__abc
---------------------------------------------------------------------------
...

PySparkAttributeError: [ATTRIBUTE_NOT_SUPPORTED] Attribute `__abc` is not supported.
```

### How was this patch tested?
ci

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #53059 from zhengruifeng/lazy_df_dot_col2.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>