[SPARK-40156][SQL][TESTS][FOLLOW-UP] `url_decode()` should the return an error class
### What changes were proposed in this pull request?

url_decode() return an error class when Invalid parameter input. like :
```
spark.sql("SELECT url_decode('http%3A%2F%2spark.apache.org')").show
```

output:
```
org.apache.spark.SparkIllegalArgumentException: [CANNOT_DECODE_URL] Cannot decode url : http%3A%2F%2spark.apache.org.
```

### Why are the changes needed?

To improve user experience w/ Spark SQL.

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

```
$ build/sbt "sql/testOnly org.apache.spark.sql.SQLQueryTestSuite -- -z url-functions.sql"
```

Closes #37709 from zzzzming95/SPARK-40156-test.

Authored-by: zhiming she <505306252@qq.com>
Signed-off-by: Max Gekk <max.gekk@gmail.com>