[SPARK-41290][SQL] Support GENERATED ALWAYS AS expressions for columns in create/replace table statements
### What changes were proposed in this pull request?

Enables creating generated columns in CREATE/REPLACE TABLE statements by specifying a generation expression for a column with GENERATED ALWAYS AS expr.

For example the following will be supported:
```sql
CREATE TABLE default.example (
    time TIMESTAMP,
    date DATE GENERATED ALWAYS AS (CAST(time AS DATE))
)
```

To be more specific this PR
1. Adds parser support for `GENERATED ALWAYS AS expr` in create/replace table statements. Generation expressions are temporarily stored in the field's metadata, and then are parsed/verified in `DataSourceV2Strategy` and used to instantiate v2 [Column](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/java/org/apache/spark/sql/connector/catalog/Column.java).
4. Adds `TableCatalog::capabilities()` and `TableCatalogCapability.SUPPORTS_CREATE_TABLE_WITH_GENERATED_COLUMNS` This will be used to determine whether to allow specifying generation expressions or whether to throw an exception.

### Why are the changes needed?

`GENERATED ALWAYS AS` is SQL standard. These changes will allow defining generated columns in create/replace table statements in Spark SQL.

### Does this PR introduce _any_ user-facing change?

Using `GENERATED ALWAYS AS expr` in CREATE/REPLACE table statements will no longer throw a parsing error. When used with a supporting table catalog the query should progress, when used with a nonsupporting catalog there will be an analysis exception.

Previous behavior:
```
spark-sql> CREATE TABLE default.example (
         >     time TIMESTAMP,
         >     date DATE GENERATED ALWAYS AS (CAST(time AS DATE))
         > )
         > ;
Error in query:
Syntax error at or near 'GENERATED'(line 3, pos 14)

== SQL ==
CREATE TABLE default.example (
    time TIMESTAMP,
    date DATE GENERATED ALWAYS AS (CAST(time AS DATE))
--------------^^^
)
```

New behavior:
```
AnalysisException: [UNSUPPORTED_FEATURE.TABLE_OPERATION] The feature is not supported: Table `my_tab` does not
support creating generated columns with GENERATED ALWAYS AS expressions. Please check the current catalog and
namespace to make sure the qualified table name is expected, and also check the catalog implementation which is
configured by "spark.sql.catalog".
```

### How was this patch tested?

Adds unit tests

Closes #38823 from allisonport-db/parser-support.

Authored-by: Allison Portis <allison.portis@databricks.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>
(cherry picked from commit bd6b751a5b1c0b9b81039ca554d00e5ef841205d)
Signed-off-by: Wenchen Fan <wenchen@databricks.com>