[SPARK-42444][PYTHON] `DataFrame.drop` should handle duplicated columns properly
### What changes were proposed in this pull request?
Existing implementation always convert inputs (maybe column or column name) to columns, this cause `AMBIGUOUS_REFERENCE` issue since there maybe several columns with the same name.

In the JVM side, the logics of drop(column: Column) and drop(columnName: String) are different, we can not simply always convert a column name to column via col() method.

When there are multi-column with the same name (e.g, `name`), users can:
1, `drop('name')` --- drop all the columns;
2, `drop(df1.name)` --- drop the column from the specific dataframe `df1`;

But if users call `drop(col('name'))`, it will fail due to ambiguous issue.

In Pyspark, it is a bit complex, that the user can input both column names with columns. This PR drops the columns first, and then the column names.

### Why are the changes needed?
bug fix

```
>>> from pyspark.sql import Row
>>> df1 = spark.createDataFrame([(14, "Tom"), (23, "Alice"), (16, "Bob")], ["age", "name"])
>>> df2 = spark.createDataFrame([Row(height=80, name="Tom"), Row(height=85, name="Bob")])
>>> df3 = df1.join(df2, df1.name == df2.name, 'inner')
>>> df3.show()
+---+----+------+----+
|age|name|height|name|
+---+----+------+----+
| 16| Bob|    85| Bob|
| 14| Tom|    80| Tom|
+---+----+------+----+
```

BEFORE
```
>>> df3.drop("name", "age").columns
Traceback (most recent call last):
...
pyspark.errors.exceptions.captured.AnalysisException: [AMBIGUOUS_REFERENCE] Reference `name` is ambiguous, could be: [`name`, `name`].
```

AFTER
```
>>> df3.drop("name", "age").columns
['height']
```

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
added tests

Closes #40135 from zhengruifeng/py_fix_drop.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>