[SPARK-1875]NoClassDefFoundError: StringUtils when building with hadoop 1.x and hive
Author: witgo <witgo@qq.com>

Closes #824 from witgo/SPARK-1875_commons-lang-2.6 and squashes the following commits:

ef7231d [witgo] review commit
ead3c3b [witgo] SPARK-1875:NoClassDefFoundError: StringUtils when building against Hadoop 1

(cherry picked from commit 6a2c5c610c259f62cb12d8cfc18bf59cdb334bb2)
Signed-off-by: Tathagata Das <tathagata.das1565@gmail.com>