Provide more helpful output if stdout is garbled
Before:
  ValueError: invalid literal for int() with base 10
After:
  Launching GatewayServer failed because of stdout interference.
  Silence the following and try again.