[SPARK-38870][SQL][PYSPARK] Make SparkSession.builder return new builder
## Update of previous commits

Fix linter's warnings

For some obscure reason, the CI linting step fails with the following error:

starting mypy examples test...
examples failed mypy checks:
examples/src/main/python/pagerank.py:79: error: unused "type: ignore" comment

This is extremely weird as the pagerank.py seems to be completely
unrelated to the changes made in this ticket.

We removed this "type: ignore" comment to make mypy happy.