[SPARK-46277][PYTHON] Validate startup urls with the config being set
### What changes were proposed in this pull request?
Validate startup urls with the config being set, see example in the "Does this PR introduce _any_ user-facing change".

### Why are the changes needed?
Clear and user-friendly error messages.

### Does this PR introduce _any_ user-facing change?
Yes.

FROM
```py
>>> SparkSession.builder.config(map={"spark.master": "x", "spark.remote": "y"})
<pyspark.sql.session.SparkSession.Builder object at 0x7fa310115b20

>>> SparkSession.builder.config(map={"spark.master": "x", "spark.remote": "y"}).config("x", "z")  # Only raises the error when adding new configs
Traceback (most recent call last):
...
RuntimeError: Spark master cannot be configured with Spark Connect server; however, found URL for Spark Connect [y]
```

TO
```py
>>> SparkSession.builder.config(map={"spark.master": "x", "spark.remote": "y"})
Traceback (most recent call last):
...
RuntimeError: Spark master cannot be configured with Spark Connect server; however, found URL for Spark Connect [y]
```

### How was this patch tested?
Unit tests.

### Was this patch authored or co-authored using generative AI tooling?
No.

Closes #44194 from xinrong-meng/fix_session.

Authored-by: Xinrong Meng <xinrong@apache.org>
Signed-off-by: Xinrong Meng <xinrong@apache.org>