[SPARK-53112][PYTHON][TESTS][FOLLOW-UP] Remove some tests for Non-ANSI
### What changes were proposed in this pull request?
remove some newly added tests which failed in non-ansi

see https://github.com/apache/spark/actions/runs/18025276597/job/51291154866

```
======================================================================
FAIL [1.563s]: test_make_timestamp_ntz (pyspark.sql.tests.test_functions.FunctionsTests.test_make_timestamp_ntz)
Comprehensive test cases for make_timestamp_ntz with various arguments and edge cases.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/spark/spark/python/pyspark/sql/tests/test_functions.py", line 999, in test_make_timestamp_ntz
    with self.assertRaises(Exception):
AssertionError: Exception not raised

----------------------------------------------------------------------
```

### Why are the changes needed?
to make non-ansi schedule job happy

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
manually check

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #52466 from zhengruifeng/remove_ansi_test.

Authored-by: Ruifeng Zheng <ruifengz@apache.org>
Signed-off-by: Ruifeng Zheng <ruifengz@apache.org>