[SPARK-39406][PYTHON] Accept NumPy array in createDataFrame
### What changes were proposed in this pull request?
Accept NunPy array in createDataFrame, with existing dtypes support.

Note that
-  by the constraint of Spark DataFrame, we support 1-dimensional and 2-dimensional arrays only.
- full NunPy <> PySpark mappings will be introduced as a follow-up.

### Why are the changes needed?
As part of SPARK-39405 for NumPy support in SQL.

### Does this PR introduce _any_ user-facing change?
Yes, NumPy array is accepted in createDataFrame now:

Before:
```py
>>> spark.createDataFrame(np.array([[1, 2], [3, 4]]))
Traceback (most recent call last):
...
TypeError: Can not infer schema for type: <class 'numpy.ndarray'>

>>> spark.createDataFrame(np.array([0.1, 0.2]))
Traceback (most recent call last):
...
TypeError: Can not infer schema for type: <class 'numpy.float64'>
```

After:
```py
>>> spark.createDataFrame(np.array([[1, 2], [3, 4]])).show()
+---+---+
| _1| _2|
+---+---+
|  1|  2|
|  3|  4|
+---+---+

>>> spark.createDataFrame(np.array([0.1, 0.2])).show()
+-----+
|value|
+-----+
|  0.1|
|  0.2|
+-----+
```

### How was this patch tested?
Unit tests.

Closes #36793 from xinrong-databricks/createDataFrame2.

Authored-by: Xinrong Meng <xinrong.meng@databricks.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>