[SPARK-38345][SQL] Introduce SQL function ARRAY_SIZE
### What changes were proposed in this pull request?
Introduce SQL function ARRAY_SIZE.

ARRAY_SIZE works the same as SIZE when the input is an array except for:
- ARRAY_SIZE raises an exception for non-array input.
- ARRAY_SIZE always returns null for null input.

### Why are the changes needed?
Counting elements within an array is a common use case. ARRAY_SIZE ensures the input to be an array and then returns the size.

Other DBRMS like Snowflake supports that as well: [Snowflake ARRAY_SIZE](https://docs.snowflake.com/en/sql-reference/functions/array_size.html). Implementing that improves compatibility with DBMS and makes migration easier.

### Does this PR introduce _any_ user-facing change?
Yea. `array_size` is available now.

```
scala> spark.sql("select array_size(array(2, 1))").show()
+-----------------------+
|array_size(array(2, 1))|
+-----------------------+
|                      2|
+-----------------------+

scala> spark.sql("select array_size(map('a', 1, 'b', 2))").show()
org.apache.spark.sql.AnalysisException: cannot resolve 'array_size(map('a', 1, 'b', 2))' due to data type mismatch: argument 1 requires array type, however, 'map('a', 1, 'b', 2)' is of map<string,int> type.; line 1 pos 7;
'Project [unresolvedalias(array_size(map(a, 1, b, 2), None), None)]
```

### How was this patch tested?
Unit tests.

Closes #35671 from xinrong-databricks/array_size.

Authored-by: Xinrong Meng <xinrong.meng@databricks.com>
Signed-off-by: Wenchen Fan <wenchen@databricks.com>