[SPARK-39444][SQL] Add OptimizeSubqueries into nonExcludableRules list
### What changes were proposed in this pull request?

This PR adds `OptimizeSubqueries` rule into nonExcludableRules list.

### Why are the changes needed?

It will throw exception if user `set spark.sql.optimizer.excludedRules=org.apache.spark.sql.catalyst.optimizer.Optimizer$OptimizeSubqueries` before running this query:
```sql
WITH tmp AS (
  SELECT id FROM range(2)
  INTERSECT
  SELECT id FROM range(4)
)

SELECT id FROM range(5) WHERE id > (SELECT max(id) FROM x)
```
Exception:
```
logical intersect  operator should have been replaced by semi-join in the optimizer
java.lang.IllegalStateException: logical intersect  operator should have been replaced by semi-join in the optimizer
```

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Unit test.

Closes #36841 from wangyum/SPARK-39444.

Authored-by: Yuming Wang <yumwang@ebay.com>
Signed-off-by: Hyukjin Kwon <gurwls223@apache.org>